// N1_KANJI — master-level kanji (40 entries)
var N1_KANJI = [
  // Philosophy & abstract concepts
  {c:'優',on:'ユウ',kun:'やさ(しい)',mean:'tenderness, excel, superior',
   kunSentence:'彼は優しい人です。',
   kunSentenceKana:'かれはやさしいひとです。',
   kunSentenceEn:'He is a kind person.',
   onSentence:'優勝（ゆうしょう）を目指す。',
   onSentenceKana:'ゆうしょうをめざす。',
   onSentenceEn:'Aim for victory.'},

  {c:'劣',on:'レツ',kun:'おと(る)',mean:'inferior, be worse than',
   kunSentence:'彼は私より劣っている。',
   kunSentenceKana:'かれはわたしよりおとっている。',
   kunSentenceEn:'He is inferior to me.',
   onSentence:'劣等感（れっとうかん）を克服する。',
   onSentenceKana:'れっとうかんをこくふくする。',
   onSentenceEn:'Overcome feelings of inferiority.'},

  {c:'善',on:'ゼン',kun:'よ(い)',mean:'good, virtue',
   kunSentence:'善い行いをしましょう。',
   kunSentenceKana:'よいおこないをしましょう。',
   kunSentenceEn:'Let\'s do good deeds.',
   onSentence:'改善（かいぜん）の余地がある。',
   onSentenceKana:'かいぜんのよちがある。',
   onSentenceEn:'There is room for improvement.'},

  {c:'悪',on:'アク',kun:'わる(い)',mean:'evil, bad',
   kunSentence:'悪いことをしてはいけない。',
   kunSentenceKana:'わるいことをしてはいけない。',
   kunSentenceEn:'You must not do bad things.',
   onSentence:'悪化（あっか）を防ぐ。',
   onSentenceKana:'あっかをふせぐ。',
   onSentenceEn:'Prevent deterioration.'},

  // Law & governance
  {c:'執',on:'シツ',kun:'と(る)',mean:'grasp, take charge',
   kunSentence:'筆を執る。',
   kunSentenceKana:'ふでをとる。',
   kunSentenceEn:'Take up the pen.',
   onSentence:'執行（しっこう）する。',
   onSentenceKana:'しっこうする。',
   onSentenceEn:'Execute, enforce.'},

  {c:'憲',on:'ケン',kun:'—',mean:'constitution, rule',
   onSentence:'憲法（けんぽう）を遵守する。',
   onSentenceKana:'けんぽうをじゅんしゅする。',
   onSentenceEn:'Obey the constitution.'},

  {c:'裁',on:'サイ',kun:'さば(く)',mean:'judge, decide',
   kunSentence:'事件を裁く。',
   kunSentenceKana:'じけんをさばく。',
   kunSentenceEn:'Judge a case.',
   onSentence:'裁判官（さいばんかん）は公平だ。',
   onSentenceKana:'さいばんかんはこうへいだ。',
   onSentenceEn:'The judge is fair.'},

  // Society & human relations
  {c:'憂',on:'ユウ',kun:'うれ(える)',mean:'sorrow, grieve',
   kunSentence:'彼の将来を憂える。',
   kunSentenceKana:'かれのしょうらいをうれえる。',
   kunSentenceEn:'Worry about his future.',
   onSentence:'憂鬱（ゆううつ）な気分だ。',
   onSentenceKana:'ゆううつなきぶんだ。',
   onSentenceEn:'I feel melancholy.'},

  {c:'愁',on:'シュウ',kun:'うれ(える)',mean:'sorrow, anguish',
   kunSentence:'彼女の悲しみを愁う。',
   kunSentenceKana:'かのじょのかなしみをうれう。',
   kunSentenceEn:'Grieve for her sadness.',
   onSentence:'愁眉（しゅうび）を開く。',
   onSentenceKana:'しゅうびをひらく。',
   onSentenceEn:'Relieve worry.'},

  {c:'慈',on:'ジ',kun:'いつく(しむ)',mean:'mercy, compassion',
   kunSentence:'子どもを慈しむ。',
   kunSentenceKana:'こどもをいつくしむ。',
   kunSentenceEn:'Show affection for children.',
   onSentence:'慈悲（じひ）深い人だ。',
   onSentenceKana:'じひぶかいひとだ。',
   onSentenceEn:'He is a compassionate person.'},

  // Science & technology
  {c:'圏',on:'ケン',kun:'—',mean:'sphere, range, area',
   onSentence:'経済圏（けいざいけん）が広がる。',
   onSentenceKana:'けいざいけんがひろがる。',
   onSentenceEn:'The economic sphere expands.'},

  {c:'域',on:'イキ',kun:'—',mean:'region, boundary',
   onSentence:'地域（ちいき）の活性化を図る。',
   onSentenceKana:'ちいきのかっせいかをはかる。',
   onSentenceEn:'Revitalize the region.'},

  {c:'項',on:'コウ',kun:'—',mean:'paragraph, item',
   onSentence:'次の項目（こうもく）を確認する。',
   onSentenceKana:'つぎのこうもくをかくにんする。',
   onSentenceEn:'Check the next item.'},

  // Culture & arts
  {c:'雅',on:'ガ',kun:'みやび',mean:'elegance, refined',
   kunSentence:'雅（みやび）な趣味を持つ。',
   kunSentenceKana:'みやびなしゅみをもつ。',
   kunSentenceEn:'Have refined tastes.',
   onSentence:'雅楽（ががく）を鑑賞する。',
   onSentenceKana:'ががくをかんしょうする。',
   onSentenceEn:'Appreciate gagaku (ancient court music).'},

  {c:'華',on:'カ',kun:'はな',mean:'splendor, flower',
   kunSentence:'華（はな）が咲く。',
   kunSentenceKana:'はながさく。',
   kunSentenceEn:'Flowers bloom.',
   onSentence:'華やか（はなやか）な式典。',
   onSentenceKana:'はなやかなしきてん。',
   onSentenceEn:'A splendid ceremony.'},

  // Nature & environment
  {c:'潤',on:'ジュン',kun:'うるお(う)',mean:'moist, benefit',
   kunSentence:'雨が大地を潤す。',
   kunSentenceKana:'あめがだいちをうるおす。',
   kunSentenceEn:'Rain moistens the earth.',
   onSentence:'潤沢（じゅんたく）な資金。',
   onSentenceKana:'じゅんたくなしきん。',
   onSentenceEn:'Abundant funds.'},

  {c:'澄',on:'チョウ',kun:'す(む)',mean:'clear, lucid',
   kunSentence:'水が澄んでいる。',
   kunSentenceKana:'みずがすんでいる。',
   kunSentenceEn:'The water is clear.',
   onSentence:'清澄（せいちょう）な心。',
   onSentenceKana:'せいちょうなこころ。',
   onSentenceEn:'A clear heart.'},

  {c:'麗',on:'レイ',kun:'うるわ(しい)',mean:'beautiful, graceful',
   kunSentence:'麗しい景色だ。',
   kunSentenceKana:'うるわしいけしきだ。',
   kunSentenceEn:'What a beautiful scene.',
   onSentence:'麗人（れいじん）と呼ばれる。',
   onSentenceKana:'れいじんとよばれる。',
   onSentenceEn:'Called a beauty.'},

  // Psychology & emotion
  {c:'慮',on:'リョ',kun:'おもんばか(る)',mean:'consider, concern',
   kunSentence:'将来を慮る。',
   kunSentenceKana:'しょうらいをおもんばかる。',
   kunSentenceEn:'Consider the future.',
   onSentence:'配慮（はいりょ）に感謝する。',
   onSentenceKana:'はいりょにかんしゃする。',
   onSentenceEn:'Appreciate the consideration.'},

  {c:'憂',on:'ユウ',kun:'うれ(える)',mean:'melancholy, worry',
   kunSentence:'彼の健康を憂える。',
   kunSentenceKana:'かれのけんこうをうれえる。',
   kunSentenceEn:'Worry about his health.',
   onSentence:'憂慮（ゆうりょ）すべき問題。',
   onSentenceKana:'ゆうりょすべきもんだい。',
   onSentenceEn:'A matter of concern.'},

  // Business & economics
  {c:'膨',on:'ボウ',kun:'ふく(らむ)',mean:'swell, expand',
   kunSentence:'風船が膨らむ。',
   kunSentenceKana:'ふうせんがふくらむ。',
   kunSentenceEn:'The balloon expands.',
   onSentence:'膨張（ぼうちょう）する経済。',
   onSentenceKana:'ぼうちょうするけいざい。',
   onSentenceEn:'The expanding economy.'},

  {c:'縮',on:'シュク',kun:'ちぢ(む)',mean:'shrink, contract',
   kunSentence:'セーターが縮んだ。',
   kunSentenceKana:'せーたーがちぢんだ。',
   kunSentenceEn:'The sweater shrank.',
   onSentence:'縮小（しゅくしょう）する市場。',
   onSentenceKana:'しゅくしょうするいちば。',
   onSentenceEn:'A shrinking market.'},

  // Time & change
  {c:'経',on:'ケイ',kun:'へ(る)',mean:'pass, experience, manage',
   kunSentence:'月日が経つ。',
   kunSentenceKana:'つきひがたつ。',
   kunSentenceEn:'Time passes.',
   onSentence:'経験（けいけん）を活かす。',
   onSentenceKana:'けいけんをいかす。',
   onSentenceEn:'Make use of experience.'},

  {c:'歴',on:'レキ',kun:'—',mean:'history, curriculum',
   onSentence:'歴史（れきし）を学ぶ。',
   onSentenceKana:'れきしをまなぶ。',
   onSentenceEn:'Study history.'},

  // Movement & action
  {c:'奔',on:'ホン',kun:'—',mean:'rush, run wild',
   onSentence:'奔走（ほんそう）する。',
   onSentenceKana:'ほんそうする。',
   onSentenceEn:'Run about, strive.'},

  {c:'駆',on:'ク',kun:'か(ける)',mean:'drive, run',
   kunSentence:'馬を駆る。',
   kunSentenceKana:'うまをかる。',
   kunSentenceEn:'Drive a horse.',
   onSentence:'駆除（くじょ）する。',
   onSentenceKana:'くじょする。',
   onSentenceEn:'Exterminate, eliminate.'},

  // Language & communication
  {c:'誇',on:'コ',kun:'ほこ(る)',mean:'pride, boast',
   kunSentence:'彼は実力を誇る。',
   kunSentenceKana:'かれはじつりょくをほこる。',
   kunSentenceEn:'He boasts his ability.',
   onSentence:'誇張（こちょう）は控える。',
   onSentenceKana:'こちょうはひかえる。',
   onSentenceEn:'Avoid exaggeration.'},

  {c:'謳',on:'オウ',kun:'うた(う)',mean:'proclaim, sing',
   kunSentence:'自由を謳う。',
   kunSentenceKana:'じゆうをうたう。',
   kunSentenceEn:'Proclaim freedom.',
   onSentence:'謳歌（おうか）する人生。',
   onSentenceKana:'おうかするじんせい。',
   onSentenceEn:'A life of enjoyment.'},

  // Nature & energy
  {c:'輝',on:'キ',kun:'かがや(く)',mean:'shine, brilliant',
   kunSentence:'星が輝いている。',
   kunSentenceKana:'ほしがかがやいている。',
   kunSentenceEn:'The stars are shining.',
   onSentence:'輝石（きせき）を発見する。',
   onSentenceKana:'きせきをはっけんする。',
   onSentenceEn:'Discover a brilliant stone.'},

  {c:'瞬',on:'シュン',kun:'またた(く)',mean:'blink, moment',
   kunSentence:'まばたきをした。',
   kunSentenceKana:'まばたきをした。',
   kunSentenceEn:'I blinked.',
   onSentence:'瞬間（しゅんかん）を逃さない。',
   onSentenceKana:'しゅんかんをのがさない。',
   onSentenceEn:'Don\'t miss the moment.'},

  // Emotions & states
  {c:'憧',on:'ショウ',kun:'あこが(れる)',mean:'yearn, long for',
   kunSentence:'彼は彼女に憧れている。',
   kunSentenceKana:'かれはかのじょにあこがれている。',
   kunSentenceEn:'He admires her.',
   onSentence:'憧れ（あこがれ）の存在。',
   onSentenceKana:'あこがれのそんざい。',
   onSentenceEn:'An admired existence.'},

  {c:'慕',on:'ボ',kun:'した(う)',mean:'yearn for, love',
   kunSentence:'故郷を慕う。',
   kunSentenceKana:'こきょうをしたう。',
   kunSentenceEn:'Long for one\'s hometown.',
   onSentence:'慕情（ぼじょう）を抱く。',
   onSentenceKana:'ぼじょうをいだく。',
   onSentenceEn:'Feel longing.'},

  // Technology & progress
  {c:'著',on:'チョ',kun:'いちじる(しい)',mean:'remarkable, write, publish',
   kunSentence:'著しい進歩だ。',
   kunSentenceKana:'いちじるしいしんぽだ。',
   kunSentenceEn:'Remarkable progress.',
   onSentence:'著作（ちょさく）を発表する。',
   onSentenceKana:'ちょさくをはっぴょうする。',
   onSentenceEn:'Publish a work.'},

  {c:'刊',on:'カン',kun:'—',mean:'publish',
   onSentence:'新聞を刊行（かんこう）する。',
   onSentenceKana:'しんぶんをかんこうする。',
   onSentenceEn:'Publish a newspaper.'},

  // Thought & philosophy
  {c:'哲',on:'テツ',kun:'—',mean:'philosophy, wise',
   onSentence:'哲学（てつがく）を学ぶ。',
   onSentenceKana:'てつがくをまなぶ。',
   onSentenceEn:'Study philosophy.'},

  {c:'理',on:'リ',kun:'ことわり',mean:'reason, logic',
   kunSentence:'理を説く。',
   kunSentenceKana:'りをとく。',
   onSentence:'理解（りかい）を深める。',
   onSentenceKana:'りかいをふかめる。',
   onSentenceEn:'Deepen understanding.'},

  // Life & existence
  {c:'営',on:'エイ',kun:'いとな(む)',mean:'manage, run',
   kunSentence:'ビジネスを営む。',
   kunSentenceKana:'びじねすをいとなむ。',
   kunSentenceEn:'Run a business.',
   onSentence:'営業（えいぎょう）をする。',
   onSentenceKana:'えいぎょうをする。',
   onSentenceEn:'Do sales.'},

  {c:'養',on:'ヨウ',kun:'やしな(う)',mean:'nurture, support',
   kunSentence:'子供を養う。',
   kunSentenceKana:'こどもをやしなう。',
   kunSentenceEn:'Raise children.',
   onSentence:'栄養（えいよう）を摂る。',
   onSentenceKana:'えいようをとる。',
   onSentenceEn:'Take nutrition.'},

  // Movement & change
  {c:'転',on:'テン',kun:'ころ(がる)',mean:'turn, change, roll',
   kunSentence:'石が転がる。',
   kunSentenceKana:'いしがころがる。',
   kunSentenceEn:'The stone rolls.',
   onSentence:'転職（てんしょく）を考える。',
   onSentenceKana:'てんしょくをかんがえる。',
   onSentenceEn:'Consider changing jobs.'},

  {c:'換',on:'カン',kun:'か(える)',mean:'exchange, replace',
   kunSentence:'お金を換える。',
   kunSentenceKana:'おかねをかえる。',
   kunSentenceEn:'Exchange money.',
   onSentence:'換気（かんき）をする。',
   onSentenceKana:'かんきをする。',
   onSentenceEn:'Ventilate.'},

  // Energy & strength
  {c:'闘',on:'トウ',kun:'たたか(う)',mean:'fight, struggle',
   kunSentence:'病気と闘う。',
   kunSentenceKana:'びょうきとたたかう。',
   kunSentenceEn:'Fight against illness.',
   onSentence:'闘志（とうし）を燃やす。',
   onSentenceKana:'とうしをもやす。',
   onSentenceEn:'Burn with fighting spirit.'},

  {c:'努',on:'ド',kun:'つと(める)',mean:'exert, strive',
   kunSentence:'努力する。',
   kunSentenceKana:'どりょくする。',
   kunSentenceEn:'Make an effort.',
   onSentence:'勤務（きんむ）先で評価される。',
   onSentenceKana:'きんむさきでひょうかされる。',
   onSentenceEn:'Be appreciated at work.'},

  // Progress & achievement
  {c:'遂',on:'スイ',kun:'と(げる)',mean:'accomplish, achieve',
   kunSentence:'目標を遂げる。',
   kunSentenceKana:'もくひょうをとげる。',
   kunSentenceEn:'Achieve the goal.',
   onSentence:'遂行（すいこう）する。',
   onSentenceKana:'すいこうする。',
   onSentenceEn:'Carry out.'},

  {c:'達',on:'タツ',kun:'—',mean:'reach, achieve',
   onSentence:'目標を達成（たっせい）する。',
   onSentenceKana:'もくひょうをたっせいする。',
   onSentenceEn:'Achieve the goal.'},

  // Society & structure
  {c:'構',on:'コウ',kun:'かま(える)',mean:'structure, build, posture',
   kunSentence:'構えをとる。',
   kunSentenceKana:'かまえをとる。',
   kunSentenceEn:'Take a stance.',
   onSentence:'構造（こうぞう）を理解する。',
   onSentenceKana:'こうぞうをりかいする。',
   onSentenceEn:'Understand the structure.'},

  {c:'築',on:'チク',kun:'きず(く)',mean:'construct, build',
   kunSentence:'家を築く。',
   kunSentenceKana:'いえをきずく。',
   kunSentenceEn:'Build a house.',
   onSentence:'建築（けんちく）に携わる。',
   onSentenceKana:'けんちくにたずさわる。',
   onSentenceEn:'Be involved in architecture.'},
];

export { N1_KANJI };