// N1_VOCAB — 120 master-level words
var N1_VOCAB = [
  // Philosophy & abstract concepts
  {jp:'哲学',kana:'てつがく',romaji:'tetsugaku',en:'philosophy',cat:'Thought',
   sentence:'哲学を深く考える。',
   sentenceKana:'てつがくをふかくかんがえる。',
   sentenceEn:'Think deeply about philosophy.'},
  {jp:'真理',kana:'しんり',romaji:'shinri',en:'truth',cat:'Thought',
   sentence:'真理を追求する。',
   sentenceKana:'しんりをついきゅうする。',
   sentenceEn:'Pursue the truth.'},
  {jp:'信念',kana:'しんねん',romaji:'shinnen',en:'belief, conviction',cat:'Thought',
   sentence:'自分の信念を貫く。',
   sentenceKana:'じぶんのしんねんをつらぬく。',
   sentenceEn:'Hold firmly to one\'s beliefs.'},
  {jp:'価値観',kana:'かちかん',romaji:'kachikan',en:'values, sense of values',cat:'Thought',
   sentence:'価値観は人それぞれだ。',
   sentenceKana:'かちかんはひとそれぞれだ。',
   sentenceEn:'Values differ from person to person.'},
  {jp:'倫理',kana:'りんり',romaji:'rinri',en:'ethics',cat:'Thought',
   sentence:'倫理的な判断が必要だ。',
   sentenceKana:'りんりてきなはんだんがひつようだ。',
   sentenceEn:'Ethical judgment is necessary.'},

  // Society & politics
  {jp:'民主主義',kana:'みんしゅしゅぎ',romaji:'minshushugi',en:'democracy',cat:'Politics',
   sentence:'民主主義の原則を守る。',
   sentenceKana:'みんしゅしゅぎのげんそくをまもる。',
   sentenceEn:'Protect the principles of democracy.'},
  {jp:'独裁',kana:'どくさい',romaji:'dokusai',en:'dictatorship',cat:'Politics',
   sentence:'独裁政権が倒れた。',
   sentenceKana:'どくさいせいけんがたおれた。',
   sentenceEn:'The dictatorship fell.'},
  {jp:'憲法',kana:'けんぽう',romaji:'kenpou',en:'constitution',cat:'Politics',
   sentence:'憲法改正（かいせい）が議論されている。',
   sentenceKana:'けんぽうかいせいがぎろんされている。',
   sentenceEn:'Constitutional revision is being debated.'},
  {jp:'条約',kana:'じょうやく',romaji:'jouyaku',en:'treaty, pact',cat:'Politics',
   sentence:'国際条約（こくさいじょうやく）に署名する。',
   sentenceKana:'こくさいじょうやくにしょめいする。',
   sentenceEn:'Sign an international treaty.'},
  {jp:'議会',kana:'ぎかい',romaji:'gikai',en:'parliament, congress',cat:'Politics',
   sentence:'議会が開かれる。',
   sentenceKana:'ぎかいがひらかれる。',
   sentenceEn:'Parliament is convened.'},

  // Economy & business
  {jp:'景気',kana:'けいき',romaji:'keiki',en:'economy, business conditions',cat:'Economy',
   sentence:'景気が回復している。',
   sentenceKana:'けいきがかいふくしている。',
   sentenceEn:'The economy is recovering.'},
  {jp:'不況',kana:'ふきょう',romaji:'fukyou',en:'recession, depression',cat:'Economy',
   sentence:'世界不況（せかいふきょう）が続く。',
   sentenceKana:'せかいふきょうがつづく。',
   sentenceEn:'The global recession continues.'},
  {jp:'株価',kana:'かぶか',romaji:'kabuka',en:'stock price',cat:'Economy',
   sentence:'株価が急落した。',
   sentenceKana:'かぶかがきゅうらくした。',
   sentenceEn:'Stock prices plummeted.'},
  {jp:'為替',kana:'かわせ',romaji:'kawase',en:'foreign exchange, rate',cat:'Economy',
   sentence:'為替リスクをヘッジする。',
   sentenceKana:'かわせりすくをへっじする。',
   sentenceEn:'Hedge foreign exchange risk.'},
  {jp:'消費',kana:'しょうひ',romaji:'shouhi',en:'consumption',cat:'Economy',
   sentence:'消費税（しょうひぜい）が上がる。',
   sentenceKana:'しょうひぜいがあがる。',
   sentenceEn:'Consumption tax rises.'},

  // Law & justice
  {jp:'司法',kana:'しほう',romaji:'shihou',en:'judiciary, justice',cat:'Law',
   sentence:'司法の独立が重要だ。',
   sentenceKana:'しほうのどくりつがじゅうようだ。',
   sentenceEn:'Judicial independence is important.'},
  {jp:'裁判所',kana:'さいばんしょ',romaji:'saibansho',en:'court of law',cat:'Law',
   sentence:'裁判所に出頭する。',
   sentenceKana:'さいばんしょにしゅっとうする。',
   sentenceEn:'Appear in court.'},
  {jp:'弁護士',kana:'べんごし',romaji:'bengoshi',en:'lawyer',cat:'Law',
   sentence:'弁護士を雇う。',
   sentenceKana:'べんごしをやとう。',
   sentenceEn:'Hire a lawyer.'},
  {jp:'証拠',kana:'しょうこ',romaji:'shouko',en:'evidence, proof',cat:'Law',
   sentence:'証拠を提出する。',
   sentenceKana:'しょうこをていしゅつする。',
   sentenceEn:'Submit evidence.'},
  {jp:'訴訟',kana:'そしょう',romaji:'soshou',en:'lawsuit',cat:'Law',
   sentence:'訴訟を起こす。',
   sentenceKana:'そしょうをおこす。',
   sentenceEn:'File a lawsuit.'},

  // Science & technology
  {jp:'進歩',kana:'しんぽ',romaji:'shinpo',en:'progress, advance',cat:'Tech',
   sentence:'科学技術が進歩する。',
   sentenceKana:'かがくぎじゅつがしんぽする。',
   sentenceEn:'Science and technology advance.'},
  {jp:'革新',kana:'かくしん',romaji:'kakushin',en:'innovation, reform',cat:'Tech',
   sentence:'技術革新（ぎじゅつかくしん）が起こる。',
   sentenceKana:'ぎじゅつかくしんがおこる。',
   sentenceEn:'Technological innovation occurs.'},
  {jp:'分析',kana:'ぶんせき',romaji:'bunseki',en:'analysis',cat:'Tech',
   sentence:'データを分析する。',
   sentenceKana:'でーたをぶんせきする。',
   sentenceEn:'Analyze data.'},
  {jp:'シミュレーション',kana:'しみゅれーしょん',romaji:'shimyureeshon',en:'simulation',cat:'Tech',
   sentence:'シミュレーションを実行する。',
   sentenceKana:'しみゅれーしょんをじっこうする。',
   sentenceEn:'Run a simulation.'},
  {jp:'自律',kana:'じりつ',romaji:'jiritsu',en:'autonomy, self-regulation',cat:'Tech',
   sentence:'自律型ロボットが開発された。',
   sentenceKana:'じりつがたろぼっとがかいはつされた。',
   sentenceEn:'An autonomous robot was developed.'},

  // Environment & nature
  {jp:'持続可能',kana:'じぞくかのう',romaji:'jizokukanou',en:'sustainable',cat:'Environment',
   sentence:'持続可能な開発を目指す。',
   sentenceKana:'じぞくかのうなかいはつをめざす。',
   sentenceEn:'Aim for sustainable development.'},
  {jp:'生態系',kana:'せいたいけい',romaji:'seitaikei',en:'ecosystem',cat:'Environment',
   sentence:'生態系の保全に努める。',
   sentenceKana:'せいたいけいのほぜんにつとめる。',
   sentenceEn:'Strive to preserve the ecosystem.'},
  {jp:'化石燃料',kana:'かせきねんりょう',romaji:'kasekinenryou',en:'fossil fuel',cat:'Environment',
   sentence:'化石燃料からの脱却が求められる。',
   sentenceKana:'かせきねんりょうからのだっきゃくがもとめられる。',
   sentenceEn:'A shift away from fossil fuels is required.'},
  {jp:'排出',kana:'はいしゅつ',romaji:'haishutsu',en:'emission, discharge',cat:'Environment',
   sentence:'CO2排出量を削減する。',
   sentenceKana:'しーおーつーはいしゅつりょうをさくげんする。',
   sentenceEn:'Reduce CO2 emissions.'},

  // Psychology & human nature
  {jp:'無意識',kana:'むいしき',romaji:'muishiki',en:'unconscious',cat:'Psychology',
   sentence:'無意識に行動してしまう。',
   sentenceKana:'むいしきにこうどうしてしまう。',
   sentenceEn:'I act unconsciously.'},
  {jp:'トラウマ',kana:'とらうま',romaji:'torauma',en:'trauma',cat:'Psychology',
   sentence:'トラウマを克服する。',
   sentenceKana:'とらうまをこくふくする。',
   sentenceEn:'Overcome trauma.'},
  {jp:'ストレス',kana:'すとれす',romaji:'sutoresu',en:'stress',cat:'Psychology',
   sentence:'ストレスを管理する。',
   sentenceKana:'すとれすをかんりする。',
   sentenceEn:'Manage stress.'},
  {jp:'認知',kana:'にんち',romaji:'ninchi',en:'cognition, recognition',cat:'Psychology',
   sentence:'認知能力（にんちのうりょく）を高める。',
   sentenceKana:'にんちのうりょくをたかめる。',
   sentenceEn:'Improve cognitive ability.'},
  {jp:'偏見',kana:'へんけん',romaji:'henken',en:'prejudice, bias',cat:'Psychology',
   sentence:'偏見をなくす努力をする。',
   sentenceKana:'へんけんをなくすどりょくをする。',
   sentenceEn:'Make efforts to eliminate prejudice.'},

  // Education & academia
  {jp:'高等教育',kana:'こうとうきょういく',romaji:'koutou kyouiku',en:'higher education',cat:'Education',
   sentence:'高等教育を受けている。',
   sentenceKana:'こうとうきょういくをうけている。',
   sentenceEn:'Receiving higher education.'},
  {jp:'研究',kana:'けんきゅう',romaji:'kenkyuu',en:'research',cat:'Education',
   sentence:'研究に没頭する。',
   sentenceKana:'けんきゅうにぼっとうする。',
   sentenceEn:'Immerse oneself in research.'},
  {jp:'論文',kana:'ろんぶん',romaji:'ronbun',en:'thesis, paper',cat:'Education',
   sentence:'論文を発表する。',
   sentenceKana:'ろんぶんをはっぴょうする。',
   sentenceEn:'Present a paper.'},
  {jp:'知性',kana:'ちせい',romaji:'chisei',en:'intelligence, intellect',cat:'Education',
   sentence:'知性を磨く。',
   sentenceKana:'ちせいをみがく。',
   sentenceEn:'Sharpen one\'s intellect.'},

  // Culture & arts
  {jp:'芸術',kana:'げいじゅつ',romaji:'geijutsu',en:'art',cat:'Culture',
   sentence:'芸術を鑑賞する。',
   sentenceKana:'げいじゅつをかんしょうする。',
   sentenceEn:'Appreciate art.'},
  {jp:'伝統',kana:'でんとう',romaji:'dentou',en:'tradition',cat:'Culture',
   sentence:'伝統を継承する。',
   sentenceKana:'でんとうをけいしょうする。',
   sentenceEn:'Inherit traditions.'},
  {jp:'先端',kana:'せんたん',romaji:'sentan',en:'cutting edge',cat:'Culture',
   sentence:'先端技術を導入する。',
   sentenceKana:'せんたんぎじゅつをどうにゅうする。',
   sentenceEn:'Introduce cutting-edge technology.'},
  {jp:'遺産',kana:'いさん',romaji:'isan',en:'heritage',cat:'Culture',
   sentence:'世界遺産（せかいいさん）を訪れる。',
   sentenceKana:'せかいいさんをおとずれる。',
   sentenceEn:'Visit a World Heritage site.'},

  // Work & management
  {jp:'戦略',kana:'せんりゃく',romaji:'senryaku',en:'strategy',cat:'Business',
   sentence:'戦略を練る。',
   sentenceKana:'せんりゃくをねる。',
   sentenceEn:'Formulate a strategy.'},
  {jp:'改革',kana:'かいかく',romaji:'kaikaku',en:'reform, innovation',cat:'Business',
   sentence:'組織改革を断行する。',
   sentenceKana:'そしきかいかくをだんこうする。',
   sentenceEn:'Implement organizational reform.'},
  {jp:'業績',kana:'ぎょうせき',romaji:'gyouseki',en:'performance, results',cat:'Business',
   sentence:'業績が向上している。',
   sentenceKana:'ぎょうせきがこうじょうしている。',
   sentenceEn:'Performance is improving.'},
  {jp:'部門',kana:'ぶもん',romaji:'bumon',en:'department, division',cat:'Business',
   sentence:'営業部門（えいぎょうぶもん）に配属される。',
   sentenceKana:'えいぎょうぶもんにはいぞくされる。',
   sentenceEn:'Assigned to the sales department.'},

  // Health & medicine
  {jp:'慢性',kana:'まんせい',romaji:'mansei',en:'chronic',cat:'Health',
   sentence:'慢性疾患を抱える。',
   sentenceKana:'まんせいしっかんをかかえる。',
   sentenceEn:'Suffer from chronic disease.'},
  {jp:'治療',kana:'ちりょう',romaji:'chiryou',en:'treatment',cat:'Health',
   sentence:'治療を受ける。',
   sentenceKana:'ちりょうをうける。',
   sentenceEn:'Receive treatment.'},
  {jp:'予防',kana:'よぼう',romaji:'yobou',en:'prevention',cat:'Health',
   sentence:'予防策を講じる。',
   sentenceKana:'よぼうさくをこうじる。',
   sentenceEn:'Take preventive measures.'},
  {jp:'免疫',kana:'めんえき',romaji:'men eki',en:'immunity',cat:'Health',
   sentence:'免疫力を高める。',
   sentenceKana:'めんえきりょくをたかめる。',
   sentenceEn:'Boost immunity.'},

  // Language & communication
  {jp:'推論',kana:'すいろん',romaji:'suiron',en:'inference, reasoning',cat:'Communication',
   sentence:'推論を組み立てる。',
   sentenceKana:'すいろんをくみたてる。',
   sentenceEn:'Construct a reasoning.'},
  {jp:'根拠',kana:'こんきょ',romaji:'konkyo',en:'basis, grounds',cat:'Communication',
   sentence:'根拠を示す。',
   sentenceKana:'こんきょをしめす。',
   sentenceEn:'Show the basis.'},
  {jp:'議論',kana:'ぎろん',romaji:'giron',en:'discussion, argument',cat:'Communication',
   sentence:'活発な議論が交わされる。',
   sentenceKana:'かっぱつなぎろんがかわされる。',
   sentenceEn:'An active discussion is held.'},
  {jp:'主張',kana:'しゅちょう',romaji:'shuchou',en:'assertion, claim',cat:'Communication',
   sentence:'自分の主張を貫く。',
   sentenceKana:'じぶんのしゅちょうをつらぬく。',
   sentenceEn:'Maintain one\'s claim.'},

  // Time & change
  {jp:'恒久',kana:'こうきゅう',romaji:'koukyuu',en:'permanent, perpetual',cat:'Time',
   sentence:'恒久平和を願う。',
   sentenceKana:'こうきゅうへいわをねがう。',
   sentenceEn:'Hope for permanent peace.'},
  {jp:'一時的',kana:'いちじてき',romaji:'ichijiteki',en:'temporary',cat:'Time',
   sentence:'一時的な措置を取る。',
   sentenceKana:'いちじてきなそちをとる。',
   sentenceEn:'Take temporary measures.'},
  {jp:'優先',kana:'ゆうせん',romaji:'yuusen',en:'priority',cat:'Time',
   sentence:'優先順位を決める。',
   sentenceKana:'ゆうせんじゅんいをきめる。',
   sentenceEn:'Set priorities.'},
];

export { N1_VOCAB };