// N2_KANJI — advanced kanji (35 entries)
var N2_KANJI = [
  // Society & politics
  {c:'憲',on:'ケン',kun:'—',mean:'constitution, rule',
   onSentence:'憲法（けんぽう）を守る。',
   onSentenceKana:'けんぽうをまもる。',
   onSentenceEn:'Protect the constitution.'},
  {c:'政',on:'セイ',kun:'まつりごと',mean:'government, politics',
   kunSentence:'政（まつりごと）を行う。',
   kunSentenceKana:'まつりごとをおこなう。',
   kunSentenceEn:'Conduct government affairs.',
   onSentence:'政治（せいじ）に参加する。',
   onSentenceKana:'せいじにさんかする。',
   onSentenceEn:'Participate in politics.'},
  {c:'党',on:'トウ',kun:'—',mean:'party, faction',
   onSentence:'政党（せいとう）に所属する。',
   onSentenceKana:'せいとうにしょぞくする。',
   onSentenceEn:'Belong to a political party.'},
  {c:'員',on:'イン',kun:'—',mean:'member, employee',
   onSentence:'委員（いいん）に選ばれる。',
   onSentenceKana:'いいんにえらばれる。',
   onSentenceEn:'Be elected as a committee member.'},

  // Economy & business
  {c:'貿',on:'ボウ',kun:'—',mean:'trade, exchange',
   onSentence:'貿易（ぼうえき）に従事する。',
   onSentenceKana:'ぼうえきにじゅうじする。',
   onSentenceEn:'Engage in trade.'},
  {c:'易',on:'エキ',kun:'やさ(しい)',mean:'exchange, easy',
   kunSentence:'この問題は易しい。',
   kunSentenceKana:'このもんだいはやさしい。',
   kunSentenceEn:'This problem is easy.',
   onSentence:'貿易（ぼうえき）は難しい。',
   onSentenceKana:'ぼうえきはむずかしい。',
   onSentenceEn:'Trade is difficult.'},
  {c:'産',on:'サン',kun:'う(む)',mean:'give birth, produce',
   kunSentence:'子を産む。',
   kunSentenceKana:'こをうむ。',
   kunSentenceEn:'Give birth to a child.',
   onSentence:'産業（さんぎょう）が発展する。',
   onSentenceKana:'さんぎょうがはってんする。',
   onSentenceEn:'Industry develops.'},
  {c:'業',on:'ギョウ',kun:'わざ',mean:'business, profession',
   kunSentence:'業（わざ）がいい。',
   kunSentenceKana:'わざがいい。',
   kunSentenceEn:'Skilled.',
   onSentence:'卒業（そつぎょう）する。',
   onSentenceKana:'そつぎょうする。',
   onSentenceEn:'Graduate.'},

  // Law & justice
  {c:'法',on:'ホウ・ハッ',kun:'のり',mean:'law, rule',
   kunSentence:'法（のり）を守る。',
   kunSentenceKana:'のりをまもる。',
   kunSentenceEn:'Follow the rules.',
   onSentence:'法律（ほうりつ）を勉強する。',
   onSentenceKana:'ほうりつをべんきょうする。',
   onSentenceEn:'Study law.'},
  {c:'裁',on:'サイ',kun:'さば(く)',mean:'judge, decide',
   kunSentence:'事件を裁く。',
   kunSentenceKana:'じけんをさばく。',
   kunSentenceEn:'Judge a case.',
   onSentence:'裁判（さいばん）を受ける。',
   onSentenceKana:'さいばんをうける。',
   onSentenceEn:'Stand trial.'},

  // Science & technology
  {c:'技',on:'ギ',kun:'わざ',mean:'skill, art',
   kunSentence:'技（わざ）を磨く。',
   kunSentenceKana:'わざをみがく。',
   kunSentenceEn:'Polish one\'s skill.',
   onSentence:'技術（ぎじゅつ）が進歩する。',
   onSentenceKana:'ぎじゅつがしんぽする。',
   onSentenceEn:'Technology advances.'},
  {c:'術',on:'ジュツ',kun:'—',mean:'technique, art',
   onSentence:'手術（しゅじゅつ）を受ける。',
   onSentenceKana:'しゅじゅつをうける。',
   onSentenceEn:'Undergo surgery.'},
  {c:'能',on:'ノウ',kun:'—',mean:'ability, capacity',
   onSentence:'能力（のうりょく）を向上させる。',
   onSentenceKana:'のうりょくをこうじょうさせる。',
   onSentenceEn:'Improve abilities.'},
  {c:'機',on:'キ',kun:'はた',mean:'machine, opportunity',
   kunSentence:'機（はた）を織る。',
   kunSentenceKana:'はたをおる。',
   kunSentenceEn:'Weave cloth.',
   onSentence:'機械（きかい）を操作する。',
   onSentenceKana:'きかいをそうさする。',
   onSentenceEn:'Operate machinery.'},

  // Culture & art
  {c:'芸',on:'ゲイ',kun:'—',mean:'art, performance',
   onSentence:'芸術（げいじゅつ）を鑑賞する。',
   onSentenceKana:'げいじゅつをかんしょうする。',
   onSentenceEn:'Appreciate art.'},
  {c:'術',on:'ジュツ',kun:'—',mean:'technique, art',
   onSentence:'技術（ぎじゅつ）を習得する。',
   onSentenceKana:'ぎじゅつをしゅうとくする。',
   onSentenceEn:'Acquire techniques.'},

  // Environment & nature
  {c:'環',on:'カン',kun:'—',mean:'ring, environment',
   onSentence:'環境（かんきょう）を守る。',
   onSentenceKana:'かんきょうをまもる。',
   onSentenceEn:'Protect the environment.'},
  {c:'境',on:'キョウ・ケイ',kun:'さかい',mean:'boundary, condition',
   kunSentence:'国境（こっきょう）を越える。',
   kunSentenceKana:'こっきょうをこえる。',
   kunSentenceEn:'Cross the border.',
   onSentence:'境界（きょうかい）を定める。',
   onSentenceKana:'きょうかいをさだめる。',
   onSentenceEn:'Set boundaries.'},
  {c:'資源',on:'シゲン',kun:'—',mean:'resources',
   onSentence:'資源を節約する。',
   onSentenceKana:'しげんをせつやくする。',
   onSentenceEn:'Save resources.'},

  // Health & medicine
  {c:'療',on:'リョウ',kun:'—',mean:'heal, treat',
   onSentence:'治療（ちりょう）を受ける。',
   onSentenceKana:'ちりょうをうける。',
   onSentenceEn:'Receive treatment.'},
  {c:'薬',on:'ヤク',kun:'くすり',mean:'medicine, drug',
   kunSentence:'この薬を飲む。',
   kunSentenceKana:'このくすりをのむ。',
   kunSentenceEn:'Take this medicine.',
   onSentence:'薬局（やっきょく）で買う。',
   onSentenceKana:'やっきょくでかう。',
   onSentenceEn:'Buy at the pharmacy.'},

  // Education & learning
  {c:'育',on:'イク',kun:'そだ(つ)',mean:'raise, develop',
   kunSentence:'子供を育てる。',
   kunSentenceKana:'こどもをそだてる。',
   kunSentenceEn:'Raise children.',
   onSentence:'教育（きょういく）に力を入れる。',
   onSentenceKana:'きょういくにちからをいれる。',
   onSentenceEn:'Put effort into education.'},
  {c:'養',on:'ヨウ',kun:'やしな(う)',mean:'nurture, support',
   kunSentence:'家族を養う。',
   kunSentenceKana:'かぞくをやしなう。',
   kunSentenceEn:'Support the family.',
   onSentence:'養成（ようせい）コースに参加する。',
   onSentenceKana:'ようせいこーすにさんかする。',
   onSentenceEn:'Participate in a training course.'},

  // Work & management
  {c:'管',on:'カン',kun:'くだ',mean:'pipe, management',
   kunSentence:'管（くだ）を通す。',
   kunSentenceKana:'くだをとおす。',
   kunSentenceEn:'Pass through a pipe.',
   onSentence:'管理（かんり）する。',
   onSentenceKana:'かんりする。',
   onSentenceEn:'Manage.'},
  {c:'理',on:'リ',kun:'ことわり',mean:'reason, logic',
   kunSentence:'理（ことわり）を説く。',
   kunSentenceKana:'ことわりをとく。',
   kunSentenceEn:'Explain the logic.',
   onSentence:'理解（りかい）する。',
   onSentenceKana:'りかいする。',
   onSentenceEn:'Understand.'},

  // Communication
  {c:'伝',on:'デン',kun:'つた(わる)',mean:'transmit, tell',
   kunSentence:'伝統（でんとう）を伝える。',
   kunSentenceKana:'でんとうをつたえる。',
   kunSentenceEn:'Pass on traditions.',
   onSentence:'伝言（でんごん）を残す。',
   onSentenceKana:'でんごんをのこす。',
   onSentenceEn:'Leave a message.'},
  {c:'絡',on:'ラク',kun:'から(む)',mean:'entangle, involve',
   kunSentence:'問題が絡む。',
   kunSentenceKana:'もんだいがからむ。',
   kunSentenceEn:'Problems are involved.',
   onSentence:'連絡（れんらく）する。',
   onSentenceKana:'れんらくする。',
   onSentenceEn:'Contact.'},

  // Society & community
  {c:'市',on:'シ',kun:'いち',mean:'city, market',
   kunSentence:'市場（いちば）に行く。',
   kunSentenceKana:'いちばにいく。',
   kunSentenceEn:'Go to the market.',
   onSentence:'市役所（しやくしょ）に用事がある。',
   onSentenceKana:'しやくしょにようじがある。',
   onSentenceEn:'Have business at city hall.'},
  {c:'村',on:'ソン',kun:'むら',mean:'village',
   kunSentence:'村（むら）に住む。',
   kunSentenceKana:'むらにすむ。',
   kunSentenceEn:'Live in a village.',
   onSentence:'村民（そんみん）の意見を聞く。',
   onSentenceKana:'そんみんのいけんをきく。',
   onSentenceEn:'Listen to villagers\' opinions.'},
  {c:'都',on:'ト',kun:'みやこ',mean:'metropolis, capital',
   kunSentence:'都（みやこ）へ行く。',
   kunSentenceKana:'みやこへいく。',
   kunSentenceEn:'Go to the capital.',
   onSentence:'都合（つごう）が悪い。',
   onSentenceKana:'つごうがわるい。',
   onSentenceEn:'Inconvenient.'},

  // Miscellaneous advanced
  {c:'確',on:'カク',kun:'たし(か)',mean:'certain, sure',
   kunSentence:'確かめる。',
   kunSentenceKana:'たしかめる。',
   kunSentenceEn:'Check, confirm.',
   onSentence:'確率（かくりつ）を計算する。',
   onSentenceKana:'かくりつをけいさんする。',
   onSentenceEn:'Calculate probability.'},
  {c:'認',on:'ニン',kun:'みと(める)',mean:'recognize, admit',
   kunSentence:'事実を認める。',
   kunSentenceKana:'じじつをみとめる。',
   kunSentenceEn:'Admit the fact.',
   onSentence:'認識（にんしき）が変わる。',
   onSentenceKana:'にんしきがかわる。',
   onSentenceEn:'Change one\'s perception.'},
  {c:'質',on:'シツ',kun:'たち',mean:'quality, nature',
   kunSentence:'質（たち）がいい。',
   kunSentenceKana:'たちがいい。',
   kunSentenceEn:'Good quality.',
   onSentence:'質問（しつもん）する。',
   onSentenceKana:'しつもんする。',
   onSentenceEn:'Ask a question.'},
  {c:'量',on:'リョウ',kun:'はか(る)',mean:'quantity, amount',
   kunSentence:'量（はか）る。',
   kunSentenceKana:'はかる。',
   kunSentenceEn:'Measure.',
   onSentence:'大量（たいりょう）のデータを処理する。',
   onSentenceKana:'たいりょうのでーたをしょりする。',
   onSentenceEn:'Process large amounts of data.'},
  {c:'対',on:'タイ',kun:'あいて',mean:'opposite, match',
   kunSentence:'相手（あいて）を選ぶ。',
   kunSentenceKana:'あいてをえらぶ。',
   kunSentenceEn:'Choose an opponent.',
   onSentence:'対応（たいおう）する。',
   onSentenceKana:'たいおうする。',
   onSentenceEn:'Respond, cope.'},
  {c:'比',on:'ヒ',kun:'くら(べる)',mean:'compare, ratio',
   kunSentence:'比べる。',
   kunSentenceKana:'くらべる。',
   kunSentenceEn:'Compare.',
   onSentence:'比較（ひかく）する。',
   onSentenceKana:'ひかくする。',
   onSentenceEn:'Compare.'},
  {c:'絶',on:'ゼツ',kun:'た(える)',mean:'end, absolute',
   kunSentence:'絶える。',
   kunSentenceKana:'たえる。',
   kunSentenceEn:'Die out, cease.',
   onSentence:'絶対（ぜったい）に成功する。',
   onSentenceKana:'ぜったいにせいこうする。',
   onSentenceEn:'Will definitely succeed.'},
  {c:'続',on:'ゾク',kun:'つづ(く)',mean:'continue, sequence',
   kunSentence:'続ける。',
   kunSentenceKana:'つづける。',
   kunSentenceEn:'Continue.',
   onSentence:'続編（ぞくへん）を読む。',
   onSentenceKana:'ぞくへんをよむ。',
   onSentenceEn:'Read the sequel.'},
];

export { N2_KANJI };