// N2_VOCAB — 120 advanced words
var N2_VOCAB = [
  // Society & politics
  {jp:'民主主義',kana:'みんしゅしゅぎ',romaji:'minshushugi',en:'democracy',cat:'Politics',
   sentence:'民主主義は重要な価値観です。',
   sentenceKana:'みんしゅしゅぎはじゅうようなかちかんです。',
   sentenceEn:'Democracy is an important value.'},
  {jp:'選挙',kana:'せんきょ',romaji:'senkyo',en:'election',cat:'Politics',
   sentence:'選挙に行きましょう。',
   sentenceKana:'せんきょにいきましょう。',
   sentenceEn:'Let\'s go to vote.'},
  {jp:'政策',kana:'せいさく',romaji:'seisaku',en:'policy',cat:'Politics',
   sentence:'新しい政策が発表された。',
   sentenceKana:'あたらしいせいさくがはっぴょうされた。',
   sentenceEn:'A new policy was announced.'},
  {jp:'権利',kana:'けんり',romaji:'kenri',en:'rights',cat:'Politics',
   sentence:'人権（じんけん）を守る。',
   sentenceKana:'じんけんをまもる。',
   sentenceEn:'Protect human rights.'},
  {jp:'義務',kana:'ぎむ',romaji:'gimu',en:'duty, obligation',cat:'Politics',
   sentence:'国民（こくみん）の義務を果たす。',
   sentenceKana:'こくみんのぎむをはたす。',
   sentenceEn:'Fulfill the duties of a citizen.'},

  // Economy
  {jp:'インフレ',kana:'いんふれ',romaji:'infure',en:'inflation',cat:'Economy',
   sentence:'インフレが進んでいる。',
   sentenceKana:'いんふれがすすんでいる。',
   sentenceEn:'Inflation is progressing.'},
  {jp:'デフレ',kana:'でふれ',romaji:'defure',en:'deflation',cat:'Economy',
   sentence:'デフレは経済に悪影響を与える。',
   sentenceKana:'でふれはけいざいにあくえいきょうをあたえる。',
   sentenceEn:'Deflation negatively affects the economy.'},
  {jp:'株',kana:'かぶ',romaji:'kabu',en:'stock, share',cat:'Economy',
   sentence:'株を買う。',
   sentenceKana:'かぶをかう。',
   sentenceEn:'Buy stocks.'},
  {jp:'為替',kana:'かわせ',romaji:'kawase',en:'foreign exchange, rate',cat:'Economy',
   sentence:'為替レートを確認する。',
   sentenceKana:'かわせれーとをかくにんする。',
   sentenceEn:'Check the exchange rate.'},
  {jp:'貿易',kana:'ぼうえき',romaji:'boueki',en:'trade',cat:'Economy',
   sentence:'日本は貿易大国だ。',
   sentenceKana:'にほんはぼうえきたいこくだ。',
   sentenceEn:'Japan is a major trading nation.'},

  // Work & management
  {jp:'効率',kana:'こうりつ',romaji:'kouritsu',en:'efficiency',cat:'Business',
   sentence:'効率を上げる。',
   sentenceKana:'こうりつをあげる。',
   sentenceEn:'Increase efficiency.'},
  {jp:'成果',kana:'せいか',romaji:'seika',en:'result, achievement',cat:'Business',
   sentence:'成果を出す。',
   sentenceKana:'せいかをだす。',
   sentenceEn:'Produce results.'},
  {jp:'戦略',kana:'せんりゃく',romaji:'senryaku',en:'strategy',cat:'Business',
   sentence:'マーケティング戦略を立てる。',
   sentenceKana:'まーけてぃんぐせんりゃくをたてる。',
   sentenceEn:'Formulate a marketing strategy.'},
  {jp:'提案',kana:'ていあん',romaji:'teian',en:'proposal, suggestion',cat:'Business',
   sentence:'新しい提案をします。',
   sentenceKana:'あたらしいていあんをします。',
   sentenceEn:'I will make a new proposal.'},
  {jp:'改善',kana:'かいぜん',romaji:'kaizen',en:'improvement',cat:'Business',
   sentence:'改善点を見つける。',
   sentenceKana:'かいぜんてんをみつける。',
   sentenceEn:'Find areas for improvement.'},

  // Law & justice
  {jp:'憲法',kana:'けんぽう',romaji:'kenpou',en:'constitution',cat:'Law',
   sentence:'憲法を改正する。',
   sentenceKana:'けんぽうをかいせいする。',
   sentenceEn:'Amend the constitution.'},
  {jp:'裁判',kana:'さいばん',romaji:'saiban',en:'trial, court',cat:'Law',
   sentence:'裁判が行われる。',
   sentenceKana:'さいばんがおこなわれる。',
   sentenceEn:'A trial will be held.'},
  {jp:'弁護士',kana:'べんごし',romaji:'bengoshi',en:'lawyer',cat:'Law',
   sentence:'弁護士に相談する。',
   sentenceKana:'べんごしにそうだんする。',
   sentenceEn:'Consult a lawyer.'},
  {jp:'規制',kana:'きせい',romaji:'kisei',en:'regulation, control',cat:'Law',
   sentence:'規制を緩和する。',
   sentenceKana:'きせいをかんわする。',
   sentenceEn:'Relax regulations.'},
  {jp:'訴訟',kana:'そしょう',romaji:'soshou',en:'lawsuit',cat:'Law',
   sentence:'訴訟を起こす。',
   sentenceKana:'そしょうをおこす。',
   sentenceEn:'File a lawsuit.'},

  // Technology & communication
  {jp:'データベース',kana:'でーたべーす',romaji:'deetabeisu',en:'database',cat:'Tech',
   sentence:'データベースを更新する。',
   sentenceKana:'でーたべーすをこうしんする。',
   sentenceEn:'Update the database.'},
  {jp:'ネットワーク',kana:'ねっとわーく',romaji:'nettowaaku',en:'network',cat:'Tech',
   sentence:'ネットワークを構築する。',
   sentenceKana:'ねっとわーくをこうちくする。',
   sentenceEn:'Build a network.'},
  {jp:'セキュリティ',kana:'せきゅりてぃ',romaji:'sekyuriti',en:'security',cat:'Tech',
   sentence:'セキュリティを強化する。',
   sentenceKana:'せきゅりてぃをきょうかする。',
   sentenceEn:'Strengthen security.'},
  {jp:'ソフトウェア',kana:'そふとうぇあ',romaji:'sofutowea',en:'software',cat:'Tech',
   sentence:'ソフトウェアを開発する。',
   sentenceKana:'そふとうぇあをかいはつする。',
   sentenceEn:'Develop software.'},
  {jp:'アップデート',kana:'あっぷでーと',romaji:'appudeeto',en:'update',cat:'Tech',
   sentence:'アップデートを適用する。',
   sentenceKana:'あっぷでーとをてきようする。',
   sentenceEn:'Apply the update.'},

  // Environment
  {jp:'地球温暖化',kana:'ちきゅうおんだんか',romaji:'chikyuu ondanka',en:'global warming',cat:'Environment',
   sentence:'地球温暖化が深刻だ。',
   sentenceKana:'ちきゅうおんだんかがしんこくだ。',
   sentenceEn:'Global warming is serious.'},
  {jp:'再生可能エネルギー',kana:'さいせいかのうえねるぎー',romaji:'saiseikanou enerugii',en:'renewable energy',cat:'Environment',
   sentence:'再生可能エネルギーを導入する。',
   sentenceKana:'さいせいかのうえねるぎーをどうにゅうする。',
   sentenceEn:'Introduce renewable energy.'},
  {jp:'生態系',kana:'せいたいけい',romaji:'seitaikei',en:'ecosystem',cat:'Environment',
   sentence:'生態系を保護する。',
   sentenceKana:'せいたいけいをほごする。',
   sentenceEn:'Protect the ecosystem.'},
  {jp:'排出',kana:'はいしゅつ',romaji:'haishutsu',en:'emission, discharge',cat:'Environment',
   sentence:'CO2の排出を減らす。',
   sentenceKana:'しーおーつーのはいしゅつをへらす。',
   sentenceEn:'Reduce CO2 emissions.'},

  // Health & medicine
  {jp:'予防',kana:'よぼう',romaji:'yobou',en:'prevention',cat:'Health',
   sentence:'予防策を講じる。',
   sentenceKana:'よぼうさくをこうじる。',
   sentenceEn:'Take preventive measures.'},
  {jp:'症状',kana:'しょうじょう',romaji:'shoujou',en:'symptom',cat:'Health',
   sentence:'症状が出ている。',
   sentenceKana:'しょうじょうがでている。',
   sentenceEn:'Symptoms are appearing.'},
  {jp:'慢性',kana:'まんせい',romaji:'mansei',en:'chronic',cat:'Health',
   sentence:'慢性疾患を抱える。',
   sentenceKana:'まんせいしっかんをかかえる。',
   sentenceEn:'Suffer from chronic disease.'},
  {jp:'健康診断',kana:'けんこうしんだん',romaji:'kenkou shindan',en:'health check-up',cat:'Health',
   sentence:'健康診断を受ける。',
   sentenceKana:'けんこうしんだんをうける。',
   sentenceEn:'Have a health check-up.'},

  // Education & learning
  {jp:'カリキュラム',kana:'かりきゅらむ',romaji:'karikyuramu',en:'curriculum',cat:'Education',
   sentence:'カリキュラムを設計する。',
   sentenceKana:'かりきゅらむをせっけいする。',
   sentenceEn:'Design a curriculum.'},
  {jp:'学位',kana:'がくい',romaji:'gakui',en:'academic degree',cat:'Education',
   sentence:'修士号（しゅうしごう）を取得する。',
   sentenceKana:'しゅうしごうをしゅとくする。',
   sentenceEn:'Obtain a master\'s degree.'},
  {jp:'論文',kana:'ろんぶん',romaji:'ronbun',en:'thesis, paper',cat:'Education',
   sentence:'論文を執筆する。',
   sentenceKana:'ろんぶんをしっぴつする。',
   sentenceEn:'Write a thesis.'},
  {jp:'研究',kana:'けんきゅう',romaji:'kenkyuu',en:'research',cat:'Education',
   sentence:'研究を続ける。',
   sentenceKana:'けんきゅうをつづける。',
   sentenceEn:'Continue research.'},

  // Culture & art
  {jp:'文化財',kana:'ぶんかざい',romaji:'bunkazai',en:'cultural property',cat:'Culture',
   sentence:'文化財を保護する。',
   sentenceKana:'ぶんかざいをほごする。',
   sentenceEn:'Protect cultural properties.'},
  {jp:'伝統芸能',kana:'でんとうげいのう',romaji:'dentou geinou',en:'traditional performing arts',cat:'Culture',
   sentence:'伝統芸能を見学する。',
   sentenceKana:'でんとうげいのうをけんがくする。',
   sentenceEn:'Watch traditional performing arts.'},
  {jp:'文学',kana:'ぶんがく',romaji:'bungaku',en:'literature',cat:'Culture',
   sentence:'日本文学に興味がある。',
   sentenceKana:'にほんぶんがくにきょうみがある。',
   sentenceEn:'I am interested in Japanese literature.'},
  {jp:'哲学',kana:'てつがく',romaji:'tetsugaku',en:'philosophy',cat:'Culture',
   sentence:'哲学を学ぶ。',
   sentenceKana:'てつがくをまなぶ。',
   sentenceEn:'Study philosophy.'},

  // Feelings & personality
  {jp:'誇り',kana:'ほこり',romaji:'hokori',en:'pride',cat:'Personality',
   sentence:'誇りを持つ。',
   sentenceKana:'ほこりをもつ。',
   sentenceEn:'Have pride.'},
  {jp:'謙虚',kana:'けんきょ',romaji:'kenkyo',en:'humility',cat:'Personality',
   sentence:'謙虚な態度が大切だ。',
   sentenceKana:'けんきょなたいどがたいせつだ。',
   sentenceEn:'A humble attitude is important.'},
  {jp:'誠実',kana:'せいじつ',romaji:'seijitsu',en:'sincerity',cat:'Personality',
   sentence:'誠実な人柄（ひとがら）だ。',
   sentenceKana:'せいじつなひとがらだ。',
   sentenceEn:'He is of sincere character.'},
  {jp:'向上心',kana:'こうじょうしん',romaji:'koujoushin',en:'aspiration, drive',cat:'Personality',
   sentence:'向上心を持って働く。',
   sentenceKana:'こうじょうしんをもってはたらく。',
   sentenceEn:'Work with ambition.'},
];

export { N2_VOCAB };