var N4_KANJI = [
  {c:'夕',on:'セキ',kun:'ゆう',mean:'evening',ex:'夕方 (ゆうがた) evening'},
  {c:'工',on:'コウ・ク',kun:'—',mean:'craft, construction',ex:'工場 (こうじょう) factory'},
  {c:'不',on:'フ・ブ',kun:'—',mean:'negative, non-, un-',ex:'不便 (ふべん) inconvenient'},
  {c:'元',on:'ゲン・ガン',kun:'もと',mean:'origin, beginning',ex:'元気 (げんき) healthy, energetic'},
  {c:'公',on:'コウ',kun:'おおやけ',mean:'public, official',ex:'公園 (こうえん) park'},
  {c:'切',on:'セツ・サイ',kun:'き(る)・き(れる)',mean:'cut, be sharp',ex:'親切 (しんせつ) kind'},
  {c:'心',on:'シン',kun:'こころ',mean:'heart, mind, spirit',ex:'心配 (しんぱい) worry'},
  {c:'文',on:'ブン・モン',kun:'ふみ',mean:'sentence, literature',ex:'文化 (ぶんか) culture'},
  {c:'方',on:'ホウ',kun:'かた',mean:'direction, way, person',ex:'方法 (ほうほう) method'},
  {c:'止',on:'シ',kun:'と(まる)・と(める)',mean:'stop, halt',ex:'中止 (ちゅうし) cancellation'},
  {c:'牛',on:'ギュウ',kun:'うし',mean:'cow, ox',ex:'牛肉 (ぎゅうにく) beef'},
  {c:'犬',on:'ケン',kun:'いぬ',mean:'dog',ex:'子犬 (こいぬ) puppy'},
  {c:'世',on:'セイ・セ',kun:'よ',mean:'generation, world, society',ex:'世界 (せかい) world'},
  {c:'主',on:'シュ・ス',kun:'ぬし・おも',mean:'lord, master, main',ex:'主人 (しゅじん) husband, master'},
  {c:'仕',on:'シ・ジ',kun:'つか(える)',mean:'serve, work, do',ex:'仕事 (しごと) work, job'},
  {c:'代',on:'ダイ・タイ',kun:'か(わる)・か(える)・よ・しろ',mean:'substitute, generation, fee',ex:'時代 (じだい) era, period'},
  {c:'以',on:'イ',kun:'—',mean:'by means of, since',ex:'以上 (いじょう) above, more than'},
  {c:'兄',on:'ケイ・キョウ',kun:'あに',mean:'older brother',ex:'兄弟 (きょうだい) siblings'},
  {c:'写',on:'シャ',kun:'うつ(す)・うつ(る)',mean:'copy, photograph',ex:'写真 (しゃしん) photograph'},
  {c:'冬',on:'トウ',kun:'ふゆ',mean:'winter',ex:'冬休み (ふゆやすみ) winter vacation'},
  {c:'去',on:'キョ・コ',kun:'さ(る)',mean:'leave, past, gone',ex:'去年 (きょねん) last year'},
  {c:'台',on:'ダイ・タイ',kun:'—',mean:'stand, pedestal, counter for machines',ex:'台所 (だいどころ) kitchen'},
  {c:'広',on:'コウ',kun:'ひろ(い)・ひろ(がる)',mean:'wide, broad, spacious',ex:'広告 (こうこく) advertisement'},
  {c:'正',on:'セイ・ショウ',kun:'ただ(しい)・まさ',mean:'correct, right, justice',ex:'正月 (しょうがつ) New Year'},
  {c:'用',on:'ヨウ',kun:'もち(いる)',mean:'use, business, errand',ex:'用事 (ようじ) errand, business'},
  {c:'会',on:'カイ・エ',kun:'あ(う)',mean:'meet, society, association',ex:'会社 (かいしゃ) company'},
  {c:'同',on:'ドウ',kun:'おな(じ)',mean:'same, equal, agree',ex:'同じ (おなじ) same'},
  {c:'地',on:'チ・ジ',kun:'—',mean:'ground, earth, place',ex:'地図 (ちず) map'},
  {c:'有',on:'ユウ・ウ',kun:'あ(る)',mean:'exist, have, possess',ex:'有名 (ゆうめい) famous'},
  {c:'死',on:'シ',kun:'し(ぬ)',mean:'death, die',ex:'死亡 (しぼう) death'},
  {c:'考',on:'コウ',kun:'かんが(える)',mean:'consider, think over',ex:'考え方 (かんがえかた) way of thinking'},
  {c:'肉',on:'ニク',kun:'—',mean:'meat, flesh',ex:'肉屋 (にくや) butcher shop'},
  {c:'自',on:'ジ・シ',kun:'みずか(ら)',mean:'oneself, self',ex:'自分 (じぶん) oneself'},
  {c:'色',on:'ショク・シキ',kun:'いろ',mean:'color',ex:'黄色 (きいろ) yellow'},
  {c:'住',on:'ジュウ',kun:'す(む)・す(まう)',mean:'dwell, reside, live',ex:'住所 (じゅうしょ) address'},
  {c:'体',on:'タイ・テイ',kun:'からだ',mean:'body, object, form',ex:'体育 (たいいく) physical education'},
  {c:'作',on:'サク・サ',kun:'つく(る)',mean:'make, produce, build',ex:'作文 (さくぶん) composition, essay'},
  {c:'別',on:'ベツ',kun:'わか(れる)',mean:'separate, another, distinction',ex:'特別 (とくべつ) special'},
  {c:'医',on:'イ',kun:'—',mean:'doctor, medicine',ex:'医者 (いしゃ) doctor'},
  {c:'図',on:'ズ・ト',kun:'はか(る)',mean:'diagram, plan, map',ex:'図書館 (としょかん) library'},
  {c:'売',on:'バイ',kun:'う(る)・う(れる)',mean:'sell',ex:'売店 (ばいてん) kiosk, stand'},
  {c:'弟',on:'テイ・ダイ',kun:'おとうと',mean:'younger brother',ex:'兄弟 (きょうだい) siblings'},
  {c:'町',on:'チョウ',kun:'まち',mean:'town, block',ex:'町長 (ちょうちょう) town mayor'},
  {c:'社',on:'シャ',kun:'やしろ',mean:'company, shrine',ex:'社長 (しゃちょう) company president'},
  {c:'私',on:'シ',kun:'わたし・わたくし',mean:'I, me, private',ex:'私立 (しりつ) private (institution)'},
  {c:'究',on:'キュウ',kun:'きわ(める)',mean:'research, investigate',ex:'研究 (けんきゅう) research'},
  {c:'言',on:'ゲン・ゴン',kun:'い(う)・こと',mean:'say, word, speech',ex:'言葉 (ことば) word, language'},
  {c:'赤',on:'セキ・シャク',kun:'あか・あか(い)',mean:'red',ex:'赤色 (あかいろ) red color'},
  {c:'走',on:'ソウ',kun:'はし(る)',mean:'run',ex:'走者 (そうしゃ) runner'},
  {c:'近',on:'キン',kun:'ちか(い)',mean:'near, close, recent',ex:'最近 (さいきん) recently'},
  {c:'事',on:'ジ・ズ',kun:'こと',mean:'matter, thing, affair',ex:'事務所 (じむしょ) office'},
  {c:'京',on:'キョウ・ケイ',kun:'みやこ',mean:'capital',ex:'東京 (とうきょう) Tokyo'},
  {c:'使',on:'シ',kun:'つか(う)',mean:'use, messenger, envoy',ex:'使用 (しよう) use, usage'},
  {c:'味',on:'ミ',kun:'あじ・あじ(わう)',mean:'flavor, taste',ex:'意味 (いみ) meaning'},
  {c:'夜',on:'ヤ',kun:'よる・よ',mean:'night, evening',ex:'今夜 (こんや) tonight'},
  {c:'妹',on:'マイ',kun:'いもうと',mean:'younger sister',ex:'姉妹 (しまい) sisters'},
  {c:'姉',on:'シ',kun:'あね',mean:'older sister',ex:'姉妹 (しまい) sisters'},
  {c:'始',on:'シ',kun:'はじ(まる)・はじ(める)',mean:'begin, start',ex:'開始 (かいし) start, beginning'},
  {c:'明',on:'メイ・ミョウ',kun:'あ(かるい)・あ(ける)',mean:'bright, clear, light',ex:'説明 (せつめい) explanation'},
  {c:'服',on:'フク',kun:'—',mean:'clothing, dress, obey',ex:'洋服 (ようふく) Western clothes'},
  {c:'歩',on:'ホ・ブ',kun:'ある(く)・あゆ(む)',mean:'walk, step',ex:'散歩 (さんぽ) walk, stroll'},
  {c:'注',on:'チュウ',kun:'そそ(ぐ)',mean:'pour, concentrate, note',ex:'注意 (ちゅうい) caution, attention'},
  {c:'物',on:'ブツ・モツ',kun:'もの',mean:'thing, object, matter',ex:'動物 (どうぶつ) animal'},
  {c:'画',on:'ガ・カク',kun:'—',mean:'picture, drawing, stroke',ex:'映画 (えいが) movie'},
  {c:'知',on:'チ',kun:'し(る)',mean:'know, wisdom',ex:'知人 (ちじん) acquaintance'},
  {c:'者',on:'シャ',kun:'もの',mean:'person, someone',ex:'医者 (いしゃ) doctor'},
  {c:'英',on:'エイ',kun:'—',mean:'England, English, hero',ex:'英語 (えいご) English language'},
  {c:'青',on:'セイ・ショウ',kun:'あお・あお(い)',mean:'blue, green',ex:'青年 (せいねん) youth, young man'},
  {c:'品',on:'ヒン',kun:'しな',mean:'goods, article, quality',ex:'食品 (しょくひん) food products'},
  {c:'室',on:'シツ',kun:'むろ',mean:'room, chamber',ex:'教室 (きょうしつ) classroom'},
  {c:'屋',on:'オク',kun:'や',mean:'roof, shop, house',ex:'部屋 (へや) room'},
  {c:'度',on:'ド・ト・タク',kun:'たび',mean:'degree, time, occurrence',ex:'今度 (こんど) this time, next time'},
  {c:'建',on:'ケン・コン',kun:'た(てる)・た(つ)',mean:'build, construct',ex:'建物 (たてもの) building'},
  {c:'待',on:'タイ',kun:'ま(つ)',mean:'wait, await',ex:'招待 (しょうたい) invitation'},
  {c:'思',on:'シ',kun:'おも(う)',mean:'think, feel',ex:'思想 (しそう) thought, ideology'},
  {c:'急',on:'キュウ',kun:'いそ(ぐ)',mean:'hurry, urgent, sudden',ex:'急行 (きゅうこう) express train'},
  {c:'持',on:'ジ',kun:'も(つ)',mean:'hold, have, carry',ex:'気持ち (きもち) feeling'},
  {c:'映',on:'エイ',kun:'うつ(る)・うつ(す)・は(える)',mean:'reflect, project',ex:'映画 (えいが) movie'},
  {c:'春',on:'シュン',kun:'はる',mean:'spring (season)',ex:'春休み (はるやすみ) spring vacation'},
  {c:'昼',on:'チュウ',kun:'ひる',mean:'daytime, noon',ex:'昼食 (ちゅうしょく) lunch'},
  {c:'洋',on:'ヨウ',kun:'—',mean:'ocean, Western style',ex:'洋服 (ようふく) Western clothes'},
  {c:'海',on:'カイ',kun:'うみ',mean:'sea, ocean',ex:'海外 (かいがい) overseas'},
  {c:'界',on:'カイ',kun:'—',mean:'world, boundary',ex:'世界 (せかい) world'},
  {c:'発',on:'ハツ・ホツ',kun:'—',mean:'departure, emit, start',ex:'発音 (はつおん) pronunciation'},
  {c:'研',on:'ケン',kun:'と(ぐ)',mean:'polish, sharpen, study',ex:'研究 (けんきゅう) research'},
  {c:'秋',on:'シュウ',kun:'あき',mean:'autumn, fall',ex:'秋分 (しゅうぶん) autumnal equinox'},
  {c:'茶',on:'チャ・サ',kun:'—',mean:'tea',ex:'お茶 (おちゃ) tea'},
  {c:'計',on:'ケイ',kun:'はか(る)・はか(らう)',mean:'measure, plan, count',ex:'時計 (とけい) clock, watch'},
  {c:'送',on:'ソウ',kun:'おく(る)',mean:'send, escort, see off',ex:'放送 (ほうそう) broadcast'},
  {c:'重',on:'ジュウ・チョウ',kun:'おも(い)・かさ(ねる)・え',mean:'heavy, important, -fold',ex:'重要 (じゅうよう) important'},
  {c:'音',on:'オン・イン',kun:'おと・ね',mean:'sound, noise',ex:'音楽 (おんがく) music'},
  {c:'風',on:'フウ・フ',kun:'かぜ・かざ',mean:'wind, style, manner',ex:'台風 (たいふう) typhoon'},
  {c:'借',on:'シャク',kun:'か(りる)',mean:'borrow, rent',ex:'借金 (しゃっきん) debt'},
  {c:'勉',on:'ベン',kun:'つと(める)',mean:'exert, make effort, diligence',ex:'勉強 (べんきょう) study'},
  {c:'員',on:'イン',kun:'—',mean:'member, employee',ex:'店員 (てんいん) shop clerk'},
  {c:'夏',on:'カ・ゲ',kun:'なつ',mean:'summer',ex:'夏休み (なつやすみ) summer vacation'},
  {c:'家',on:'カ・ケ',kun:'いえ・や',mean:'house, home, family',ex:'家族 (かぞく) family'},
  {c:'帰',on:'キ',kun:'かえ(る)・かえ(す)',mean:'return, go home',ex:'帰国 (きこく) return to one\'s country'},
  {c:'料',on:'リョウ',kun:'—',mean:'fee, materials, charge',ex:'料理 (りょうり) cooking, dish'},
  {c:'旅',on:'リョ',kun:'たび',mean:'trip, travel, journey',ex:'旅行 (りょこう) travel, trip'},
  {c:'特',on:'トク',kun:'—',mean:'special, particular',ex:'特急 (とっきゅう) limited express'},
  {c:'病',on:'ビョウ・ヘイ',kun:'や(む)・やまい',mean:'illness, sick',ex:'病院 (びょういん) hospital'},
  {c:'真',on:'シン',kun:'ま・まこと',mean:'true, real, genuine',ex:'写真 (しゃしん) photograph'},
  {c:'紙',on:'シ',kun:'かみ',mean:'paper',ex:'手紙 (てがみ) letter'},
  {c:'起',on:'キ',kun:'お(きる)・お(こる)・お(こす)',mean:'wake up, rise, occur',ex:'起立 (きりつ) standing up'},
  {c:'通',on:'ツウ・ツ',kun:'とお(る)・かよ(う)',mean:'pass through, commute, avenue',ex:'交通 (こうつう) traffic, transport'},
  {c:'院',on:'イン',kun:'—',mean:'institution, temple',ex:'病院 (びょういん) hospital'},
  {c:'動',on:'ドウ',kun:'うご(く)・うご(かす)',mean:'move, motion',ex:'運動 (うんどう) exercise, movement'},
  {c:'問',on:'モン',kun:'と(う)・とい',mean:'question, ask, problem',ex:'問題 (もんだい) problem, question'},
  {c:'堂',on:'ドウ',kun:'—',mean:'hall, public chamber',ex:'食堂 (しょくどう) dining hall, cafeteria'},
  {c:'強',on:'キョウ・ゴウ',kun:'つよ(い)・し(いる)',mean:'strong, powerful',ex:'勉強 (べんきょう) study'},
  {c:'悪',on:'アク・オ',kun:'わる(い)',mean:'bad, evil, wrong',ex:'悪化 (あっか) worsening'},
  {c:'教',on:'キョウ',kun:'おし(える)・おそ(わる)',mean:'teach, faith, doctrine',ex:'教室 (きょうしつ) classroom'},
  {c:'族',on:'ゾク',kun:'—',mean:'tribe, family, clan',ex:'家族 (かぞく) family'},
  {c:'理',on:'リ',kun:'—',mean:'logic, reason, arrangement',ex:'料理 (りょうり) cooking, dish'},
  {c:'終',on:'シュウ',kun:'お(わる)・お(える)',mean:'end, finish',ex:'終電 (しゅうでん) last train'},
  {c:'習',on:'シュウ',kun:'なら(う)',mean:'learn, practice',ex:'練習 (れんしゅう) practice'},
  {c:'転',on:'テン',kun:'ころ(がる)・ころ(ぶ)',mean:'revolve, turn, roll',ex:'自転車 (じてんしゃ) bicycle'},
  {c:'週',on:'シュウ',kun:'—',mean:'week',ex:'今週 (こんしゅう) this week'},
  {c:'野',on:'ヤ',kun:'の',mean:'field, plains, civilian',ex:'野菜 (やさい) vegetable'},
  {c:'鳥',on:'チョウ',kun:'とり',mean:'bird, chicken',ex:'小鳥 (ことり) small bird'},
  {c:'黒',on:'コク',kun:'くろ・くろ(い)',mean:'black',ex:'黒板 (こくばん) blackboard'},
  {c:'場',on:'ジョウ',kun:'ば',mean:'place, location, site',ex:'場所 (ばしょ) place, location'},
  {c:'朝',on:'チョウ',kun:'あさ',mean:'morning',ex:'毎朝 (まいあさ) every morning'},
  {c:'着',on:'チャク・ジャク',kun:'き(る)・つ(く)',mean:'wear, arrive',ex:'到着 (とうちゃく) arrival'},
  {c:'答',on:'トウ',kun:'こた(える)・こた(え)',mean:'answer, solution',ex:'返答 (へんとう) reply, answer'},
  {c:'貸',on:'タイ',kun:'か(す)',mean:'lend, loan',ex:'貸間 (かしま) room for rent'},
  {c:'運',on:'ウン',kun:'はこ(ぶ)',mean:'carry, luck, transport',ex:'運転 (うんてん) driving'},
  {c:'開',on:'カイ',kun:'ひら(く)・あ(く)・あ(ける)',mean:'open, unfold',ex:'開店 (かいてん) shop opening'},
  {c:'集',on:'シュウ',kun:'あつ(まる)・あつ(める)',mean:'gather, collect',ex:'集中 (しゅうちゅう) concentration'},
  {c:'飯',on:'ハン',kun:'めし',mean:'meal, boiled rice',ex:'御飯 (ごはん) cooked rice, meal'},
  {c:'意',on:'イ',kun:'—',mean:'mind, meaning, intention',ex:'意見 (いけん) opinion'},
  {c:'業',on:'ギョウ・ゴウ',kun:'わざ',mean:'business, vocation, arts',ex:'授業 (じゅぎょう) class, lesson'},
  {c:'楽',on:'ガク・ラク',kun:'たの(しい)・たの(しむ)',mean:'music, comfort, ease',ex:'音楽 (おんがく) music'},
  {c:'漢',on:'カン',kun:'—',mean:'Han, China, Sino-',ex:'漢字 (かんじ) kanji, Chinese character'},
  {c:'試',on:'シ',kun:'こころ(みる)・ため(す)',mean:'test, try, attempt',ex:'試験 (しけん) exam'},
  {c:'歌',on:'カ',kun:'うた・うた(う)',mean:'song, sing',ex:'歌手 (かしゅ) singer'},
  {c:'銀',on:'ギン',kun:'—',mean:'silver',ex:'銀行 (ぎんこう) bank'},
  {c:'質',on:'シツ・シチ',kun:'—',mean:'quality, substance, matter',ex:'質問 (しつもん) question'},
  {c:'親',on:'シン',kun:'おや・した(しい)',mean:'parent, intimacy',ex:'両親 (りょうしん) parents'},
  {c:'館',on:'カン',kun:'やかた',mean:'building, hall, mansion',ex:'旅館 (りょかん) Japanese inn'},
  {c:'曜',on:'ヨウ',kun:'—',mean:'day of the week',ex:'曜日 (ようび) day of the week'},
  {c:'題',on:'ダイ',kun:'—',mean:'topic, subject, title',ex:'宿題 (しゅくだい) homework'},
  {c:'験',on:'ケン・ゲン',kun:'—',mean:'test, verification, effect',ex:'経験 (けいけん) experience'},
  {c:'働',on:'ドウ',kun:'はたら(く)',mean:'work, labor',ex:'労働 (ろうどう) labor, work'},
  {c:'橋',on:'キョウ',kun:'はし',mean:'bridge',ex:'歩道橋 (ほどうきょう) pedestrian bridge'},
  {c:'港',on:'コウ',kun:'みなと',mean:'harbor, port',ex:'空港 (くうこう) airport'},
  {c:'船',on:'セン',kun:'ふね・ふな',mean:'ship, boat',ex:'船便 (ふなびん) sea mail'},
  {c:'乗',on:'ジョウ',kun:'の(る)・の(せる)',mean:'ride, board, get on',ex:'乗車 (じょうしゃ) boarding'},
  {c:'降',on:'コウ',kun:'お(りる)・ふ(る)',mean:'descend, get off, fall (rain)',ex:'降車 (こうしゃ) getting off (a vehicle)'},
  {c:'速',on:'ソク',kun:'はや(い)・はや(める)',mean:'fast, quick, speed',ex:'速度 (そくど) speed'},
  {c:'遅',on:'チ',kun:'おそ(い)・おく(れる)',mean:'late, slow, delay',ex:'遅刻 (ちこく) being late, tardiness'},
  {c:'初',on:'ショ',kun:'はじ(め)・はつ・うい',mean:'first, beginning',ex:'最初 (さいしょ) the first, beginning'},
  {c:'最',on:'サイ',kun:'もっと(も)',mean:'most, utmost',ex:'最後 (さいご) the last, end'},
  {c:'当',on:'トウ',kun:'あ(たる)・あ(てる)',mean:'hit, apply, this',ex:'本当 (ほんとう) truth, real'},
  {c:'期',on:'キ・ゴ',kun:'—',mean:'period, term, time',ex:'学期 (がっき) school term, semester'},
  {c:'困',on:'コン',kun:'こま(る)',mean:'be troubled, distressed',ex:'困難 (こんなん) difficulty, hardship'},
  {c:'決',on:'ケツ',kun:'き(める)・き(まる)',mean:'decide, determine',ex:'決定 (けってい) decision'},
  {c:'調',on:'チョウ',kun:'しら(べる)・ととの(える)',mean:'investigate, tune, tone',ex:'調子 (ちょうし) condition, tone'},
  {c:'説',on:'セツ・ゼイ',kun:'と(く)',mean:'explain, theory, opinion',ex:'説明 (せつめい) explanation'},
  {c:'返',on:'ヘン',kun:'かえ(す)・かえ(る)',mean:'return, give back',ex:'返事 (へんじ) reply, answer'},
  {c:'受',on:'ジュ',kun:'う(ける)・う(かる)',mean:'receive, accept',ex:'受付 (うけつけ) reception'},
  {c:'取',on:'シュ',kun:'と(る)',mean:'take, get, fetch',ex:'取材 (しゅざい) news gathering, interview'}
];

export { N4_KANJI };
