var N4_VOCAB = [
  {jp:'上がる',kana:'あがる',romaji:'agaru',en:'to rise, to go up',cat:'Verbs'},
  {jp:'集める',kana:'あつめる',romaji:'atsumeru',en:'to collect, to gather',cat:'Verbs'},
  {jp:'謝る',kana:'あやまる',romaji:'ayamaru',en:'to apologize',cat:'Verbs'},
  {jp:'急ぐ',kana:'いそぐ',romaji:'isogu',en:'to hurry',cat:'Verbs'},
  {jp:'いじめる',kana:'いじめる',romaji:'ijimeru',en:'to bully',cat:'Verbs'},
  {jp:'祈る',kana:'いのる',romaji:'inoru',en:'to pray, to wish',cat:'Verbs'},
  {jp:'いらっしゃる',kana:'いらっしゃる',romaji:'irassharu',en:'to be, to come, to go (honorific)',cat:'Verbs'},
  {jp:'植える',kana:'うえる',romaji:'ueru',en:'to plant',cat:'Verbs'},
  {jp:'動く',kana:'うごく',romaji:'ugoku',en:'to move',cat:'Verbs'},
  {jp:'打つ',kana:'うつ',romaji:'utsu',en:'to hit, to strike',cat:'Verbs'},
  {jp:'移る',kana:'うつる',romaji:'utsuru',en:'to move, to transfer',cat:'Verbs'},
  {jp:'選ぶ',kana:'えらぶ',romaji:'erabu',en:'to choose, to select',cat:'Verbs'},
  {jp:'送る',kana:'おくる',romaji:'okuru',en:'to send, to see off',cat:'Verbs'},
  {jp:'遅れる',kana:'おくれる',romaji:'okureru',en:'to be late, to fall behind',cat:'Verbs'},
  {jp:'起こす',kana:'おこす',romaji:'okosu',en:'to wake someone, to cause',cat:'Verbs'},
  {jp:'怒る',kana:'おこる',romaji:'okoru',en:'to get angry',cat:'Verbs'},
  {jp:'落とす',kana:'おとす',romaji:'otosu',en:'to drop',cat:'Verbs'},
  {jp:'落ちる',kana:'おちる',romaji:'ochiru',en:'to fall, to drop',cat:'Verbs'},
  {jp:'思い出す',kana:'おもいだす',romaji:'omoidasu',en:'to recall, to remember',cat:'Verbs'},
  {jp:'下りる',kana:'おりる',romaji:'oriru',en:'to get off, to descend',cat:'Verbs'},
  {jp:'飼う',kana:'かう',romaji:'kau',en:'to keep, to raise (an animal)',cat:'Verbs'},
  {jp:'帰す',kana:'かえす',romaji:'kaesu',en:'to send back, to return something',cat:'Verbs'},
  {jp:'変える',kana:'かえる',romaji:'kaeru',en:'to change something',cat:'Verbs'},
  {jp:'変わる',kana:'かわる',romaji:'kawaru',en:'to change',cat:'Verbs'},
  {jp:'かける',kana:'かける',romaji:'kakeru',en:'to hang, to put on',cat:'Verbs'},
  {jp:'勝つ',kana:'かつ',romaji:'katsu',en:'to win',cat:'Verbs'},
  {jp:'通う',kana:'かよう',romaji:'kayou',en:'to commute, to attend',cat:'Verbs'},
  {jp:'考える',kana:'かんがえる',romaji:'kangaeru',en:'to think, to consider',cat:'Verbs'},
  {jp:'頑張る',kana:'がんばる',romaji:'ganbaru',en:'to do your best, to persevere',cat:'Verbs'},
  {jp:'聞こえる',kana:'きこえる',romaji:'kikoeru',en:'to be audible, to be heard',cat:'Verbs'},
  {jp:'決める',kana:'きめる',romaji:'kimeru',en:'to decide',cat:'Verbs'},
  {jp:'決まる',kana:'きまる',romaji:'kimaru',en:'to be decided',cat:'Verbs'},
  {jp:'比べる',kana:'くらべる',romaji:'kuraberu',en:'to compare',cat:'Verbs'},
  {jp:'壊す',kana:'こわす',romaji:'kowasu',en:'to break something',cat:'Verbs'},
  {jp:'壊れる',kana:'こわれる',romaji:'kowareru',en:'to be broken',cat:'Verbs'},
  {jp:'探す',kana:'さがす',romaji:'sagasu',en:'to search, to look for',cat:'Verbs'},
  {jp:'下がる',kana:'さがる',romaji:'sagaru',en:'to go down, to hang down',cat:'Verbs'},
  {jp:'下げる',kana:'さげる',romaji:'sageru',en:'to lower, to hang',cat:'Verbs'},
  {jp:'触る',kana:'さわる',romaji:'sawaru',en:'to touch',cat:'Verbs'},
  {jp:'閉める',kana:'しめる',romaji:'shimeru',en:'to close something',cat:'Verbs'},
  {jp:'閉まる',kana:'しまる',romaji:'shimaru',en:'to be closed',cat:'Verbs'},
  {jp:'調べる',kana:'しらべる',romaji:'shiraberu',en:'to investigate, to check',cat:'Verbs'},
  {jp:'過ぎる',kana:'すぎる',romaji:'sugiru',en:'to pass, to exceed',cat:'Verbs'},
  {jp:'進む',kana:'すすむ',romaji:'susumu',en:'to advance, to proceed',cat:'Verbs'},
  {jp:'捨てる',kana:'すてる',romaji:'suteru',en:'to throw away',cat:'Verbs'},
  {jp:'過ごす',kana:'すごす',romaji:'sugosu',en:'to spend (time)',cat:'Verbs'},
  {jp:'育てる',kana:'そだてる',romaji:'sodateru',en:'to raise, to bring up',cat:'Verbs'},
  {jp:'倒れる',kana:'たおれる',romaji:'taoreru',en:'to fall over, to collapse',cat:'Verbs'},
  {jp:'足す',kana:'たす',romaji:'tasu',en:'to add',cat:'Verbs'},
  {jp:'助ける',kana:'たすける',romaji:'tasukeru',en:'to help, to rescue',cat:'Verbs'},
  {jp:'尋ねる',kana:'たずねる',romaji:'tazuneru',en:'to ask, to inquire',cat:'Verbs'},
  {jp:'立てる',kana:'たてる',romaji:'tateru',en:'to stand something up, to set up',cat:'Verbs'},
  {jp:'建てる',kana:'たてる',romaji:'tateru',en:'to build',cat:'Verbs'},
  {jp:'楽しむ',kana:'たのしむ',romaji:'tanoshimu',en:'to enjoy',cat:'Verbs'},
  {jp:'頼む',kana:'たのむ',romaji:'tanomu',en:'to ask, to request',cat:'Verbs'},
  {jp:'足りる',kana:'たりる',romaji:'tariru',en:'to be enough',cat:'Verbs'},
  {jp:'続く',kana:'つづく',romaji:'tsuzuku',en:'to continue',cat:'Verbs'},
  {jp:'続ける',kana:'つづける',romaji:'tsuzukeru',en:'to continue something',cat:'Verbs'},
  {jp:'勤める',kana:'つとめる',romaji:'tsutomeru',en:'to work for, to be employed',cat:'Verbs'},
  {jp:'連れる',kana:'つれる',romaji:'tsureru',en:'to take along (a person)',cat:'Verbs'},
  {jp:'手伝う',kana:'てつだう',romaji:'tetsudau',en:'to help, to assist',cat:'Verbs'},
  {jp:'届く',kana:'とどく',romaji:'todoku',en:'to reach, to be delivered',cat:'Verbs'},
  {jp:'届ける',kana:'とどける',romaji:'todokeru',en:'to deliver',cat:'Verbs'},
  {jp:'飛ぶ',kana:'とぶ',romaji:'tobu',en:'to fly, to jump',cat:'Verbs'},
  {jp:'泊まる',kana:'とまる',romaji:'tomaru',en:'to stay overnight',cat:'Verbs'},
  {jp:'止める',kana:'とめる',romaji:'tomeru',en:'to stop something',cat:'Verbs'},
  {jp:'直す',kana:'なおす',romaji:'naosu',en:'to fix, to repair',cat:'Verbs'},
  {jp:'直る',kana:'なおる',romaji:'naoru',en:'to be fixed',cat:'Verbs'},
  {jp:'治る',kana:'なおる',romaji:'naoru',en:'to be cured, to heal',cat:'Verbs'},
  {jp:'泣く',kana:'なく',romaji:'naku',en:'to cry',cat:'Verbs'},
  {jp:'亡くなる',kana:'なくなる',romaji:'nakunaru',en:'to die, to pass away',cat:'Verbs'},
  {jp:'無くなる',kana:'なくなる',romaji:'nakunaru',en:'to be lost, to run out',cat:'Verbs'},
  {jp:'鳴る',kana:'なる',romaji:'naru',en:'to ring, to sound',cat:'Verbs'},
  {jp:'慣れる',kana:'なれる',romaji:'nareru',en:'to get used to',cat:'Verbs'},
  {jp:'濡れる',kana:'ぬれる',romaji:'nureru',en:'to get wet',cat:'Verbs'},
  {jp:'眠る',kana:'ねむる',romaji:'nemuru',en:'to sleep',cat:'Verbs'},
  {jp:'残る',kana:'のこる',romaji:'nokoru',en:'to remain, to be left',cat:'Verbs'},
  {jp:'乗り換える',kana:'のりかえる',romaji:'norikaeru',en:'to transfer, to change (trains)',cat:'Verbs'},
  {jp:'運ぶ',kana:'はこぶ',romaji:'hakobu',en:'to carry, to transport',cat:'Verbs'},
  {jp:'始める',kana:'はじめる',romaji:'hajimeru',en:'to begin something',cat:'Verbs'},
  {jp:'走る',kana:'はしる',romaji:'hashiru',en:'to run',cat:'Verbs'},
  {jp:'働く',kana:'はたらく',romaji:'hataraku',en:'to work',cat:'Verbs'},
  {jp:'払う',kana:'はらう',romaji:'harau',en:'to pay',cat:'Verbs'},
  {jp:'冷える',kana:'ひえる',romaji:'hieru',en:'to get cold',cat:'Verbs'},
  {jp:'光る',kana:'ひかる',romaji:'hikaru',en:'to shine, to glitter',cat:'Verbs'},
  {jp:'引く',kana:'ひく',romaji:'hiku',en:'to pull, to subtract',cat:'Verbs'},
  {jp:'引っ越す',kana:'ひっこす',romaji:'hikkosu',en:'to move (house)',cat:'Verbs'},
  {jp:'開く',kana:'ひらく',romaji:'hiraku',en:'to open, to hold (an event)',cat:'Verbs'},
  {jp:'拾う',kana:'ひろう',romaji:'hirou',en:'to pick up',cat:'Verbs'},
  {jp:'増える',kana:'ふえる',romaji:'fueru',en:'to increase',cat:'Verbs'},
  {jp:'吹く',kana:'ふく',romaji:'fuku',en:'to blow (wind)',cat:'Verbs'},
  {jp:'褒める',kana:'ほめる',romaji:'homeru',en:'to praise',cat:'Verbs'},
  {jp:'参る',kana:'まいる',romaji:'mairu',en:'to come, to go (humble)',cat:'Verbs'},
  {jp:'負ける',kana:'まける',romaji:'makeru',en:'to lose, to be defeated',cat:'Verbs'},
  {jp:'間違える',kana:'まちがえる',romaji:'machigaeru',en:'to make a mistake',cat:'Verbs'},
  {jp:'間に合う',kana:'まにあう',romaji:'maniau',en:'to be in time',cat:'Verbs'},
  {jp:'守る',kana:'まもる',romaji:'mamoru',en:'to protect, to keep (a promise)',cat:'Verbs'},
  {jp:'回る',kana:'まわる',romaji:'mawaru',en:'to turn, to go around',cat:'Verbs'},
  {jp:'見える',kana:'みえる',romaji:'mieru',en:'to be visible, to be able to see',cat:'Verbs'},
  {jp:'見つかる',kana:'みつかる',romaji:'mitsukaru',en:'to be found',cat:'Verbs'},
  {jp:'見つける',kana:'みつける',romaji:'mitsukeru',en:'to find',cat:'Verbs'},
  {jp:'迎える',kana:'むかえる',romaji:'mukaeru',en:'to welcome, to go to meet',cat:'Verbs'},
  {jp:'召し上がる',kana:'めしあがる',romaji:'meshiagaru',en:'to eat, to drink (honorific)',cat:'Verbs'},
  {jp:'申す',kana:'もうす',romaji:'mousu',en:'to say, to be called (humble)',cat:'Verbs'},
  {jp:'戻る',kana:'もどる',romaji:'modoru',en:'to return, to go back',cat:'Verbs'},
  {jp:'戻す',kana:'もどす',romaji:'modosu',en:'to return something, to put back',cat:'Verbs'},
  {jp:'もらう',kana:'もらう',romaji:'morau',en:'to receive',cat:'Verbs'},
  {jp:'焼く',kana:'やく',romaji:'yaku',en:'to bake, to grill, to burn',cat:'Verbs'},
  {jp:'役に立つ',kana:'やくにたつ',romaji:'yakunitatsu',en:'to be useful',cat:'Verbs'},
  {jp:'焼ける',kana:'やける',romaji:'yakeru',en:'to be burned, to be grilled',cat:'Verbs'},
  {jp:'やせる',kana:'やせる',romaji:'yaseru',en:'to lose weight, to become thin',cat:'Verbs'},
  {jp:'やる',kana:'やる',romaji:'yaru',en:'to do, to give',cat:'Verbs'},
  {jp:'止む',kana:'やむ',romaji:'yamu',en:'to stop (rain)',cat:'Verbs'},
  {jp:'やめる',kana:'やめる',romaji:'yameru',en:'to quit, to stop',cat:'Verbs'},
  {jp:'揺れる',kana:'ゆれる',romaji:'yureru',en:'to shake, to sway',cat:'Verbs'},
  {jp:'汚れる',kana:'よごれる',romaji:'yogoreru',en:'to get dirty',cat:'Verbs'},
  {jp:'喜ぶ',kana:'よろこぶ',romaji:'yorokobu',en:'to be glad, to rejoice',cat:'Verbs'},
  {jp:'別れる',kana:'わかれる',romaji:'wakareru',en:'to part, to separate',cat:'Verbs'},
  {jp:'笑う',kana:'わらう',romaji:'warau',en:'to laugh, to smile',cat:'Verbs'},
  {jp:'割れる',kana:'われる',romaji:'wareru',en:'to break, to split',cat:'Verbs'},
  {jp:'浅い',kana:'あさい',romaji:'asai',en:'shallow',cat:'Adjectives'},
  {jp:'うまい',kana:'うまい',romaji:'umai',en:'skillful, delicious',cat:'Adjectives'},
  {jp:'うるさい',kana:'うるさい',romaji:'urusai',en:'noisy, annoying',cat:'Adjectives'},
  {jp:'うれしい',kana:'うれしい',romaji:'ureshii',en:'happy, glad',cat:'Adjectives'},
  {jp:'おかしい',kana:'おかしい',romaji:'okashii',en:'strange, funny',cat:'Adjectives'},
  {jp:'恐ろしい',kana:'おそろしい',romaji:'osoroshii',en:'terrible, frightening',cat:'Adjectives'},
  {jp:'固い',kana:'かたい',romaji:'katai',en:'hard, firm',cat:'Adjectives'},
  {jp:'悲しい',kana:'かなしい',romaji:'kanashii',en:'sad',cat:'Adjectives'},
  {jp:'かゆい',kana:'かゆい',romaji:'kayui',en:'itchy',cat:'Adjectives'},
  {jp:'かっこいい',kana:'かっこいい',romaji:'kakkoii',en:'cool, good-looking',cat:'Adjectives'},
  {jp:'厳しい',kana:'きびしい',romaji:'kibishii',en:'strict, severe',cat:'Adjectives'},
  {jp:'きつい',kana:'きつい',romaji:'kitsui',en:'tight, tough',cat:'Adjectives'},
  {jp:'臭い',kana:'くさい',romaji:'kusai',en:'smelly, stinky',cat:'Adjectives'},
  {jp:'詳しい',kana:'くわしい',romaji:'kuwashii',en:'detailed, knowledgeable',cat:'Adjectives'},
  {jp:'濃い',kana:'こい',romaji:'koi',en:'thick, strong (taste, color)',cat:'Adjectives'},
  {jp:'細かい',kana:'こまかい',romaji:'komakai',en:'fine, detailed',cat:'Adjectives'},
  {jp:'怖い',kana:'こわい',romaji:'kowai',en:'scary, frightening',cat:'Adjectives'},
  {jp:'寂しい',kana:'さびしい',romaji:'sabishii',en:'lonely',cat:'Adjectives'},
  {jp:'親しい',kana:'したしい',romaji:'shitashii',en:'close, intimate (friend)',cat:'Adjectives'},
  {jp:'すごい',kana:'すごい',romaji:'sugoi',en:'amazing, terrible',cat:'Adjectives'},
  {jp:'すっぱい',kana:'すっぱい',romaji:'suppai',en:'sour',cat:'Adjectives'},
  {jp:'素晴らしい',kana:'すばらしい',romaji:'subarashii',en:'wonderful, splendid',cat:'Adjectives'},
  {jp:'正しい',kana:'ただしい',romaji:'tadashii',en:'correct, right',cat:'Adjectives'},
  {jp:'楽しい',kana:'たのしい',romaji:'tanoshii',en:'fun, enjoyable',cat:'Adjectives'},
  {jp:'つらい',kana:'つらい',romaji:'tsurai',en:'painful, hard',cat:'Adjectives'},
  {jp:'懐かしい',kana:'なつかしい',romaji:'natsukashii',en:'nostalgic, dear',cat:'Adjectives'},
  {jp:'苦い',kana:'にがい',romaji:'nigai',en:'bitter',cat:'Adjectives'},
  {jp:'眠い',kana:'ねむい',romaji:'nemui',en:'sleepy',cat:'Adjectives'},
  {jp:'激しい',kana:'はげしい',romaji:'hageshii',en:'intense, violent',cat:'Adjectives'},
  {jp:'恥ずかしい',kana:'はずかしい',romaji:'hazukashii',en:'embarrassing, shy',cat:'Adjectives'},
  {jp:'ひどい',kana:'ひどい',romaji:'hidoi',en:'terrible, cruel',cat:'Adjectives'},
  {jp:'深い',kana:'ふかい',romaji:'fukai',en:'deep',cat:'Adjectives'},
  {jp:'太い',kana:'ふとい',romaji:'futoi',en:'thick, fat',cat:'Adjectives'},
  {jp:'細い',kana:'ほそい',romaji:'hosoi',en:'thin, narrow',cat:'Adjectives'},
  {jp:'欲しい',kana:'ほしい',romaji:'hoshii',en:'wanted, desired',cat:'Adjectives'},
  {jp:'まずい',kana:'まずい',romaji:'mazui',en:'bad-tasting, awkward',cat:'Adjectives'},
  {jp:'丸い',kana:'まるい',romaji:'marui',en:'round',cat:'Adjectives'},
  {jp:'珍しい',kana:'めずらしい',romaji:'mezurashii',en:'rare, unusual',cat:'Adjectives'},
  {jp:'もったいない',kana:'もったいない',romaji:'mottainai',en:'wasteful, too good',cat:'Adjectives'},
  {jp:'易しい',kana:'やさしい',romaji:'yasashii',en:'easy, simple',cat:'Adjectives'},
  {jp:'柔らかい',kana:'やわらかい',romaji:'yawarakai',en:'soft, tender',cat:'Adjectives'},
  {jp:'緩い',kana:'ゆるい',romaji:'yurui',en:'loose, lenient',cat:'Adjectives'},
  {jp:'安心',kana:'あんしん',romaji:'anshin',en:'relief, peace of mind',cat:'Na-adjectives'},
  {jp:'安全',kana:'あんぜん',romaji:'anzen',en:'safe, safety',cat:'Na-adjectives'},
  {jp:'いろいろ',kana:'いろいろ',romaji:'iroiro',en:'various',cat:'Na-adjectives'},
  {jp:'大事',kana:'だいじ',romaji:'daiji',en:'important, valuable',cat:'Na-adjectives'},
  {jp:'残念',kana:'ざんねん',romaji:'zannen',en:'regrettable, disappointing',cat:'Na-adjectives'},
  {jp:'幸せ',kana:'しあわせ',romaji:'shiawase',en:'happy, fortunate',cat:'Na-adjectives'},
  {jp:'失礼',kana:'しつれい',romaji:'shitsurei',en:'rude, impolite',cat:'Na-adjectives'},
  {jp:'十分',kana:'じゅうぶん',romaji:'juubun',en:'enough, sufficient',cat:'Na-adjectives'},
  {jp:'自由',kana:'じゆう',romaji:'jiyuu',en:'free, freedom',cat:'Na-adjectives'},
  {jp:'丈夫',kana:'じょうぶ',romaji:'joubu',en:'sturdy, durable, healthy',cat:'Na-adjectives'},
  {jp:'親切',kana:'しんせつ',romaji:'shinsetsu',en:'kind',cat:'Na-adjectives'},
  {jp:'心配',kana:'しんぱい',romaji:'shinpai',en:'worried, anxious',cat:'Na-adjectives'},
  {jp:'素敵',kana:'すてき',romaji:'suteki',en:'lovely, wonderful',cat:'Na-adjectives'},
  {jp:'大切',kana:'たいせつ',romaji:'taisetsu',en:'important, precious',cat:'Na-adjectives'},
  {jp:'確か',kana:'たしか',romaji:'tashika',en:'certain, sure',cat:'Na-adjectives'},
  {jp:'丁寧',kana:'ていねい',romaji:'teinei',en:'polite, careful',cat:'Na-adjectives'},
  {jp:'得意',kana:'とくい',romaji:'tokui',en:'good at, proud',cat:'Na-adjectives'},
  {jp:'特別',kana:'とくべつ',romaji:'tokubetsu',en:'special',cat:'Na-adjectives'},
  {jp:'苦手',kana:'にがて',romaji:'nigate',en:'poor at, weak point',cat:'Na-adjectives'},
  {jp:'熱心',kana:'ねっしん',romaji:'nesshin',en:'enthusiastic, eager',cat:'Na-adjectives'},
  {jp:'必要',kana:'ひつよう',romaji:'hitsuyou',en:'necessary',cat:'Na-adjectives'},
  {jp:'複雑',kana:'ふくざつ',romaji:'fukuzatsu',en:'complicated, complex',cat:'Na-adjectives'},
  {jp:'不便',kana:'ふべん',romaji:'fuben',en:'inconvenient',cat:'Na-adjectives'},
  {jp:'真面目',kana:'まじめ',romaji:'majime',en:'serious, diligent',cat:'Na-adjectives'},
  {jp:'無理',kana:'むり',romaji:'muri',en:'impossible, unreasonable',cat:'Na-adjectives'},
  {jp:'楽',kana:'らく',romaji:'raku',en:'comfortable, easy',cat:'Na-adjectives'},
  {jp:'立派',kana:'りっぱ',romaji:'rippa',en:'splendid, fine',cat:'Na-adjectives'},
  {jp:'同じ',kana:'おなじ',romaji:'onaji',en:'same',cat:'Na-adjectives'},
  {jp:'必ず',kana:'かならず',romaji:'kanarazu',en:'certainly, without fail',cat:'Adverbs'},
  {jp:'急に',kana:'きゅうに',romaji:'kyuuni',en:'suddenly',cat:'Adverbs'},
  {jp:'きっと',kana:'きっと',romaji:'kitto',en:'surely, certainly',cat:'Adverbs'},
  {jp:'結構',kana:'けっこう',romaji:'kekkou',en:'quite, fairly',cat:'Adverbs'},
  {jp:'決して',kana:'けっして',romaji:'kesshite',en:'never (with negative)',cat:'Adverbs'},
  {jp:'しっかり',kana:'しっかり',romaji:'shikkari',en:'firmly, properly',cat:'Adverbs'},
  {jp:'しばらく',kana:'しばらく',romaji:'shibaraku',en:'for a while',cat:'Adverbs'},
  {jp:'ずいぶん',kana:'ずいぶん',romaji:'zuibun',en:'considerably, fairly',cat:'Adverbs'},
  {jp:'ぜひ',kana:'ぜひ',romaji:'zehi',en:'by all means, certainly',cat:'Adverbs'},
  {jp:'そろそろ',kana:'そろそろ',romaji:'sorosoro',en:'soon, gradually',cat:'Adverbs'},
  {jp:'大体',kana:'だいたい',romaji:'daitai',en:'mostly, roughly',cat:'Adverbs'},
  {jp:'たいてい',kana:'たいてい',romaji:'taitei',en:'usually, mostly',cat:'Adverbs'},
  {jp:'たまに',kana:'たまに',romaji:'tamani',en:'occasionally',cat:'Adverbs'},
  {jp:'できるだけ',kana:'できるだけ',romaji:'dekirudake',en:'as much as possible',cat:'Adverbs'},
  {jp:'特に',kana:'とくに',romaji:'tokuni',en:'especially, particularly',cat:'Adverbs'},
  {jp:'なかなか',kana:'なかなか',romaji:'nakanaka',en:'quite, not easily',cat:'Adverbs'},
  {jp:'なるべく',kana:'なるべく',romaji:'narubeku',en:'as much as possible',cat:'Adverbs'},
  {jp:'はっきり',kana:'はっきり',romaji:'hakkiri',en:'clearly',cat:'Adverbs'},
  {jp:'びっくり',kana:'びっくり',romaji:'bikkuri',en:'surprised, startled',cat:'Adverbs'},
  {jp:'ほとんど',kana:'ほとんど',romaji:'hotondo',en:'almost, mostly',cat:'Adverbs'},
  {jp:'まず',kana:'まず',romaji:'mazu',en:'first of all',cat:'Adverbs'},
  {jp:'もうすぐ',kana:'もうすぐ',romaji:'mousugu',en:'soon, before long',cat:'Adverbs'},
  {jp:'もし',kana:'もし',romaji:'moshi',en:'if',cat:'Adverbs'},
  {jp:'やっと',kana:'やっと',romaji:'yatto',en:'finally, at last',cat:'Adverbs'},
  {jp:'やはり',kana:'やはり',romaji:'yahari',en:'as expected, still',cat:'Adverbs'},
  {jp:'ゆっくり',kana:'ゆっくり',romaji:'yukkuri',en:'slowly, leisurely',cat:'Adverbs'},
  {jp:'すっかり',kana:'すっかり',romaji:'sukkari',en:'completely, thoroughly',cat:'Adverbs'},
  {jp:'もっと',kana:'もっと',romaji:'motto',en:'more',cat:'Adverbs'},
  {jp:'赤ちゃん',kana:'あかちゃん',romaji:'akachan',en:'baby',cat:'People'},
  {jp:'彼',kana:'かれ',romaji:'kare',en:'he, boyfriend',cat:'People'},
  {jp:'彼女',kana:'かのじょ',romaji:'kanojo',en:'she, girlfriend',cat:'People'},
  {jp:'家族',kana:'かぞく',romaji:'kazoku',en:'family',cat:'People'},
  {jp:'客',kana:'きゃく',romaji:'kyaku',en:'guest, customer',cat:'People'},
  {jp:'校長',kana:'こうちょう',romaji:'kouchou',en:'school principal',cat:'People'},
  {jp:'子供',kana:'こども',romaji:'kodomo',en:'child',cat:'People'},
  {jp:'社長',kana:'しゃちょう',romaji:'shachou',en:'company president',cat:'People'},
  {jp:'主人',kana:'しゅじん',romaji:'shujin',en:'husband, master',cat:'People'},
  {jp:'親戚',kana:'しんせき',romaji:'shinseki',en:'relative',cat:'People'},
  {jp:'店員',kana:'てんいん',romaji:'tenin',en:'shop assistant',cat:'People'},
  {jp:'泥棒',kana:'どろぼう',romaji:'dorobou',en:'thief',cat:'People'},
  {jp:'仲間',kana:'なかま',romaji:'nakama',en:'companion, colleague',cat:'People'},
  {jp:'人々',kana:'ひとびと',romaji:'hitobito',en:'people',cat:'People'},
  {jp:'夫',kana:'おっと',romaji:'otto',en:'husband',cat:'People'},
  {jp:'妻',kana:'つま',romaji:'tsuma',en:'wife',cat:'People'},
  {jp:'娘',kana:'むすめ',romaji:'musume',en:'daughter',cat:'People'},
  {jp:'息子',kana:'むすこ',romaji:'musuko',en:'son',cat:'People'},
  {jp:'孫',kana:'まご',romaji:'mago',en:'grandchild',cat:'People'},
  {jp:'頭',kana:'あたま',romaji:'atama',en:'head',cat:'Body & Health'},
  {jp:'命',kana:'いのち',romaji:'inochi',en:'life',cat:'Body & Health'},
  {jp:'息',kana:'いき',romaji:'iki',en:'breath',cat:'Body & Health'},
  {jp:'怪我',kana:'けが',romaji:'kega',en:'injury',cat:'Body & Health'},
  {jp:'血',kana:'ち',romaji:'chi',en:'blood',cat:'Body & Health'},
  {jp:'力',kana:'ちから',romaji:'chikara',en:'strength, power',cat:'Body & Health'},
  {jp:'毛',kana:'け',romaji:'ke',en:'hair, fur',cat:'Body & Health'},
  {jp:'指',kana:'ゆび',romaji:'yubi',en:'finger',cat:'Body & Health'},
  {jp:'肌',kana:'はだ',romaji:'hada',en:'skin',cat:'Body & Health'},
  {jp:'骨',kana:'ほね',romaji:'hone',en:'bone',cat:'Body & Health'},
  {jp:'喉',kana:'のど',romaji:'nodo',en:'throat',cat:'Body & Health'},
  {jp:'腹',kana:'はら',romaji:'hara',en:'belly, stomach',cat:'Body & Health'},
  {jp:'胸',kana:'むね',romaji:'mune',en:'chest, breast',cat:'Body & Health'},
  {jp:'背中',kana:'せなか',romaji:'senaka',en:'back (of body)',cat:'Body & Health'},
  {jp:'腰',kana:'こし',romaji:'koshi',en:'lower back, waist',cat:'Body & Health'},
  {jp:'熱',kana:'ねつ',romaji:'netsu',en:'fever, heat',cat:'Body & Health'},
  {jp:'風邪',kana:'かぜ',romaji:'kaze',en:'cold (illness)',cat:'Body & Health'},
  {jp:'薬',kana:'くすり',romaji:'kusuri',en:'medicine',cat:'Body & Health'},
  {jp:'手術',kana:'しゅじゅつ',romaji:'shujutsu',en:'surgery, operation',cat:'Body & Health'},
  {jp:'入院',kana:'にゅういん',romaji:'nyuuin',en:'hospitalization',cat:'Body & Health'},
  {jp:'糸',kana:'いと',romaji:'ito',en:'thread, string',cat:'Home'},
  {jp:'押し入れ',kana:'おしいれ',romaji:'oshiire',en:'closet',cat:'Home'},
  {jp:'鍵',kana:'かぎ',romaji:'kagi',en:'key, lock',cat:'Home'},
  {jp:'壁',kana:'かべ',romaji:'kabe',en:'wall',cat:'Home'},
  {jp:'毛布',kana:'もうふ',romaji:'moufu',en:'blanket',cat:'Home'},
  {jp:'畳',kana:'たたみ',romaji:'tatami',en:'tatami mat',cat:'Home'},
  {jp:'棚',kana:'たな',romaji:'tana',en:'shelf',cat:'Home'},
  {jp:'引き出し',kana:'ひきだし',romaji:'hikidashi',en:'drawer',cat:'Home'},
  {jp:'布団',kana:'ふとん',romaji:'futon',en:'futon, bedding',cat:'Home'},
  {jp:'屋根',kana:'やね',romaji:'yane',en:'roof',cat:'Home'},
  {jp:'床',kana:'ゆか',romaji:'yuka',en:'floor',cat:'Home'},
  {jp:'居間',kana:'いま',romaji:'ima',en:'living room',cat:'Home'},
  {jp:'水道',kana:'すいどう',romaji:'suidou',en:'water supply, tap water',cat:'Home'},
  {jp:'家賃',kana:'やちん',romaji:'yachin',en:'rent',cat:'Home'},
  {jp:'引っ越し',kana:'ひっこし',romaji:'hikkoshi',en:'moving (house)',cat:'Home'},
  {jp:'掃除',kana:'そうじ',romaji:'souji',en:'cleaning',cat:'Home'},
  {jp:'洗濯',kana:'せんたく',romaji:'sentaku',en:'laundry',cat:'Home'},
  {jp:'台所',kana:'だいどころ',romaji:'daidokoro',en:'kitchen',cat:'Home'},
  {jp:'庭',kana:'にわ',romaji:'niwa',en:'garden, yard',cat:'Home'},
  {jp:'味',kana:'あじ',romaji:'aji',en:'taste, flavor',cat:'Food'},
  {jp:'味噌',kana:'みそ',romaji:'miso',en:'miso',cat:'Food'},
  {jp:'お菓子',kana:'おかし',romaji:'okashi',en:'sweets, snacks',cat:'Food'},
  {jp:'お代わり',kana:'おかわり',romaji:'okawari',en:'second helping, refill',cat:'Food'},
  {jp:'お弁当',kana:'おべんとう',romaji:'obentou',en:'boxed lunch',cat:'Food'},
  {jp:'お湯',kana:'おゆ',romaji:'oyu',en:'hot water',cat:'Food'},
  {jp:'缶',kana:'かん',romaji:'kan',en:'can',cat:'Food'},
  {jp:'米',kana:'こめ',romaji:'kome',en:'rice (uncooked)',cat:'Food'},
  {jp:'砂糖',kana:'さとう',romaji:'satou',en:'sugar',cat:'Food'},
  {jp:'塩',kana:'しお',romaji:'shio',en:'salt',cat:'Food'},
  {jp:'醤油',kana:'しょうゆ',romaji:'shouyu',en:'soy sauce',cat:'Food'},
  {jp:'食事',kana:'しょくじ',romaji:'shokuji',en:'meal',cat:'Food'},
  {jp:'食料品',kana:'しょくりょうひん',romaji:'shokuryouhin',en:'groceries, foodstuffs',cat:'Food'},
  {jp:'すき焼き',kana:'すきやき',romaji:'sukiyaki',en:'sukiyaki',cat:'Food'},
  {jp:'刺身',kana:'さしみ',romaji:'sashimi',en:'sashimi',cat:'Food'},
  {jp:'豆',kana:'まめ',romaji:'mame',en:'bean',cat:'Food'},
  {jp:'麦',kana:'むぎ',romaji:'mugi',en:'wheat, barley',cat:'Food'},
  {jp:'おつまみ',kana:'おつまみ',romaji:'otsumami',en:'snack (with drinks)',cat:'Food'},
  {jp:'飲み物',kana:'のみもの',romaji:'nomimono',en:'beverage, drink',cat:'Food'},
  {jp:'お茶碗',kana:'おちゃわん',romaji:'ochawan',en:'rice bowl',cat:'Food'},
  {jp:'裏',kana:'うら',romaji:'ura',en:'back, reverse side',cat:'Places'},
  {jp:'会場',kana:'かいじょう',romaji:'kaijou',en:'venue, meeting place',cat:'Places'},
  {jp:'郊外',kana:'こうがい',romaji:'kougai',en:'suburbs',cat:'Places'},
  {jp:'工場',kana:'こうじょう',romaji:'koujou',en:'factory',cat:'Places'},
  {jp:'空港',kana:'くうこう',romaji:'kuukou',en:'airport',cat:'Places'},
  {jp:'坂',kana:'さか',romaji:'saka',en:'slope, hill',cat:'Places'},
  {jp:'市',kana:'し',romaji:'shi',en:'city',cat:'Places'},
  {jp:'寺',kana:'てら',romaji:'tera',en:'temple',cat:'Places'},
  {jp:'都会',kana:'とかい',romaji:'tokai',en:'city, urban area',cat:'Places'},
  {jp:'島',kana:'しま',romaji:'shima',en:'island',cat:'Places'},
  {jp:'神社',kana:'じんじゃ',romaji:'jinja',en:'shrine',cat:'Places'},
  {jp:'橋',kana:'はし',romaji:'hashi',en:'bridge',cat:'Places'},
  {jp:'港',kana:'みなと',romaji:'minato',en:'harbor, port',cat:'Places'},
  {jp:'美術館',kana:'びじゅつかん',romaji:'bijutsukan',en:'art museum',cat:'Places'},
  {jp:'駐車場',kana:'ちゅうしゃじょう',romaji:'chuushajou',en:'parking lot',cat:'Places'},
  {jp:'動物園',kana:'どうぶつえん',romaji:'doubutsuen',en:'zoo',cat:'Places'},
  {jp:'場所',kana:'ばしょ',romaji:'basho',en:'place, location',cat:'Places'},
  {jp:'近所',kana:'きんじょ',romaji:'kinjo',en:'neighborhood',cat:'Places'},
  {jp:'田舎',kana:'いなか',romaji:'inaka',en:'countryside, hometown',cat:'Places'},
  {jp:'区',kana:'く',romaji:'ku',en:'ward, district',cat:'Places'},
  {jp:'運転',kana:'うんてん',romaji:'unten',en:'driving',cat:'Transport'},
  {jp:'運転手',kana:'うんてんしゅ',romaji:'untenshu',en:'driver',cat:'Transport'},
  {jp:'踏切',kana:'ふみきり',romaji:'fumikiri',en:'railroad crossing',cat:'Transport'},
  {jp:'急行',kana:'きゅうこう',romaji:'kyuukou',en:'express (train)',cat:'Transport'},
  {jp:'特急',kana:'とっきゅう',romaji:'tokkyuu',en:'limited express',cat:'Transport'},
  {jp:'交通',kana:'こうつう',romaji:'koutsuu',en:'traffic, transportation',cat:'Transport'},
  {jp:'事故',kana:'じこ',romaji:'jiko',en:'accident',cat:'Transport'},
  {jp:'指定席',kana:'していせき',romaji:'shiteiseki',en:'reserved seat',cat:'Transport'},
  {jp:'自由席',kana:'じゆうせき',romaji:'jiyuuseki',en:'unreserved seat',cat:'Transport'},
  {jp:'席',kana:'せき',romaji:'seki',en:'seat',cat:'Transport'},
  {jp:'船',kana:'ふね',romaji:'fune',en:'ship, boat',cat:'Transport'},
  {jp:'普通',kana:'ふつう',romaji:'futsuu',en:'local (train), ordinary',cat:'Transport'},
  {jp:'飛行場',kana:'ひこうじょう',romaji:'hikoujou',en:'airfield',cat:'Transport'},
  {jp:'乗り物',kana:'のりもの',romaji:'norimono',en:'vehicle',cat:'Transport'},
  {jp:'信号',kana:'しんごう',romaji:'shingou',en:'traffic light, signal',cat:'Transport'},
  {jp:'通り',kana:'とおり',romaji:'toori',en:'street, avenue',cat:'Transport'},
  {jp:'横断歩道',kana:'おうだんほどう',romaji:'oudanhodou',en:'pedestrian crossing',cat:'Transport'},
  {jp:'渋滞',kana:'じゅうたい',romaji:'juutai',en:'traffic jam',cat:'Transport'},
  {jp:'案内',kana:'あんない',romaji:'annai',en:'guidance, information',cat:'Work & School'},
  {jp:'医学',kana:'いがく',romaji:'igaku',en:'medical science',cat:'Work & School'},
  {jp:'受付',kana:'うけつけ',romaji:'uketsuke',en:'reception',cat:'Work & School'},
  {jp:'会議',kana:'かいぎ',romaji:'kaigi',en:'meeting, conference',cat:'Work & School'},
  {jp:'会議室',kana:'かいぎしつ',romaji:'kaigishitsu',en:'meeting room',cat:'Work & School'},
  {jp:'科学',kana:'かがく',romaji:'kagaku',en:'science',cat:'Work & School'},
  {jp:'教育',kana:'きょういく',romaji:'kyouiku',en:'education',cat:'Work & School'},
  {jp:'教科書',kana:'きょうかしょ',romaji:'kyoukasho',en:'textbook',cat:'Work & School'},
  {jp:'経済',kana:'けいざい',romaji:'keizai',en:'economy, economics',cat:'Work & School'},
  {jp:'経験',kana:'けいけん',romaji:'keiken',en:'experience',cat:'Work & School'},
  {jp:'研究',kana:'けんきゅう',romaji:'kenkyuu',en:'research',cat:'Work & School'},
  {jp:'研究室',kana:'けんきゅうしつ',romaji:'kenkyuushitsu',en:'laboratory, study room',cat:'Work & School'},
  {jp:'工業',kana:'こうぎょう',romaji:'kougyou',en:'industry',cat:'Work & School'},
  {jp:'高校',kana:'こうこう',romaji:'koukou',en:'high school',cat:'Work & School'},
  {jp:'講義',kana:'こうぎ',romaji:'kougi',en:'lecture',cat:'Work & School'},
  {jp:'仕事',kana:'しごと',romaji:'shigoto',en:'work, job',cat:'Work & School'},
  {jp:'社会',kana:'しゃかい',romaji:'shakai',en:'society',cat:'Work & School'},
  {jp:'就職',kana:'しゅうしょく',romaji:'shuushoku',en:'finding employment',cat:'Work & School'},
  {jp:'宿題',kana:'しゅくだい',romaji:'shukudai',en:'homework',cat:'Work & School'},
  {jp:'準備',kana:'じゅんび',romaji:'junbi',en:'preparation',cat:'Work & School'},
  {jp:'小学校',kana:'しょうがっこう',romaji:'shougakkou',en:'elementary school',cat:'Work & School'},
  {jp:'中学校',kana:'ちゅうがっこう',romaji:'chuugakkou',en:'junior high school',cat:'Work & School'},
  {jp:'大学院',kana:'だいがくいん',romaji:'daigakuin',en:'graduate school',cat:'Work & School'},
  {jp:'卒業',kana:'そつぎょう',romaji:'sotsugyou',en:'graduation',cat:'Work & School'},
  {jp:'入学',kana:'にゅうがく',romaji:'nyuugaku',en:'school admission',cat:'Work & School'},
  {jp:'試験',kana:'しけん',romaji:'shiken',en:'exam, test',cat:'Work & School'},
  {jp:'欠席',kana:'けっせき',romaji:'kesseki',en:'absence',cat:'Work & School'},
  {jp:'出席',kana:'しゅっせき',romaji:'shusseki',en:'attendance',cat:'Work & School'},
  {jp:'戦争',kana:'せんそう',romaji:'sensou',en:'war',cat:'Society'},
  {jp:'政治',kana:'せいじ',romaji:'seiji',en:'politics',cat:'Society'},
  {jp:'法律',kana:'ほうりつ',romaji:'houritsu',en:'law',cat:'Society'},
  {jp:'規則',kana:'きそく',romaji:'kisoku',en:'rule, regulation',cat:'Society'},
  {jp:'文化',kana:'ぶんか',romaji:'bunka',en:'culture',cat:'Society'},
  {jp:'歴史',kana:'れきし',romaji:'rekishi',en:'history',cat:'Society'},
  {jp:'宗教',kana:'しゅうきょう',romaji:'shuukyou',en:'religion',cat:'Society'},
  {jp:'平和',kana:'へいわ',romaji:'heiwa',en:'peace',cat:'Society'},
  {jp:'産業',kana:'さんぎょう',romaji:'sangyou',en:'industry',cat:'Society'},
  {jp:'貿易',kana:'ぼうえき',romaji:'boueki',en:'trade',cat:'Society'},
  {jp:'国民',kana:'こくみん',romaji:'kokumin',en:'citizens, nation',cat:'Society'},
  {jp:'人口',kana:'じんこう',romaji:'jinkou',en:'population',cat:'Society'},
  {jp:'警察',kana:'けいさつ',romaji:'keisatsu',en:'police',cat:'Society'},
  {jp:'消防署',kana:'しょうぼうしょ',romaji:'shoubousho',en:'fire station',cat:'Society'},
  {jp:'役所',kana:'やくしょ',romaji:'yakusho',en:'government office',cat:'Society'},
  {jp:'選挙',kana:'せんきょ',romaji:'senkyo',en:'election',cat:'Society'},
  {jp:'環境',kana:'かんきょう',romaji:'kankyou',en:'environment',cat:'Society'},
  {jp:'社会人',kana:'しゃかいじん',romaji:'shakaijin',en:'working adult, member of society',cat:'Society'},
  {jp:'政府',kana:'せいふ',romaji:'seifu',en:'government',cat:'Society'},
  {jp:'枝',kana:'えだ',romaji:'eda',en:'branch',cat:'Nature & Weather'},
  {jp:'温度',kana:'おんど',romaji:'ondo',en:'temperature',cat:'Nature & Weather'},
  {jp:'火',kana:'ひ',romaji:'hi',en:'fire',cat:'Nature & Weather'},
  {jp:'火事',kana:'かじ',romaji:'kaji',en:'fire (disaster)',cat:'Nature & Weather'},
  {jp:'湖',kana:'みずうみ',romaji:'mizuumi',en:'lake',cat:'Nature & Weather'},
  {jp:'砂',kana:'すな',romaji:'suna',en:'sand',cat:'Nature & Weather'},
  {jp:'地震',kana:'じしん',romaji:'jishin',en:'earthquake',cat:'Nature & Weather'},
  {jp:'台風',kana:'たいふう',romaji:'taifuu',en:'typhoon',cat:'Nature & Weather'},
  {jp:'月',kana:'つき',romaji:'tsuki',en:'moon',cat:'Nature & Weather'},
  {jp:'葉',kana:'は',romaji:'ha',en:'leaf',cat:'Nature & Weather'},
  {jp:'林',kana:'はやし',romaji:'hayashi',en:'woods, grove',cat:'Nature & Weather'},
  {jp:'星',kana:'ほし',romaji:'hoshi',en:'star',cat:'Nature & Weather'},
  {jp:'光',kana:'ひかり',romaji:'hikari',en:'light',cat:'Nature & Weather'},
  {jp:'森',kana:'もり',romaji:'mori',en:'forest',cat:'Nature & Weather'},
  {jp:'雲',kana:'くも',romaji:'kumo',en:'cloud',cat:'Nature & Weather'},
  {jp:'波',kana:'なみ',romaji:'nami',en:'wave',cat:'Nature & Weather'},
  {jp:'石',kana:'いし',romaji:'ishi',en:'stone',cat:'Nature & Weather'},
  {jp:'草',kana:'くさ',romaji:'kusa',en:'grass',cat:'Nature & Weather'},
  {jp:'虫',kana:'むし',romaji:'mushi',en:'insect, bug',cat:'Nature & Weather'},
  {jp:'空',kana:'そら',romaji:'sora',en:'sky',cat:'Nature & Weather'},
  {jp:'明日',kana:'あす',romaji:'asu',en:'tomorrow',cat:'Time'},
  {jp:'以下',kana:'いか',romaji:'ika',en:'less than, below',cat:'Time'},
  {jp:'以上',kana:'いじょう',romaji:'ijou',en:'more than, above',cat:'Time'},
  {jp:'以前',kana:'いぜん',romaji:'izen',en:'before, previously',cat:'Time'},
  {jp:'以来',kana:'いらい',romaji:'irai',en:'since',cat:'Time'},
  {jp:'一日中',kana:'いちにちじゅう',romaji:'ichinichijuu',en:'all day long',cat:'Time'},
  {jp:'過去',kana:'かこ',romaji:'kako',en:'past',cat:'Time'},
  {jp:'今後',kana:'こんご',romaji:'kongo',en:'from now on',cat:'Time'},
  {jp:'最近',kana:'さいきん',romaji:'saikin',en:'recently',cat:'Time'},
  {jp:'最後',kana:'さいご',romaji:'saigo',en:'last, end',cat:'Time'},
  {jp:'最初',kana:'さいしょ',romaji:'saisho',en:'first, beginning',cat:'Time'},
  {jp:'将来',kana:'しょうらい',romaji:'shourai',en:'future',cat:'Time'},
  {jp:'昔',kana:'むかし',romaji:'mukashi',en:'long ago, the past',cat:'Time'},
  {jp:'夜中',kana:'よなか',romaji:'yonaka',en:'middle of the night',cat:'Time'},
  {jp:'期間',kana:'きかん',romaji:'kikan',en:'period of time',cat:'Time'},
  {jp:'期限',kana:'きげん',romaji:'kigen',en:'deadline, time limit',cat:'Time'},
  {jp:'当時',kana:'とうじ',romaji:'touji',en:'at that time',cat:'Time'},
  {jp:'平日',kana:'へいじつ',romaji:'heijitsu',en:'weekday',cat:'Time'},
  {jp:'挨拶',kana:'あいさつ',romaji:'aisatsu',en:'greeting',cat:'Communication'},
  {jp:'意見',kana:'いけん',romaji:'iken',en:'opinion',cat:'Communication'},
  {jp:'意味',kana:'いみ',romaji:'imi',en:'meaning',cat:'Communication'},
  {jp:'会話',kana:'かいわ',romaji:'kaiwa',en:'conversation',cat:'Communication'},
  {jp:'返事',kana:'へんじ',romaji:'henji',en:'reply, answer',cat:'Communication'},
  {jp:'言葉',kana:'ことば',romaji:'kotoba',en:'word, language',cat:'Communication'},
  {jp:'手紙',kana:'てがみ',romaji:'tegami',en:'letter',cat:'Communication'},
  {jp:'説明',kana:'せつめい',romaji:'setsumei',en:'explanation',cat:'Communication'},
  {jp:'相談',kana:'そうだん',romaji:'soudan',en:'consultation, discussion',cat:'Communication'},
  {jp:'注意',kana:'ちゅうい',romaji:'chuui',en:'caution, attention',cat:'Communication'},
  {jp:'発音',kana:'はつおん',romaji:'hatsuon',en:'pronunciation',cat:'Communication'},
  {jp:'放送',kana:'ほうそう',romaji:'housou',en:'broadcast',cat:'Communication'},
  {jp:'文法',kana:'ぶんぽう',romaji:'bunpou',en:'grammar',cat:'Communication'},
  {jp:'文章',kana:'ぶんしょう',romaji:'bunshou',en:'sentence, writing',cat:'Communication'},
  {jp:'返信',kana:'へんしん',romaji:'henshin',en:'reply (mail)',cat:'Communication'},
  {jp:'翻訳',kana:'ほんやく',romaji:'honyaku',en:'translation',cat:'Communication'},
  {jp:'約束',kana:'やくそく',romaji:'yakusoku',en:'promise, appointment',cat:'Communication'},
  {jp:'用事',kana:'ようじ',romaji:'youji',en:'errand, business',cat:'Communication'},
  {jp:'連絡',kana:'れんらく',romaji:'renraku',en:'contact, communication',cat:'Communication'},
  {jp:'声',kana:'こえ',romaji:'koe',en:'voice',cat:'Communication'},
  {jp:'噂',kana:'うわさ',romaji:'uwasa',en:'rumor',cat:'Communication'},
  {jp:'質問',kana:'しつもん',romaji:'shitsumon',en:'question',cat:'Communication'},
  {jp:'値段',kana:'ねだん',romaji:'nedan',en:'price',cat:'Shopping & Money'},
  {jp:'値上げ',kana:'ねあげ',romaji:'neage',en:'price increase',cat:'Shopping & Money'},
  {jp:'お釣り',kana:'おつり',romaji:'otsuri',en:'change (money)',cat:'Shopping & Money'},
  {jp:'お金',kana:'おかね',romaji:'okane',en:'money',cat:'Shopping & Money'},
  {jp:'会計',kana:'かいけい',romaji:'kaikei',en:'bill, accounting',cat:'Shopping & Money'},
  {jp:'貯金',kana:'ちょきん',romaji:'chokin',en:'savings',cat:'Shopping & Money'},
  {jp:'財布',kana:'さいふ',romaji:'saifu',en:'wallet',cat:'Shopping & Money'},
  {jp:'品物',kana:'しなもの',romaji:'shinamono',en:'goods, article',cat:'Shopping & Money'},
  {jp:'代金',kana:'だいきん',romaji:'daikin',en:'price, charge',cat:'Shopping & Money'},
  {jp:'代わり',kana:'かわり',romaji:'kawari',en:'substitute, replacement',cat:'Shopping & Money'},
  {jp:'店',kana:'みせ',romaji:'mise',en:'shop, store',cat:'Shopping & Money'},
  {jp:'無料',kana:'むりょう',romaji:'muryou',en:'free of charge',cat:'Shopping & Money'},
  {jp:'輸入',kana:'ゆにゅう',romaji:'yunyuu',en:'import',cat:'Shopping & Money'},
  {jp:'輸出',kana:'ゆしゅつ',romaji:'yushutsu',en:'export',cat:'Shopping & Money'},
  {jp:'料金',kana:'りょうきん',romaji:'ryoukin',en:'fee, charge',cat:'Shopping & Money'},
  {jp:'割引',kana:'わりびき',romaji:'waribiki',en:'discount',cat:'Shopping & Money'},
  {jp:'現金',kana:'げんきん',romaji:'genkin',en:'cash',cat:'Shopping & Money'},
  {jp:'通帳',kana:'つうちょう',romaji:'tsuuchou',en:'bankbook, passbook',cat:'Shopping & Money'},
  {jp:'歌',kana:'うた',romaji:'uta',en:'song',cat:'Hobbies'},
  {jp:'絵',kana:'え',romaji:'e',en:'picture, drawing',cat:'Hobbies'},
  {jp:'演奏',kana:'えんそう',romaji:'ensou',en:'musical performance',cat:'Hobbies'},
  {jp:'音楽会',kana:'おんがくかい',romaji:'ongakukai',en:'concert',cat:'Hobbies'},
  {jp:'楽器',kana:'がっき',romaji:'gakki',en:'musical instrument',cat:'Hobbies'},
  {jp:'試合',kana:'しあい',romaji:'shiai',en:'match, game',cat:'Hobbies'},
  {jp:'趣味',kana:'しゅみ',romaji:'shumi',en:'hobby',cat:'Hobbies'},
  {jp:'小説',kana:'しょうせつ',romaji:'shousetsu',en:'novel',cat:'Hobbies'},
  {jp:'人形',kana:'にんぎょう',romaji:'ningyou',en:'doll',cat:'Hobbies'},
  {jp:'登山',kana:'とざん',romaji:'tozan',en:'mountain climbing',cat:'Hobbies'},
  {jp:'美術',kana:'びじゅつ',romaji:'bijutsu',en:'art, fine arts',cat:'Hobbies'},
  {jp:'踊り',kana:'おどり',romaji:'odori',en:'dance',cat:'Hobbies'},
  {jp:'漫画',kana:'まんが',romaji:'manga',en:'comic, manga',cat:'Hobbies'},
  {jp:'番組',kana:'ばんぐみ',romaji:'bangumi',en:'TV/radio program',cat:'Hobbies'},
  {jp:'花見',kana:'はなみ',romaji:'hanami',en:'cherry blossom viewing',cat:'Hobbies'},
  {jp:'釣り',kana:'つり',romaji:'tsuri',en:'fishing',cat:'Hobbies'},
  {jp:'映画館',kana:'えいがかん',romaji:'eigakan',en:'movie theater',cat:'Hobbies'},
  {jp:'愛',kana:'あい',romaji:'ai',en:'love',cat:'Feelings'},
  {jp:'怒り',kana:'いかり',romaji:'ikari',en:'anger',cat:'Feelings'},
  {jp:'感じ',kana:'かんじ',romaji:'kanji',en:'feeling, impression',cat:'Feelings'},
  {jp:'感謝',kana:'かんしゃ',romaji:'kansha',en:'gratitude',cat:'Feelings'},
  {jp:'感動',kana:'かんどう',romaji:'kandou',en:'being moved, deep emotion',cat:'Feelings'},
  {jp:'気持ち',kana:'きもち',romaji:'kimochi',en:'feeling, mood',cat:'Feelings'},
  {jp:'気分',kana:'きぶん',romaji:'kibun',en:'mood, feeling',cat:'Feelings'},
  {jp:'興味',kana:'きょうみ',romaji:'kyoumi',en:'interest',cat:'Feelings'},
  {jp:'心',kana:'こころ',romaji:'kokoro',en:'heart, mind',cat:'Feelings'},
  {jp:'自信',kana:'じしん',romaji:'jishin',en:'confidence',cat:'Feelings'},
  {jp:'我慢',kana:'がまん',romaji:'gaman',en:'patience, endurance',cat:'Feelings'},
  {jp:'希望',kana:'きぼう',romaji:'kibou',en:'hope, wish',cat:'Feelings'},
  {jp:'喜び',kana:'よろこび',romaji:'yorokobi',en:'joy, delight',cat:'Feelings'},
  {jp:'夢',kana:'ゆめ',romaji:'yume',en:'dream',cat:'Feelings'},
  {jp:'涙',kana:'なみだ',romaji:'namida',en:'tears',cat:'Feelings'},
  {jp:'笑顔',kana:'えがお',romaji:'egao',en:'smile, smiling face',cat:'Feelings'},
  {jp:'緊張',kana:'きんちょう',romaji:'kinchou',en:'tension, nervousness',cat:'Feelings'},
  {jp:'恋',kana:'こい',romaji:'koi',en:'romantic love',cat:'Feelings'},
  {jp:'相手',kana:'あいて',romaji:'aite',en:'partner, opponent',cat:'Abstract'},
  {jp:'味方',kana:'みかた',romaji:'mikata',en:'ally, supporter',cat:'Abstract'},
  {jp:'うそ',kana:'うそ',romaji:'uso',en:'lie',cat:'Abstract'},
  {jp:'運',kana:'うん',romaji:'un',en:'luck, fortune',cat:'Abstract'},
  {jp:'おかげ',kana:'おかげ',romaji:'okage',en:'thanks to, owing to',cat:'Abstract'},
  {jp:'空気',kana:'くうき',romaji:'kuuki',en:'air, atmosphere',cat:'Abstract'},
  {jp:'計画',kana:'けいかく',romaji:'keikaku',en:'plan',cat:'Abstract'},
  {jp:'結果',kana:'けっか',romaji:'kekka',en:'result',cat:'Abstract'},
  {jp:'原因',kana:'げんいん',romaji:'genin',en:'cause',cat:'Abstract'},
  {jp:'最高',kana:'さいこう',romaji:'saikou',en:'best, highest',cat:'Abstract'},
  {jp:'最低',kana:'さいてい',romaji:'saitei',en:'worst, lowest',cat:'Abstract'},
  {jp:'仕方',kana:'しかた',romaji:'shikata',en:'way, method',cat:'Abstract'},
  {jp:'種類',kana:'しゅるい',romaji:'shurui',en:'kind, type',cat:'Abstract'},
  {jp:'方法',kana:'ほうほう',romaji:'houhou',en:'method, way',cat:'Abstract'},
  {jp:'場合',kana:'ばあい',romaji:'baai',en:'case, situation',cat:'Abstract'},
  {jp:'反対',kana:'はんたい',romaji:'hantai',en:'opposite, opposition',cat:'Abstract'},
  {jp:'部分',kana:'ぶぶん',romaji:'bubun',en:'part, portion',cat:'Abstract'},
  {jp:'理由',kana:'りゆう',romaji:'riyuu',en:'reason',cat:'Abstract'},
  {jp:'量',kana:'りょう',romaji:'ryou',en:'quantity, amount',cat:'Abstract'},
  {jp:'例',kana:'れい',romaji:'rei',en:'example',cat:'Abstract'},
  {jp:'関係',kana:'かんけい',romaji:'kankei',en:'relation, relationship',cat:'Abstract'},
  {jp:'機会',kana:'きかい',romaji:'kikai',en:'opportunity, chance',cat:'Abstract'},
  {jp:'内容',kana:'ないよう',romaji:'naiyou',en:'content',cat:'Abstract'},
  {jp:'目的',kana:'もくてき',romaji:'mokuteki',en:'purpose, goal',cat:'Abstract'},
  {jp:'予定',kana:'よてい',romaji:'yotei',en:'plan, schedule',cat:'Abstract'},
  {jp:'都合',kana:'つごう',romaji:'tsugou',en:'circumstances, convenience',cat:'Abstract'},
  {jp:'調子',kana:'ちょうし',romaji:'choushi',en:'condition, state',cat:'Abstract'},
  {jp:'うちわ',kana:'うちわ',romaji:'uchiwa',en:'paper fan',cat:'Objects'},
  {jp:'機械',kana:'きかい',romaji:'kikai',en:'machine',cat:'Objects'},
  {jp:'金属',kana:'きんぞく',romaji:'kinzoku',en:'metal',cat:'Objects'},
  {jp:'品',kana:'しな',romaji:'shina',en:'goods, article',cat:'Objects'},
  {jp:'石鹸',kana:'せっけん',romaji:'sekken',en:'soap',cat:'Objects'},
  {jp:'瓶',kana:'びん',romaji:'bin',en:'bottle',cat:'Objects'},
  {jp:'袋',kana:'ふくろ',romaji:'fukuro',en:'bag, sack',cat:'Objects'},
  {jp:'布',kana:'ぬの',romaji:'nuno',en:'cloth',cat:'Objects'},
  {jp:'針',kana:'はり',romaji:'hari',en:'needle',cat:'Objects'},
  {jp:'道具',kana:'どうぐ',romaji:'dougu',en:'tool, instrument',cat:'Objects'},
  {jp:'荷物',kana:'にもつ',romaji:'nimotsu',en:'luggage, baggage',cat:'Objects'},
  {jp:'はさみ',kana:'はさみ',romaji:'hasami',en:'scissors',cat:'Objects'},
  {jp:'箱',kana:'はこ',romaji:'hako',en:'box',cat:'Objects'},
  {jp:'はがき',kana:'はがき',romaji:'hagaki',en:'postcard',cat:'Objects'},
  {jp:'紐',kana:'ひも',romaji:'himo',en:'string, cord',cat:'Objects'},
  {jp:'封筒',kana:'ふうとう',romaji:'fuutou',en:'envelope',cat:'Objects'},
  {jp:'本棚',kana:'ほんだな',romaji:'hondana',en:'bookshelf',cat:'Objects'},
  {jp:'指輪',kana:'ゆびわ',romaji:'yubiwa',en:'ring',cat:'Objects'},
  {jp:'パソコン',kana:'パソコン',romaji:'pasokon',en:'personal computer',cat:'Objects'},
  {jp:'携帯',kana:'けいたい',romaji:'keitai',en:'mobile phone',cat:'Objects'},
  {jp:'地図',kana:'ちず',romaji:'chizu',en:'map',cat:'Objects'},
  {jp:'毛糸',kana:'けいと',romaji:'keito',en:'wool, knitting yarn',cat:'Objects'},
  {jp:'湯飲み',kana:'ゆのみ',romaji:'yunomi',en:'teacup',cat:'Objects'}
];

export { N4_VOCAB };
