// N3_VOCAB — 120+ intermediate words
var N3_VOCAB = [
  // Feelings & personality
  {jp:'自慢',kana:'じまん',romaji:'jiman',en:'pride, boast',cat:'Personality',
   sentence:'彼は自分の自慢をよくする。',
   sentenceKana:'かれはじぶんのじまんをよくする。',
   sentenceEn:'He often boasts about himself.'},
  {jp:'自信',kana:'じしん',romaji:'jishin',en:'confidence, self-trust',cat:'Personality',
   sentence:'私は自分に自信がある。',
   sentenceKana:'わたしはじぶんにじしんがある。',
   sentenceEn:'I have confidence in myself.'},
  {jp:'不安',kana:'ふあん',romaji:'fuan',en:'anxiety, unease',cat:'Emotion',
   sentence:'将来（しょうらい）に不安を感じる。',
   sentenceKana:'しょうらいにふあんをかんじる。',
   sentenceEn:'I feel anxious about the future.'},
  {jp:'期待',kana:'きたい',romaji:'kitai',en:'expectation, hope',cat:'Emotion',
   sentence:'彼に期待している。',
   sentenceKana:'かれにきたいしている。',
   sentenceEn:'I have expectations for him.'},
  {jp:'感謝',kana:'かんしゃ',romaji:'kansha',en:'gratitude',cat:'Emotion',
   sentence:'両親に感謝している。',
   sentenceKana:'りょうしんにかんしゃしている。',
   sentenceEn:'I am grateful to my parents.'},
  {jp:'誇り',kana:'ほこり',romaji:'hokori',en:'pride',cat:'Emotion',
   sentence:'彼は家族を誇りに思っている。',
   sentenceKana:'かれはかぞくをほこりにおもっている。',
   sentenceEn:'He is proud of his family.'},
  {jp:'真剣',kana:'しんけん',romaji:'shinken',en:'seriousness',cat:'Personality',
   sentence:'真剣に考えてください。',
   sentenceKana:'しんけんにかんがえてください。',
   sentenceEn:'Please think seriously.'},
  {jp:'誠実',kana:'せいじつ',romaji:'seijitsu',en:'sincerity, honesty',cat:'Personality',
   sentence:'彼は誠実な人です。',
   sentenceKana:'かれはせいじつなひとです。',
   sentenceEn:'He is a sincere person.'},
  {jp:'積極的',kana:'せっきょくてき',romaji:'sekkyokuteki',en:'proactive, positive',cat:'Personality',
   sentence:'積極的に行動しましょう。',
   sentenceKana:'せっきょくてきにこうどうしましょう。',
   sentenceEn:'Let\'s act proactively.'},
  {jp:'消極的',kana:'しょうきょくてき',romaji:'shōkyokuteki',en:'passive, negative',cat:'Personality',
   sentence:'消極的な態度（たいど）を直す。',
   sentenceKana:'しょうきょくてきなたいどをなおす。',
   sentenceEn:'Correct a passive attitude.'},

  // Work & business
  {jp:'進む',kana:'すすむ',romaji:'susumu',en:'advance, make progress',cat:'Verb',
   sentence:'プロジェクトが進んでいる。',
   sentenceKana:'ぷろじぇくとがすすんでいる。',
   sentenceEn:'The project is progressing.'},
  {jp:'遅れる',kana:'おくれる',romaji:'okureru',en:'be late, fall behind',cat:'Verb',
   sentence:'電車が遅れています。',
   sentenceKana:'でんしゃがおくれています。',
   sentenceEn:'The train is late.'},
  {jp:'集める',kana:'あつめる',romaji:'atsumeru',en:'collect, gather',cat:'Verb',
   sentence:'情報（じょうほう）を集める。',
   sentenceKana:'じょうほうをあつめる。',
   sentenceEn:'Gather information.'},
  {jp:'広める',kana:'ひろめる',romaji:'hiromeru',en:'spread, propagate',cat:'Verb',
   sentence:'知識（ちしき）を広める。',
   sentenceKana:'ちしきをひろめる。',
   sentenceEn:'Spread knowledge.'},
  {jp:'支える',kana:'ささえる',romaji:'sasaeru',en:'support, sustain',cat:'Verb',
   sentence:'彼は家族を支えている。',
   sentenceKana:'かれはかぞくをささえている。',
   sentenceEn:'He supports his family.'},
  {jp:'維持する',kana:'いじする',romaji:'iji suru',en:'maintain, keep',cat:'Verb',
   sentence:'健康（けんこう）を維持する。',
   sentenceKana:'けんこうをいじする。',
   sentenceEn:'Maintain health.'},
  {jp:'担当',kana:'たんとう',romaji:'tantō',en:'person in charge',cat:'Work',
   sentence:'私は営業（えいぎょう）を担当しています。',
   sentenceKana:'わたしはえいぎょうをたんとうしています。',
   sentenceEn:'I am in charge of sales.'},
  {jp:'役割',kana:'やくわり',romaji:'yakuwari',en:'role, part',cat:'Work',
   sentence:'彼はチームのリーダー役割を果たす。',
   sentenceKana:'かれはちーむのりーだーやくわりをはたす。',
   sentenceEn:'He fulfills the role of team leader.'},
  {jp:'目標',kana:'もくひょう',romaji:'mokuhyō',en:'goal, target',cat:'Work',
   sentence:'今年の目標を設定する。',
   sentenceKana:'ことしのもくひょうをせっていする。',
   sentenceEn:'Set this year\'s goals.'},
  {jp:'成功',kana:'せいこう',romaji:'seikō',en:'success',cat:'Work',
   sentence:'ビジネスで成功する。',
   sentenceKana:'びじねすでせいこうする。',
   sentenceEn:'Succeed in business.'},
  {jp:'失敗',kana:'しっぱい',romaji:'shippai',en:'failure',cat:'Work',
   sentence:'失敗から学ぶことが大切です。',
   sentenceKana:'しっぱいからまなぶことがたいせつです。',
   sentenceEn:'It is important to learn from failure.'},

  // Social & community
  {jp:'交流',kana:'こうりゅう',romaji:'kōryū',en:'exchange, communication',cat:'Social',
   sentence:'留学生（りゅうがくせい）と交流する。',
   sentenceKana:'りゅうがくせいとこうりゅうする。',
   sentenceEn:'Interact with international students.'},
  {jp:'地域',kana:'ちいき',romaji:'chiiki',en:'region, community',cat:'Social',
   sentence:'地域社会（しゃかい）に貢献（こうけん）する。',
   sentenceKana:'ちいきしゃかいこうけんする。',
   sentenceEn:'Contribute to the local community.'},
  {jp:'協力',kana:'きょうりょく',romaji:'kyōryoku',en:'cooperation',cat:'Social',
   sentence:'みんなで協力しましょう。',
   sentenceKana:'みんなできょうりょくしましょう。',
   sentenceEn:'Let\'s cooperate together.'},
  {jp:'支援',kana:'しえん',romaji:'shien',en:'support, aid',cat:'Social',
   sentence:'被災地（ひさいち）を支援する。',
   sentenceKana:'ひさいちをしえんする。',
   sentenceEn:'Support the disaster area.'},
  {jp:'意識',kana:'いしき',romaji:'ishiki',en:'consciousness, awareness',cat:'Social',
   sentence:'環境（かんきょう）意識が高まっている。',
   sentenceKana:'かんきょういしきがたかまっている。',
   sentenceEn:'Environmental awareness is rising.'},

  // Health & lifestyle
  {jp:'健康',kana:'けんこう',romaji:'kenkō',en:'health',cat:'Health',
   sentence:'健康が一番大切です。',
   sentenceKana:'けんこうがいちばんたいせつです。',
   sentenceEn:'Health is most important.'},
  {jp:'生活',kana:'せいかつ',romaji:'seikatsu',en:'daily life, livelihood',cat:'Lifestyle',
   sentence:'生活リズムを整える。',
   sentenceKana:'せいかつりずむをととのえる。',
   sentenceEn:'Organize your daily rhythm.'},
  {jp:'習慣',kana:'しゅうかん',romaji:'shūkan',en:'habit, custom',cat:'Lifestyle',
   sentence:'早起き（はやおき）の習慣がある。',
   sentenceKana:'はやおきのしゅうかんがある。',
   sentenceEn:'I have a habit of waking up early.'},
  {jp:'ストレス',kana:'すとれす',romaji:'sutoresu',en:'stress',cat:'Health',
   sentence:'ストレスをためないようにする。',
   sentenceKana:'すとれすをためないようにする。',
   sentenceEn:'Try not to accumulate stress.'},
  {jp:'リラックス',kana:'りらっくす',romaji:'rirakkusu',en:'relax',cat:'Health',
   sentence:'音楽を聴いてリラックスする。',
   sentenceKana:'おんがくをきいてりらっくすする。',
   sentenceEn:'Relax by listening to music.'},

  // Shopping & consumption
  {jp:'購入',kana:'こうにゅう',romaji:'kōnyū',en:'purchase',cat:'Shopping',
   sentence:'オンラインで購入する。',
   sentenceKana:'おんらいんでこうにゅうする。',
   sentenceEn:'Make a purchase online.'},
  {jp:'消費',kana:'しょうひ',romaji:'shōhi',en:'consumption',cat:'Shopping',
   sentence:'消費税（しょうひぜい）が上がった。',
   sentenceKana:'しょうひぜいがあがった。',
   sentenceEn:'Consumption tax increased.'},
  {jp:'値段',kana:'ねだん',romaji:'nedan',en:'price, cost',cat:'Shopping',
   sentence:'この値段は高い。',
   sentenceKana:'このねだんはたかい。',
   sentenceEn:'This price is expensive.'},
  {jp:'試着',kana:'しちゃく',romaji:'shichaku',en:'fitting (clothes)',cat:'Shopping',
   sentence:'試着室（しちゃくしつ）はどこですか。',
   sentenceKana:'しちゃくしつはどこですか。',
   sentenceEn:'Where is the fitting room?'},
  {jp:'割引',kana:'わりびき',romaji:'waribiki',en:'discount',cat:'Shopping',
   sentence:'割引券（けん）を使う。',
   sentenceKana:'わりびきけんをつかう。',
   sentenceEn:'Use a discount coupon.'},

  // Travel & transport
  {jp:'旅行',kana:'りょこう',romaji:'ryokō',en:'travel, trip',cat:'Travel',
   sentence:'海外旅行（かいがいりょこう）に行く。',
   sentenceKana:'かいがいりょこうにいく。',
   sentenceEn:'Go on an overseas trip.'},
  {jp:'観光',kana:'かんこう',romaji:'kankō',en:'sightseeing',cat:'Travel',
   sentence:'観光地（かんこうち）を巡る（めぐる）。',
   sentenceKana:'かんこうちをめぐる。',
   sentenceEn:'Visit tourist spots.'},
  {jp:'予約',kana:'よやく',romaji:'yoyaku',en:'reservation',cat:'Travel',
   sentence:'ホテルを予約する。',
   sentenceKana:'ほてるをよやくする。',
   sentenceEn:'Make a hotel reservation.'},
  {jp:'出発',kana:'しゅっぱつ',romaji:'shuppatsu',en:'departure',cat:'Travel',
   sentence:'明日出発します。',
   sentenceKana:'あしたしゅっぱつします。',
   sentenceEn:'Depart tomorrow.'},
  {jp:'到着',kana:'とうちゃく',romaji:'tōchaku',en:'arrival',cat:'Travel',
   sentence:'到着時間は何時ですか。',
   sentenceKana:'とうちゃくじかんはなんじですか。',
   sentenceEn:'What is the arrival time?'},

  // Technology & media
  {jp:'情報',kana:'じょうほう',romaji:'jōhō',en:'information',cat:'Tech',
   sentence:'最新情報（さいしんじょうほう）をチェックする。',
   sentenceKana:'さいしんじょうほうをちぇっくする。',
   sentenceEn:'Check the latest information.'},
  {jp:'データ',kana:'でーた',romaji:'dēta',en:'data',cat:'Tech',
   sentence:'データを分析（ぶんせき）する。',
   sentenceKana:'でーたをぶんせきする。',
   sentenceEn:'Analyze data.'},
  {jp:'ネット',kana:'ねっと',romaji:'netto',en:'internet, net',cat:'Tech',
   sentence:'ネットで調べる。',
   sentenceKana:'ねっとでしらべる。',
   sentenceEn:'Look it up on the internet.'},
  {jp:'メール',kana:'めーる',romaji:'mēru',en:'email',cat:'Tech',
   sentence:'メールを送る（おくる）。',
   sentenceKana:'めーるをおくる。',
   sentenceEn:'Send an email.'},
  {jp:'電話',kana:'でんわ',romaji:'denwa',en:'telephone, phone call',cat:'Tech',
   sentence:'電話をかける。',
   sentenceKana:'でんわをかける。',
   sentenceEn:'Make a phone call.'},

  // Environment
  {jp:'環境',kana:'かんきょう',romaji:'kankyō',en:'environment',cat:'Environment',
   sentence:'環境問題（もんだい）に関心がある。',
   sentenceKana:'かんきょうもんだいにかんしんがある。',
   sentenceEn:'I am concerned about environmental issues.'},
  {jp:'自然',kana:'しぜん',romaji:'shizen',en:'nature',cat:'Environment',
   sentence:'自然を大切にする。',
   sentenceKana:'しぜんをたいせつにする。',
   sentenceEn:'Cherish nature.'},
  {jp:'資源',kana:'しげん',romaji:'shigen',en:'resources',cat:'Environment',
   sentence:'資源を節約（せつやく）する。',
   sentenceKana:'しげんをせつやくする。',
   sentenceEn:'Save resources.'},
  {jp:'汚染',kana:'おせん',romaji:'osen',en:'pollution',cat:'Environment',
   sentence:'水質汚染（すいしつおせん）が問題だ。',
   sentenceKana:'すいしつおせんがもんだいだ。',
   sentenceEn:'Water pollution is a problem.'},
  {jp:'リサイクル',kana:'りさいくる',romaji:'risaikuru',en:'recycling',cat:'Environment',
   sentence:'リサイクルに協力する。',
   sentenceKana:'りさいくるにきょうりょくする。',
   sentenceEn:'Cooperate with recycling.'},

  // Education & learning
  {jp:'勉強',kana:'べんきょう',romaji:'benkyō',en:'study',cat:'Education',
   sentence:'毎日勉強することが大切だ。',
   sentenceKana:'まいにちべんきょうすることがたいせつだ。',
   sentenceEn:'It is important to study every day.'},
  {jp:'試験',kana:'しけん',romaji:'shiken',en:'examination, test',cat:'Education',
   sentence:'試験に合格（ごうかく）する。',
   sentenceKana:'しけんにごうかくする。',
   sentenceEn:'Pass the exam.'},
  {jp:'授業',kana:'じゅぎょう',romaji:'jugyō',en:'class, lesson',cat:'Education',
   sentence:'授業に出席（しゅっせき）する。',
   sentenceKana:'じゅぎょうにしゅっせきする。',
   sentenceEn:'Attend class.'},
  {jp:'予習',kana:'よしゅう',romaji:'yoshū',en:'preview, preparation',cat:'Education',
   sentence:'授業の予習をする。',
   sentenceKana:'じゅぎょうのよしゅうをする。',
   sentenceEn:'Prepare for class.'},
  {jp:'復習',kana:'ふくしゅう',romaji:'fukushū',en:'review, revision',cat:'Education',
   sentence:'定期（ていき）復習が効果的（こうかてき）だ。',
   sentenceKana:'ていきふくしゅうがこうかてきだ。',
   sentenceEn:'Regular review is effective.'},

  // Relationships
  {jp:'関係',kana:'かんけい',romaji:'kankei',en:'relationship, relation',cat:'Relationships',
   sentence:'彼とはいい関係を保っている。',
   sentenceKana:'かれとはいいかんけいをたもっている。',
   sentenceEn:'I maintain a good relationship with him.'},
  {jp:'信頼',kana:'しんらい',romaji:'shinrai',en:'trust, reliance',cat:'Relationships',
   sentence:'友だちを信頼している。',
   sentenceKana:'ともだちをしんらいしている。',
   sentenceEn:'I trust my friend.'},
  {jp:'理解',kana:'りかい',romaji:'rikai',en:'understanding, comprehension',cat:'Relationships',
   sentence:'彼の気持ちを理解する。',
   sentenceKana:'かれのきもちをりかいする。',
   sentenceEn:'Understand his feelings.'},
  {jp:'助け合い',kana:'たすけあい',romaji:'tasukeai',en:'mutual help',cat:'Relationships',
   sentence:'助け合いの精神（せいしん）が大切だ。',
   sentenceKana:'たすけあいのせいしんがたいせつだ。',
   sentenceEn:'The spirit of mutual help is important.'},
  {jp:'仲間',kana:'なかま',romaji:'nakama',en:'fellow, companion',cat:'Relationships',
   sentence:'仲間と一緒に頑張る。',
   sentenceKana:'なかまといっしょにがんばる。',
   sentenceEn:'Work hard together with companions.'},

  // Time & schedule
  {jp:'スケジュール',kana:'すけじゅーる',romaji:'sukejūru',en:'schedule',cat:'Time',
   sentence:'スケジュールを確認（かくにん）する。',
   sentenceKana:'すけじゅーるをかくにんする。',
   sentenceEn:'Check the schedule.'},
  {jp:'締切',kana:'しめきり',romaji:'shimekiri',en:'deadline',cat:'Time',
   sentence:'締切に間に合うようにする。',
   sentenceKana:'しめきりにまにあうようにする。',
   sentenceEn:'Make sure to meet the deadline.'},
  {jp:'期限',kana:'きげん',romaji:'kigen',en:'time limit, term',cat:'Time',
   sentence:'期限を守る。',
   sentenceKana:'きげんをまもる。',
   sentenceEn:'Keep the deadline.'},
  {jp:'延期',kana:'えんき',romaji:'enki',en:'postponement',cat:'Time',
   sentence:'会議が延期された。',
   sentenceKana:'かいぎがえんきされた。',
   sentenceEn:'The meeting was postponed.'},
  {jp:'前倒し',kana:'まえだおし',romaji:'maedaoshi',en:'moving up (time)',cat:'Time',
   sentence:'プロジェクトを前倒しで進める。',
   sentenceKana:'ぷろじぇくとをまえだおしですすめる。',
   sentenceEn:'Move the project forward ahead of schedule.'},

  // Financial
  {jp:'予算',kana:'よさん',romaji:'yosan',en:'budget',cat:'Finance',
   sentence:'予算内（よさんない）で収める。',
   sentenceKana:'よさんないでおさめる。',
   sentenceEn:'Keep within the budget.'},
  {jp:'経費',kana:'けいひ',romaji:'keihi',en:'expenses, cost',cat:'Finance',
   sentence:'経費を削減（さくげん）する。',
   sentenceKana:'けいひをさくげんする。',
   sentenceEn:'Reduce expenses.'},
  {jp:'収入',kana:'しゅうにゅう',romaji:'shūnyū',en:'income, revenue',cat:'Finance',
   sentence:'収入が安定（あんてい）している。',
   sentenceKana:'しゅうにゅうがあんていしている。',
   sentenceEn:'Income is stable.'},
  {jp:'貯金',kana:'ちょきん',romaji:'chokin',en:'savings',cat:'Finance',
   sentence:'毎月貯金する。',
   sentenceKana:'まいつきちょきんする。',
   sentenceEn:'Save money every month.'},
  {jp:'投資',kana:'とうし',romaji:'tōshi',en:'investment',cat:'Finance',
   sentence:'株式（かぶしき）に投資する。',
   sentenceKana:'かぶしきにとうしする。',
   sentenceEn:'Invest in stocks.'},

  // Food & cooking
  {jp:'食材',kana:'しょくざい',romaji:'shokuzai',en:'ingredients',cat:'Food',
   sentence:'新鮮（しんせん）な食材を使う。',
   sentenceKana:'しんせんなしょくざいをつかう。',
   sentenceEn:'Use fresh ingredients.'},
  {jp:'レシピ',kana:'れしぴ',romaji:'reshipi',en:'recipe',cat:'Food',
   sentence:'新しいレシピを試す。',
   sentenceKana:'あたらしいれしぴをためす。',
   sentenceEn:'Try a new recipe.'},
  {jp:'味わい',kana:'あじわい',romaji:'ajiwai',en:'taste, savor',cat:'Food',
   sentence:'この料理は深い味わいがある。',
   sentenceKana:'このりょうりはふかいあじわいがある。',
   sentenceEn:'This dish has a deep flavor.'},
  {jp:'調理',kana:'ちょうり',romaji:'chōri',en:'cooking, preparation',cat:'Food',
   sentence:'調理方法（ほうほう）を学ぶ。',
   sentenceKana:'ちょうりほうほうをまなぶ。',
   sentenceEn:'Learn cooking methods.'},
  {jp:'栄養',kana:'えいよう',romaji:'eiyō',en:'nutrition',cat:'Food',
   sentence:'栄養バランスを考える。',
   sentenceKana:'えいようばらんすをかんがえる。',
   sentenceEn:'Think about nutritional balance.'},

  // Culture & society
  {jp:'伝統',kana:'でんとう',romaji:'dentō',en:'tradition',cat:'Culture',
   sentence:'伝統文化（ぶんか）を守る。',
   sentenceKana:'でんとうぶんかをまもる。',
   sentenceEn:'Protect traditional culture.'},
  {jp:'文化',kana:'ぶんか',romaji:'bunka',en:'culture',cat:'Culture',
   sentence:'異文化（いぶんか）に触れる。',
   sentenceKana:'いぶんかにふれる。',
   sentenceEn:'Experience different cultures.'},
  {jp:'芸術',kana:'げいじゅつ',romaji:'geijutsu',en:'art',cat:'Culture',
   sentence:'芸術を鑑賞（かんしょう）する。',
   sentenceKana:'げいじゅつをかんしょうする。',
   sentenceEn:'Appreciate art.'},
  {jp:'祭り',kana:'まつり',romaji:'matsuri',en:'festival',cat:'Culture',
   sentence:'夏祭りに行く。',
   sentenceKana:'なつまつりにいく。',
   sentenceEn:'Go to the summer festival.'},
  {jp:'習慣',kana:'しゅうかん',romaji:'shūkan',en:'custom, habit',cat:'Culture',
   sentence:'日本の習慣に慣れる。',
   sentenceKana:'にほんのしゅうかんになれる。',
   sentenceEn:'Get used to Japanese customs.'},

  // Transportation
  {jp:'交通',kana:'こうつう',romaji:'kōtsū',en:'traffic, transportation',cat:'Transport',
   sentence:'交通ルールを守る。',
   sentenceKana:'こうつうるーるをまもる。',
   sentenceEn:'Obey traffic rules.'},
  {jp:'渋滞',kana:'じゅうたい',romaji:'jūtai',en:'traffic jam',cat:'Transport',
   sentence:'渋滞に巻き込まれた。',
   sentenceKana:'じゅうたいにまきこまれた。',
   sentenceEn:'I got caught in a traffic jam.'},
  {jp:'乗り換え',kana:'のりかえ',romaji:'norikae',en:'transfer (train)',cat:'Transport',
   sentence:'次の駅で乗り換える。',
   sentenceKana:'つぎのえきでのりかえる。',
   sentenceEn:'Transfer at the next station.'},
  {jp:'出発',kana:'しゅっぱつ',romaji:'shuppatsu',en:'departure',cat:'Transport',
   sentence:'出発時間は午前7時です。',
   sentenceKana:'しゅっぱつじかんはごぜんしちじです。',
   sentenceEn:'Departure time is 7 a.m.'},
  {jp:'到着',kana:'とうちゃく',romaji:'tōchaku',en:'arrival',cat:'Transport',
   sentence:'到着が遅れています。',
   sentenceKana:'とうちゃくがおくれています。',
   sentenceEn:'Arrival is delayed.'},

  // Home & living
  {jp:'賃貸',kana:'ちんたい',romaji:'chintai',en:'rental (property)',cat:'Housing',
   sentence:'賃貸アパートに住んでいる。',
   sentenceKana:'ちんたいあぱーとにすんでいる。',
   sentenceEn:'I live in a rental apartment.'},
  {jp:'引っ越し',kana:'ひっこし',romaji:'hikkoshi',en:'moving (house)',cat:'Housing',
   sentence:'来月引っ越しする。',
   sentenceKana:'らいげつひっこしする。',
   sentenceEn:'I will move next month.'},
  {jp:'隣',kana:'となり',romaji:'tonari',en:'neighbor, next door',cat:'Housing',
   sentence:'隣の家に引っ越してきた。',
   sentenceKana:'となりのいえにひっこしてきた。',
   sentenceEn:'A new neighbor moved in next door.'},
  {jp:'近所',kana:'きんじょ',romaji:'kinjo',en:'neighborhood',cat:'Housing',
   sentence:'近所にスーパーがある。',
   sentenceKana:'きんじょにすーぱーがある。',
   sentenceEn:'There is a supermarket in the neighborhood.'},
  {jp:'修理',kana:'しゅうり',romaji:'shūri',en:'repair, fixing',cat:'Housing',
   sentence:'水道（すいどう）の修理を頼む。',
   sentenceKana:'すいどうのしゅうりをたのむ。',
   sentenceEn:'Ask for a plumbing repair.'},

  // Health & body
  {jp:'体調',kana:'たいちょう',romaji:'taichō',en:'physical condition',cat:'Health',
   sentence:'体調が悪いので休む。',
   sentenceKana:'たいちょうがわるいのでやすむ。',
   sentenceEn:'I rest because I don\'t feel well.'},
  {jp:'症状',kana:'しょうじょう',romaji:'shōjō',en:'symptom',cat:'Health',
   sentence:'風邪（かぜ）の症状が出ている。',
   sentenceKana:'かぜのしょうじょうがでている。',
   sentenceEn:'I have cold symptoms.'},
  {jp:'治療',kana:'ちりょう',romaji:'chiryō',en:'medical treatment',cat:'Health',
   sentence:'治療を受ける。',
   sentenceKana:'ちりょうをうける。',
   sentenceEn:'Receive medical treatment.'},
  {jp:'予防',kana:'よぼう',romaji:'yobō',en:'prevention',cat:'Health',
   sentence:'病気（びょうき）を予防する。',
   sentenceKana:'びょうきをよぼうする。',
   sentenceEn:'Prevent diseases.'},
  {jp:'健康診断',kana:'けんこうしんだん',romaji:'kenkō shindan',en:'health check',cat:'Health',
   sentence:'健康診断を受ける。',
   sentenceKana:'けんこうしんだんをうける。',
   sentenceEn:'Have a health check.'},

  // Work environment
  {jp:'職場',kana:'しょくば',romaji:'shokuba',en:'workplace',cat:'Work',
   sentence:'職場の環境が良い。',
   sentenceKana:'しょくばのかんきょうがよい。',
   sentenceEn:'The workplace environment is good.'},
  {jp:'同僚',kana:'どうりょう',romaji:'dōryō',en:'colleague, coworker',cat:'Work',
   sentence:'同僚と仲良くする。',
   sentenceKana:'どうりょうとなかよくする。',
   sentenceEn:'Get along with colleagues.'},
  {jp:'上司',kana:'じょうし',romaji:'jōshi',en:'boss, supervisor',cat:'Work',
   sentence:'上司に報告（ほうこく）する。',
   sentenceKana:'じょうしにほうこくする。',
   sentenceEn:'Report to the boss.'},
  {jp:'部下',kana:'ぶか',romaji:'buka',en:'subordinate',cat:'Work',
   sentence:'部下を指導（しどう）する。',
   sentenceKana:'ぶかをしどうする。',
   sentenceEn:'Guide subordinates.'},
  {jp:'会議',kana:'かいぎ',romaji:'kaigi',en:'meeting',cat:'Work',
   sentence:'会議に参加（さんか）する。',
   sentenceKana:'かいぎにさんかする。',
   sentenceEn:'Participate in the meeting.'},
];

export { N3_VOCAB };