// JLPT N5 core kanji. on = on'yomi, kun = kun'yomi, ex = example word (reading) meaning
var N5_KANJI = [
  // Numbers & money
  {c:'一',on:'イチ',kun:'ひと(つ)',mean:'one',ex:'一つ (ひとつ) one thing'},
  {c:'二',on:'ニ',kun:'ふた(つ)',mean:'two',ex:'二つ (ふたつ) two things'},
  {c:'三',on:'サン',kun:'みっ(つ)',mean:'three',ex:'三つ (みっつ) three things'},
  {c:'四',on:'シ',kun:'よん・よ(っつ)',mean:'four',ex:'四つ (よっつ) four things'},
  {c:'五',on:'ゴ',kun:'いつ(つ)',mean:'five',ex:'五つ (いつつ) five things'},
  {c:'六',on:'ロク',kun:'むっ(つ)',mean:'six',ex:'六つ (むっつ) six things'},
  {c:'七',on:'シチ',kun:'なな(つ)',mean:'seven',ex:'七つ (ななつ) seven things'},
  {c:'八',on:'ハチ',kun:'やっ(つ)',mean:'eight',ex:'八つ (やっつ) eight things'},
  {c:'九',on:'キュウ・ク',kun:'ここの(つ)',mean:'nine',ex:'九つ (ここのつ) nine things'},
  {c:'十',on:'ジュウ',kun:'とお',mean:'ten',ex:'十 (じゅう) ten'},
  {c:'百',on:'ヒャク',kun:'—',mean:'hundred',ex:'百 (ひゃく) hundred'},
  {c:'千',on:'セン',kun:'ち',mean:'thousand',ex:'千 (せん) thousand'},
  {c:'万',on:'マン・バン',kun:'—',mean:'ten thousand',ex:'一万 (いちまん) 10,000'},
  {c:'円',on:'エン',kun:'まる(い)',mean:'yen, circle',ex:'百円 (ひゃくえん) 100 yen'},
  // Days, time, calendar
  {c:'日',on:'ニチ・ジツ',kun:'ひ・か',mean:'day, sun',ex:'日曜日 (にちようび) Sunday'},
  {c:'月',on:'ゲツ・ガツ',kun:'つき',mean:'month, moon',ex:'月曜日 (げつようび) Monday'},
  {c:'火',on:'カ',kun:'ひ',mean:'fire',ex:'火曜日 (かようび) Tuesday'},
  {c:'水',on:'スイ',kun:'みず',mean:'water',ex:'水曜日 (すいようび) Wednesday'},
  {c:'木',on:'モク・ボク',kun:'き',mean:'tree, wood',ex:'木曜日 (もくようび) Thursday'},
  {c:'金',on:'キン・コン',kun:'かね',mean:'gold, money',ex:'金曜日 (きんようび) Friday'},
  {c:'土',on:'ド・ト',kun:'つち',mean:'earth, soil',ex:'土曜日 (どようび) Saturday'},
  {c:'年',on:'ネン',kun:'とし',mean:'year',ex:'今年 (ことし) this year'},
  {c:'時',on:'ジ',kun:'とき',mean:'time, hour',ex:'時間 (じかん) time'},
  {c:'間',on:'カン・ケン',kun:'あいだ',mean:'interval, between',ex:'時間 (じかん) time'},
  {c:'分',on:'フン・ブン',kun:'わ(かる)',mean:'minute, part',ex:'五分 (ごふん) five minutes'},
  {c:'半',on:'ハン',kun:'なか(ば)',mean:'half',ex:'半分 (はんぶん) half'},
  {c:'今',on:'コン・キン',kun:'いま',mean:'now',ex:'今日 (きょう) today'},
  {c:'毎',on:'マイ',kun:'—',mean:'every',ex:'毎日 (まいにち) every day'},
  {c:'午',on:'ゴ',kun:'—',mean:'noon',ex:'午前 (ごぜん) morning, a.m.'},
  // Position & direction
  {c:'上',on:'ジョウ',kun:'うえ・あ(がる)',mean:'up, above',ex:'上 (うえ) above'},
  {c:'下',on:'カ・ゲ',kun:'した・さ(がる)',mean:'down, below',ex:'下 (した) below'},
  {c:'中',on:'チュウ',kun:'なか',mean:'middle, inside',ex:'中 (なか) inside'},
  {c:'外',on:'ガイ',kun:'そと',mean:'outside',ex:'外 (そと) outside'},
  {c:'前',on:'ゼン',kun:'まえ',mean:'before, front',ex:'前 (まえ) front'},
  {c:'後',on:'ゴ・コウ',kun:'あと・うし(ろ)',mean:'after, behind',ex:'午後 (ごご) afternoon'},
  {c:'左',on:'サ',kun:'ひだり',mean:'left',ex:'左 (ひだり) left'},
  {c:'右',on:'ウ・ユウ',kun:'みぎ',mean:'right',ex:'右 (みぎ) right'},
  {c:'東',on:'トウ',kun:'ひがし',mean:'east',ex:'東 (ひがし) east'},
  {c:'西',on:'セイ・サイ',kun:'にし',mean:'west',ex:'西 (にし) west'},
  {c:'南',on:'ナン',kun:'みなみ',mean:'south',ex:'南 (みなみ) south'},
  {c:'北',on:'ホク',kun:'きた',mean:'north',ex:'北 (きた) north'},
  // People & family
  {c:'人',on:'ジン・ニン',kun:'ひと',mean:'person',ex:'日本人 (にほんじん) Japanese person'},
  {c:'男',on:'ダン・ナン',kun:'おとこ',mean:'man, male',ex:'男の人 (おとこのひと) man'},
  {c:'女',on:'ジョ',kun:'おんな',mean:'woman, female',ex:'女の人 (おんなのひと) woman'},
  {c:'子',on:'シ',kun:'こ',mean:'child',ex:'子ども (こども) child'},
  {c:'父',on:'フ',kun:'ちち',mean:'father',ex:'父 (ちち) my father'},
  {c:'母',on:'ボ',kun:'はは',mean:'mother',ex:'母 (はは) my mother'},
  {c:'友',on:'ユウ',kun:'とも',mean:'friend',ex:'友だち (ともだち) friend'},
  {c:'先',on:'セン',kun:'さき',mean:'previous, ahead',ex:'先生 (せんせい) teacher'},
  {c:'生',on:'セイ・ショウ',kun:'う(まれる)・い(きる)',mean:'life, birth',ex:'学生 (がくせい) student'},
  {c:'名',on:'メイ・ミョウ',kun:'な',mean:'name',ex:'名前 (なまえ) name'},
  // Nature
  {c:'山',on:'サン',kun:'やま',mean:'mountain',ex:'山 (やま) mountain'},
  {c:'川',on:'セン',kun:'かわ',mean:'river',ex:'川 (かわ) river'},
  {c:'天',on:'テン',kun:'—',mean:'heaven, sky',ex:'天気 (てんき) weather'},
  {c:'気',on:'キ・ケ',kun:'—',mean:'spirit, air',ex:'元気 (げんき) healthy, energetic'},
  {c:'雨',on:'ウ',kun:'あめ',mean:'rain',ex:'雨 (あめ) rain'},
  {c:'田',on:'デン',kun:'た',mean:'rice field',ex:'田んぼ (たんぼ) rice paddy'},
  // School, language & verbs
  {c:'学',on:'ガク',kun:'まな(ぶ)',mean:'study, learning',ex:'学校 (がっこう) school'},
  {c:'校',on:'コウ',kun:'—',mean:'school',ex:'学校 (がっこう) school'},
  {c:'本',on:'ホン',kun:'もと',mean:'book, origin',ex:'本 (ほん) book'},
  {c:'語',on:'ゴ',kun:'かた(る)',mean:'language, word',ex:'日本語 (にほんご) Japanese language'},
  {c:'話',on:'ワ',kun:'はな(す)・はなし',mean:'talk, story',ex:'電話 (でんわ) telephone'},
  {c:'読',on:'ドク',kun:'よ(む)',mean:'read',ex:'読む (よむ) to read'},
  {c:'書',on:'ショ',kun:'か(く)',mean:'write',ex:'書く (かく) to write'},
  {c:'聞',on:'ブン・モン',kun:'き(く)',mean:'hear, listen',ex:'聞く (きく) to listen'},
  {c:'見',on:'ケン',kun:'み(る)',mean:'see, look',ex:'見る (みる) to see'},
  {c:'食',on:'ショク',kun:'た(べる)',mean:'eat',ex:'食べる (たべる) to eat'},
  {c:'飲',on:'イン',kun:'の(む)',mean:'drink',ex:'飲む (のむ) to drink'},
  {c:'行',on:'コウ・ギョウ',kun:'い(く)',mean:'go',ex:'行く (いく) to go'},
  {c:'来',on:'ライ',kun:'く(る)',mean:'come',ex:'来る (くる) to come'},
  {c:'出',on:'シュツ',kun:'で(る)・だ(す)',mean:'exit, leave',ex:'出る (でる) to go out'},
  {c:'入',on:'ニュウ',kun:'はい(る)・い(れる)',mean:'enter',ex:'入る (はいる) to enter'},
  {c:'休',on:'キュウ',kun:'やす(む)',mean:'rest',ex:'休む (やすむ) to rest'},
  // Adjectives & qualities
  {c:'大',on:'ダイ・タイ',kun:'おお(きい)',mean:'big',ex:'大きい (おおきい) big'},
  {c:'小',on:'ショウ',kun:'ちい(さい)・こ',mean:'small',ex:'小さい (ちいさい) small'},
  {c:'高',on:'コウ',kun:'たか(い)',mean:'tall, expensive',ex:'高い (たかい) expensive, tall'},
  {c:'安',on:'アン',kun:'やす(い)',mean:'cheap, safe',ex:'安い (やすい) cheap'},
  {c:'新',on:'シン',kun:'あたら(しい)',mean:'new',ex:'新しい (あたらしい) new'},
  {c:'古',on:'コ',kun:'ふる(い)',mean:'old',ex:'古い (ふるい) old'},
  {c:'長',on:'チョウ',kun:'なが(い)',mean:'long, chief',ex:'長い (ながい) long'},
  {c:'白',on:'ハク',kun:'しろ(い)',mean:'white',ex:'白い (しろい) white'},
  // Common
  {c:'国',on:'コク',kun:'くに',mean:'country',ex:'外国 (がいこく) foreign country'},
  {c:'何',on:'カ',kun:'なに・なん',mean:'what',ex:'何 (なに) what'},
  {c:'車',on:'シャ',kun:'くるま',mean:'car, vehicle',ex:'車 (くるま) car'},
  {c:'電',on:'デン',kun:'—',mean:'electricity',ex:'電車 (でんしゃ) train'},
  {c:'口',on:'コウ・ク',kun:'くち',mean:'mouth',ex:'口 (くち) mouth'},
  // Body
  {c:'手',on:'シュ',kun:'て',mean:'hand',ex:'手 (て) hand'},
  {c:'足',on:'ソク',kun:'あし・た(りる)',mean:'foot, leg',ex:'足 (あし) foot/leg'},
  {c:'目',on:'モク',kun:'め',mean:'eye',ex:'目 (め) eye'},
  {c:'耳',on:'ジ',kun:'みみ',mean:'ear',ex:'耳 (みみ) ear'},
  // Actions & qualities
  {c:'立',on:'リツ',kun:'た(つ)',mean:'stand',ex:'立つ (たつ) to stand'},
  {c:'力',on:'リョク・リキ',kun:'ちから',mean:'power, strength',ex:'力 (ちから) strength'},
  {c:'早',on:'ソウ',kun:'はや(い)',mean:'early, fast',ex:'早い (はやい) early'},
  {c:'多',on:'タ',kun:'おお(い)',mean:'many, much',ex:'多い (おおい) many'},
  {c:'少',on:'ショウ',kun:'すく(ない)・すこ(し)',mean:'few, little',ex:'少し (すこし) a little'},
  // Things & places
  {c:'字',on:'ジ',kun:'—',mean:'character, letter',ex:'漢字 (かんじ) kanji'},
  {c:'花',on:'カ',kun:'はな',mean:'flower',ex:'花 (はな) flower'},
  {c:'空',on:'クウ',kun:'そら・あ(く)',mean:'sky, empty',ex:'空 (そら) sky'},
  {c:'魚',on:'ギョ',kun:'さかな・うお',mean:'fish',ex:'魚 (さかな) fish'},
  {c:'店',on:'テン',kun:'みせ',mean:'shop, store',ex:'店 (みせ) shop'},
  {c:'買',on:'バイ',kun:'か(う)',mean:'buy',ex:'買う (かう) to buy'},
  {c:'駅',on:'エキ',kun:'—',mean:'station',ex:'駅 (えき) station'},
  {c:'道',on:'ドウ',kun:'みち',mean:'road, way',ex:'道 (みち) road, street'}
];

export { N5_KANJI };
