var N5_VOCAB = [
  {jp:'おはようございます',kana:'おはようございます',romaji:'ohayō gozaimasu',en:'good morning (polite)',cat:'Greetings',sentence:'おはようございます。',sentenceKana:'おはようございます。',sentenceEn:'Good morning.'},
  {jp:'こんにちは',kana:'こんにちは',romaji:'konnichiwa',en:'hello, good afternoon',cat:'Greetings',sentence:'こんにちは。',sentenceKana:'こんにちは。',sentenceEn:'Hello.'},
  {jp:'こんばんは',kana:'こんばんは',romaji:'konbanwa',en:'good evening',cat:'Greetings',sentence:'こんばんは。',sentenceKana:'こんばんは。',sentenceEn:'Good evening.'},
  {jp:'おやすみなさい',kana:'おやすみなさい',romaji:'oyasuminasai',en:'good night',cat:'Greetings',sentence:'おやすみなさい。',sentenceKana:'おやすみなさい。',sentenceEn:'Good night.'},
  {jp:'さようなら',kana:'さようなら',romaji:'sayōnara',en:'goodbye',cat:'Greetings',sentence:'さようなら。',sentenceKana:'さようなら。',sentenceEn:'Goodbye.'},
  {jp:'ありがとうございます',kana:'ありがとうございます',romaji:'arigatō gozaimasu',en:'thank you (polite)',cat:'Greetings',sentence:'ありがとうございます。',sentenceKana:'ありがとうございます。',sentenceEn:'Thank you.'},
  {jp:'すみません',kana:'すみません',romaji:'sumimasen',en:'excuse me, sorry',cat:'Greetings',sentence:'すみません。',sentenceKana:'すみません。',sentenceEn:'Excuse me.'},
  {jp:'ごめんなさい',kana:'ごめんなさい',romaji:'gomennasai',en:'I\'m sorry',cat:'Greetings',sentence:'ごめんなさい。',sentenceKana:'ごめんなさい。',sentenceEn:'I\'m sorry.'},
  {jp:'はじめまして',kana:'はじめまして',romaji:'hajimemashite',en:'nice to meet you',cat:'Greetings',sentence:'はじめまして。',sentenceKana:'はじめまして。',sentenceEn:'Nice to meet you.'},
  {jp:'どうぞよろしく',kana:'どうぞよろしく',romaji:'dōzo yoroshiku',en:'pleased to meet you',cat:'Greetings',sentence:'どうぞよろしく。',sentenceKana:'どうぞよろしく。',sentenceEn:'Pleased to meet you.'},
  {jp:'いってきます',kana:'いってきます',romaji:'ittekimasu',en:'I\'m leaving (going out)',cat:'Greetings',sentence:'いってきます。',sentenceKana:'いってきます。',sentenceEn:'I\'m leaving.'},
  {jp:'いってらっしゃい',kana:'いってらっしゃい',romaji:'itterasshai',en:'see you, take care',cat:'Greetings',sentence:'いってらっしゃい。',sentenceKana:'いってらっしゃい。',sentenceEn:'See you.'},
  {jp:'ただいま',kana:'ただいま',romaji:'tadaima',en:'I\'m home',cat:'Greetings',sentence:'ただいま。',sentenceKana:'ただいま。',sentenceEn:'I\'m home.'},
  {jp:'おかえりなさい',kana:'おかえりなさい',romaji:'okaerinasai',en:'welcome back',cat:'Greetings',sentence:'おかえりなさい。',sentenceKana:'おかえりなさい。',sentenceEn:'Welcome back.'},
  {jp:'いただきます',kana:'いただきます',romaji:'itadakimasu',en:'said before eating',cat:'Greetings',sentence:'いただきます。',sentenceKana:'いただきます。',sentenceEn:'I will receive (said before eating).'},
  {jp:'ごちそうさま',kana:'ごちそうさま',romaji:'gochisōsama',en:'said after eating',cat:'Greetings',sentence:'ごちそうさま。',sentenceKana:'ごちそうさま。',sentenceEn:'Thank you for the meal.'},
  {jp:'お願いします',kana:'おねがいします',romaji:'onegai shimasu',en:'please (request)',cat:'Greetings',sentence:'お願いします。',sentenceKana:'おねがいします。',sentenceEn:'Please.'},
  {jp:'はい',kana:'はい',romaji:'hai',en:'yes',cat:'Greetings',sentence:'はい。',sentenceKana:'はい。',sentenceEn:'Yes.'},
  {jp:'いいえ',kana:'いいえ',romaji:'iie',en:'no',cat:'Greetings',sentence:'いいえ。',sentenceKana:'いいえ。',sentenceEn:'No.'},
  {jp:'一',kana:'いち',romaji:'ichi',en:'one',cat:'Numbers',sentence:'りんごが一つあります。',sentenceKana:'りんごがひとつあります。',sentenceEn:'There is one apple.'},
  {jp:'二',kana:'に',romaji:'ni',en:'two',cat:'Numbers',sentence:'りんごが二つあります。',sentenceKana:'りんごがふたつあります。',sentenceEn:'There are two apples.'},
  {jp:'三',kana:'さん',romaji:'san',en:'three',cat:'Numbers',sentence:'りんごが三つあります。',sentenceKana:'りんごがみっつあります。',sentenceEn:'There are three apples.'},
  {jp:'四',kana:'よん',romaji:'yon / shi',en:'four',cat:'Numbers',sentence:'りんごが四つあります。',sentenceKana:'りんごがよっつあります。',sentenceEn:'There are four apples.'},
  {jp:'五',kana:'ご',romaji:'go',en:'five',cat:'Numbers',sentence:'りんごが五つあります。',sentenceKana:'りんごがいつつあります。',sentenceEn:'There are five apples.'},
  {jp:'六',kana:'ろく',romaji:'roku',en:'six',cat:'Numbers',sentence:'りんごが六つあります。',sentenceKana:'りんごがむっつあります。',sentenceEn:'There are six apples.'},
  {jp:'七',kana:'なな',romaji:'nana / shichi',en:'seven',cat:'Numbers',sentence:'りんごが七つあります。',sentenceKana:'りんごがななつあります。',sentenceEn:'There are seven apples.'},
  {jp:'八',kana:'はち',romaji:'hachi',en:'eight',cat:'Numbers',sentence:'りんごが八つあります。',sentenceKana:'りんごがやっつあります。',sentenceEn:'There are eight apples.'},
  {jp:'九',kana:'きゅう',romaji:'kyū / ku',en:'nine',cat:'Numbers',sentence:'りんごが九つあります。',sentenceKana:'りんごがここのつあります。',sentenceEn:'There are nine apples.'},
  {jp:'十',kana:'じゅう',romaji:'jū',en:'ten',cat:'Numbers',sentence:'十円です。',sentenceKana:'じゅうえんです。',sentenceEn:'It\'s ten yen.'},
  {jp:'百',kana:'ひゃく',romaji:'hyaku',en:'hundred',cat:'Numbers',sentence:'百円です。',sentenceKana:'ひゃくえんです。',sentenceEn:'It\'s one hundred yen.'},
  {jp:'千',kana:'せん',romaji:'sen',en:'thousand',cat:'Numbers',sentence:'千円です。',sentenceKana:'せんえんです。',sentenceEn:'It\'s one thousand yen.'},
  {jp:'万',kana:'まん',romaji:'man',en:'ten thousand',cat:'Numbers',sentence:'一万円です。',sentenceKana:'いちまんえんです。',sentenceEn:'It\'s ten thousand yen.'},
  {jp:'ゼロ',kana:'ゼロ',romaji:'zero',en:'zero',cat:'Numbers',sentence:'ゼロです。',sentenceKana:'ゼロです。',sentenceEn:'It\'s zero.'},
  {jp:'月曜日',kana:'げつようび',romaji:'getsuyōbi',en:'Monday',cat:'Time',sentence:'今日は月曜日です。',sentenceKana:'きょうはげつようびです。',sentenceEn:'Today is Monday.'},
  {jp:'火曜日',kana:'かようび',romaji:'kayōbi',en:'Tuesday',cat:'Time',sentence:'今日は火曜日です。',sentenceKana:'きょうはかようびです。',sentenceEn:'Today is Tuesday.'},
  {jp:'水曜日',kana:'すいようび',romaji:'suiyōbi',en:'Wednesday',cat:'Time',sentence:'今日は水曜日です。',sentenceKana:'きょうはすいようびです。',sentenceEn:'Today is Wednesday.'},
  {jp:'木曜日',kana:'もくようび',romaji:'mokuyōbi',en:'Thursday',cat:'Time',sentence:'今日は木曜日です。',sentenceKana:'きょうはもくようびです。',sentenceEn:'Today is Thursday.'},
  {jp:'金曜日',kana:'きんようび',romaji:'kinyōbi',en:'Friday',cat:'Time',sentence:'今日は金曜日です。',sentenceKana:'きょうはきんようびです。',sentenceEn:'Today is Friday.'},
  {jp:'土曜日',kana:'どようび',romaji:'doyōbi',en:'Saturday',cat:'Time',sentence:'今日は土曜日です。',sentenceKana:'きょうはどようびです。',sentenceEn:'Today is Saturday.'},
  {jp:'日曜日',kana:'にちようび',romaji:'nichiyōbi',en:'Sunday',cat:'Time',sentence:'今日は日曜日です。',sentenceKana:'きょうはにちようびです。',sentenceEn:'Today is Sunday.'},
  {jp:'今日',kana:'きょう',romaji:'kyō',en:'today',cat:'Time',sentence:'今日はいい天気です。',sentenceKana:'きょうはいいてんきです。',sentenceEn:'Today is nice weather.'},
  {jp:'明日',kana:'あした',romaji:'ashita',en:'tomorrow',cat:'Time',sentence:'明日はテストです。',sentenceKana:'あしたはてすとです。',sentenceEn:'Tomorrow is the test.'},
  {jp:'昨日',kana:'きのう',romaji:'kinō',en:'yesterday',cat:'Time',sentence:'昨日は雨でした。',sentenceKana:'きのうはあめでした。',sentenceEn:'It rained yesterday.'},
  {jp:'今',kana:'いま',romaji:'ima',en:'now',cat:'Time',sentence:'今は何時ですか。',sentenceKana:'いまはなんじですか。',sentenceEn:'What time is it now?'},
  {jp:'朝',kana:'あさ',romaji:'asa',en:'morning',cat:'Time',sentence:'朝ご飯を食べます。',sentenceKana:'あさごはんをたべます。',sentenceEn:'I eat breakfast.'},
  {jp:'昼',kana:'ひる',romaji:'hiru',en:'noon, daytime',cat:'Time',sentence:'昼ご飯を食べます。',sentenceKana:'ひるごはんをたべます。',sentenceEn:'I eat lunch.'},
  {jp:'夜',kana:'よる',romaji:'yoru',en:'night',cat:'Time',sentence:'夜は静かです。',sentenceKana:'よるはしずかです。',sentenceEn:'The night is quiet.'},
  {jp:'晩',kana:'ばん',romaji:'ban',en:'evening',cat:'Time',sentence:'晩ご飯を食べます。',sentenceKana:'ばんごはんをたべます。',sentenceEn:'I eat dinner.'},
  {jp:'今朝',kana:'けさ',romaji:'kesa',en:'this morning',cat:'Time',sentence:'今朝は寒かったです。',sentenceKana:'けさはさむかったです。',sentenceEn:'It was cold this morning.'},
  {jp:'今晩',kana:'こんばん',romaji:'konban',en:'tonight',cat:'Time',sentence:'今晩は何をしますか。',sentenceKana:'こんばんはなにをしますか。',sentenceEn:'What will you do tonight?'},
  {jp:'午前',kana:'ごぜん',romaji:'gozen',en:'a.m., morning',cat:'Time',sentence:'午前中に勉強します。',sentenceKana:'ごぜんちゅうにべんきょうします。',sentenceEn:'I study in the morning.'},
  {jp:'午後',kana:'ごご',romaji:'gogo',en:'p.m., afternoon',cat:'Time',sentence:'午後は友だちと会います。',sentenceKana:'ごごはともだちとあいます。',sentenceEn:'I\'ll meet a friend in the afternoon.'},
  {jp:'毎日',kana:'まいにち',romaji:'mainichi',en:'every day',cat:'Time',sentence:'毎日勉強します。',sentenceKana:'まいにちべんきょうします。',sentenceEn:'I study every day.'},
  {jp:'毎朝',kana:'まいあさ',romaji:'maiasa',en:'every morning',cat:'Time',sentence:'毎朝コーヒーを飲みます。',sentenceKana:'まいあさこーひーをのみます。',sentenceEn:'I drink coffee every morning.'},
  {jp:'毎晩',kana:'まいばん',romaji:'maiban',en:'every night',cat:'Time',sentence:'毎晩テレビを見ます。',sentenceKana:'まいばんてれびをみます。',sentenceEn:'I watch TV every night.'},
  {jp:'今週',kana:'こんしゅう',romaji:'konshū',en:'this week',cat:'Time',sentence:'今週は忙しいです。',sentenceKana:'こんしゅうはいそがしいです。',sentenceEn:'I am busy this week.'},
  {jp:'来週',kana:'らいしゅう',romaji:'raishū',en:'next week',cat:'Time',sentence:'来週は試験があります。',sentenceKana:'らいしゅうはしけんがあります。',sentenceEn:'There is an exam next week.'},
  {jp:'先週',kana:'せんしゅう',romaji:'senshū',en:'last week',cat:'Time',sentence:'先週は友だちと映画を見ました。',sentenceKana:'せんしゅうはともだちとえいがをみました。',sentenceEn:'I watched a movie with a friend last week.'},
  {jp:'今月',kana:'こんげつ',romaji:'kongetsu',en:'this month',cat:'Time',sentence:'今月は雨が多いです。',sentenceKana:'こんげつはあめがおおいです。',sentenceEn:'It rains a lot this month.'},
  {jp:'来月',kana:'らいげつ',romaji:'raigetsu',en:'next month',cat:'Time',sentence:'来月は日本に行きます。',sentenceKana:'らいげつはにほんにいきます。',sentenceEn:'I will go to Japan next month.'},
  {jp:'先月',kana:'せんげつ',romaji:'sengetsu',en:'last month',cat:'Time',sentence:'先月は誕生日でした。',sentenceKana:'せんげつはたんじょうびでした。',sentenceEn:'It was my birthday last month.'},
  {jp:'今年',kana:'ことし',romaji:'kotoshi',en:'this year',cat:'Time',sentence:'今年は旅行をします。',sentenceKana:'ことしはりょこうをします。',sentenceEn:'I will travel this year.'},
  {jp:'来年',kana:'らいねん',romaji:'rainen',en:'next year',cat:'Time',sentence:'来年は大学に入学します。',sentenceKana:'らいねんはだいがくににゅうがくします。',sentenceEn:'I will enter university next year.'},
  {jp:'去年',kana:'きょねん',romaji:'kyonen',en:'last year',cat:'Time',sentence:'去年は海外に行きました。',sentenceKana:'きょねんはかいがいにいきました。',sentenceEn:'I went abroad last year.'},
  {jp:'時間',kana:'じかん',romaji:'jikan',en:'time, hour',cat:'Time',sentence:'時間がありません。',sentenceKana:'じかんがありません。',sentenceEn:'I don\'t have time.'},
  {jp:'週末',kana:'しゅうまつ',romaji:'shūmatsu',en:'weekend',cat:'Time',sentence:'週末はゆっくり休みます。',sentenceKana:'しゅうまつはゆっくりやすみます。',sentenceEn:'I rest well on the weekend.'},
  {jp:'私',kana:'わたし',romaji:'watashi',en:'I, me',cat:'People',sentence:'私は学生です。',sentenceKana:'わたしはがくせいです。',sentenceEn:'I am a student.'},
  {jp:'僕',kana:'ぼく',romaji:'boku',en:'I, me (male)',cat:'People',sentence:'僕はサッカーが好きです。',sentenceKana:'ぼくはさっかーがすきです。',sentenceEn:'I like soccer.'},
  {jp:'あなた',kana:'あなた',romaji:'anata',en:'you',cat:'People',sentence:'あなたは日本人ですか。',sentenceKana:'あなたはにほんじんですか。',sentenceEn:'Are you Japanese?'},
  {jp:'彼',kana:'かれ',romaji:'kare',en:'he, boyfriend',cat:'People',sentence:'彼は学生です。',sentenceKana:'かれはがくせいです。',sentenceEn:'He is a student.'},
  {jp:'彼女',kana:'かのじょ',romaji:'kanojo',en:'she, girlfriend',cat:'People',sentence:'彼女は先生です。',sentenceKana:'かのじょはせんせいです。',sentenceEn:'She is a teacher.'},
  {jp:'人',kana:'ひと',romaji:'hito',en:'person',cat:'People',sentence:'あそこに人がいます。',sentenceKana:'あそこにひとがいます。',sentenceEn:'There is a person over there.'},
  {jp:'友だち',kana:'ともだち',romaji:'tomodachi',en:'friend',cat:'People',sentence:'友だちと遊びます。',sentenceKana:'ともだちとあそびます。',sentenceEn:'I play with friends.'},
  {jp:'先生',kana:'せんせい',romaji:'sensei',en:'teacher',cat:'People',sentence:'先生は優しいです。',sentenceKana:'せんせいはやさしいです。',sentenceEn:'The teacher is kind.'},
  {jp:'学生',kana:'がくせい',romaji:'gakusei',en:'student',cat:'People',sentence:'私は学生です。',sentenceKana:'わたしはがくせいです。',sentenceEn:'I am a student.'},
  {jp:'会社員',kana:'かいしゃいん',romaji:'kaishain',en:'office worker',cat:'People',sentence:'父は会社員です。',sentenceKana:'ちちはかいしゃいんです。',sentenceEn:'My father is an office worker.'},
  {jp:'医者',kana:'いしゃ',romaji:'isha',en:'doctor',cat:'People',sentence:'医者に会います。',sentenceKana:'いしゃにあいます。',sentenceEn:'I meet the doctor.'},
  {jp:'家族',kana:'かぞく',romaji:'kazoku',en:'family',cat:'People',sentence:'家族は４人です。',sentenceKana:'かぞくはよにんです。',sentenceEn:'My family has four people.'},
  {jp:'両親',kana:'りょうしん',romaji:'ryōshin',en:'parents',cat:'People',sentence:'両親は元気です。',sentenceKana:'りょうしんはげんきです。',sentenceEn:'My parents are healthy.'},
  {jp:'お父さん',kana:'おとうさん',romaji:'otōsan',en:'father',cat:'People',sentence:'お父さんは会社員です。',sentenceKana:'おとうさんはかいしゃいんです。',sentenceEn:'My father is an office worker.'},
  {jp:'お母さん',kana:'おかあさん',romaji:'okāsan',en:'mother',cat:'People',sentence:'お母さんは料理が上手です。',sentenceKana:'おかあさんはりょうりがじょうずです。',sentenceEn:'My mother is good at cooking.'},
  {jp:'兄',kana:'あに',romaji:'ani',en:'older brother',cat:'People',sentence:'兄は大学生です。',sentenceKana:'あにはだいがくせいです。',sentenceEn:'My older brother is a university student.'},
  {jp:'姉',kana:'あね',romaji:'ane',en:'older sister',cat:'People',sentence:'姉は看護師です。',sentenceKana:'あねはかんごしです。',sentenceEn:'My older sister is a nurse.'},
  {jp:'弟',kana:'おとうと',romaji:'otōto',en:'younger brother',cat:'People',sentence:'弟は小学生です。',sentenceKana:'おとうとはしょうがくせいです。',sentenceEn:'My younger brother is an elementary school student.'},
  {jp:'妹',kana:'いもうと',romaji:'imōto',en:'younger sister',cat:'People',sentence:'妹は中学生です。',sentenceKana:'いもうとはちゅうがくせいです。',sentenceEn:'My younger sister is a junior high school student.'},
  {jp:'兄弟',kana:'きょうだい',romaji:'kyōdai',en:'siblings',cat:'People',sentence:'兄弟がいます。',sentenceKana:'きょうだいがいます。',sentenceEn:'I have siblings.'},
  {jp:'祖父',kana:'そふ',romaji:'sofu',en:'grandfather',cat:'People',sentence:'祖父は元気です。',sentenceKana:'そふはげんきです。',sentenceEn:'My grandfather is healthy.'},
  {jp:'祖母',kana:'そぼ',romaji:'sobo',en:'grandmother',cat:'People',sentence:'祖母は優しいです。',sentenceKana:'そぼはやさしいです。',sentenceEn:'My grandmother is kind.'},
  {jp:'子ども',kana:'こども',romaji:'kodomo',en:'child',cat:'People',sentence:'子どもが三人います。',sentenceKana:'こどもがさんにんいます。',sentenceEn:'There are three children.'},
  {jp:'男の人',kana:'おとこのひと',romaji:'otoko no hito',en:'man',cat:'People',sentence:'あの男の人は先生です。',sentenceKana:'あのおとこのひとはせんせいです。',sentenceEn:'That man is a teacher.'},
  {jp:'女の人',kana:'おんなのひと',romaji:'onna no hito',en:'woman',cat:'People',sentence:'あの女の人は医者です。',sentenceKana:'あのおんなのひとはいしゃです。',sentenceEn:'That woman is a doctor.'},
  {jp:'名前',kana:'なまえ',romaji:'namae',en:'name',cat:'People',sentence:'名前は何ですか。',sentenceKana:'なまえはなんですか。',sentenceEn:'What is your name?'},
  {jp:'体',kana:'からだ',romaji:'karada',en:'body',cat:'Body',sentence:'体を動かします。',sentenceKana:'からだをうごかします。',sentenceEn:'I move my body.'},
  {jp:'頭',kana:'あたま',romaji:'atama',en:'head',cat:'Body',sentence:'頭が痛いです。',sentenceKana:'あたまがいたいです。',sentenceEn:'My head hurts.'},
  {jp:'顔',kana:'かお',romaji:'kao',en:'face',cat:'Body',sentence:'顔を洗います。',sentenceKana:'かおをあらいます。',sentenceEn:'I wash my face.'},
  {jp:'目',kana:'め',romaji:'me',en:'eye',cat:'Body',sentence:'目が大きいです。',sentenceKana:'めがおおきいです。',sentenceEn:'My eyes are big.'},
  {jp:'耳',kana:'みみ',romaji:'mimi',en:'ear',cat:'Body',sentence:'耳が痛いです。',sentenceKana:'みみがいたいです。',sentenceEn:'My ear hurts.'},
  {jp:'鼻',kana:'はな',romaji:'hana',en:'nose',cat:'Body',sentence:'鼻が高いです。',sentenceKana:'はながたかいです。',sentenceEn:'My nose is tall.'},
  {jp:'口',kana:'くち',romaji:'kuchi',en:'mouth',cat:'Body',sentence:'口を開けてください。',sentenceKana:'くちをあけてください。',sentenceEn:'Please open your mouth.'},
  {jp:'歯',kana:'は',romaji:'ha',en:'tooth',cat:'Body',sentence:'歯を磨きます。',sentenceKana:'はをみがきます。',sentenceEn:'I brush my teeth.'},
  {jp:'手',kana:'て',romaji:'te',en:'hand',cat:'Body',sentence:'手を洗います。',sentenceKana:'てをあらいます。',sentenceEn:'I wash my hands.'},
  {jp:'足',kana:'あし',romaji:'ashi',en:'foot, leg',cat:'Body',sentence:'足が速いです。',sentenceKana:'あしがはやいです。',sentenceEn:'My legs are fast.'},
  {jp:'お腹',kana:'おなか',romaji:'onaka',en:'stomach, belly',cat:'Body',sentence:'お腹がすきました。',sentenceKana:'おなかがすきました。',sentenceEn:'I\'m hungry.'},
  {jp:'家',kana:'いえ',romaji:'ie',en:'house, home',cat:'Places',sentence:'家に帰ります。',sentenceKana:'いえにかえります。',sentenceEn:'I go home.'},
  {jp:'学校',kana:'がっこう',romaji:'gakkō',en:'school',cat:'Places',sentence:'学校へ行きます。',sentenceKana:'がっこうへいきます。',sentenceEn:'I go to school.'},
  {jp:'大学',kana:'だいがく',romaji:'daigaku',en:'university',cat:'Places',sentence:'大学で勉強します。',sentenceKana:'だいがくでべんきょうします。',sentenceEn:'I study at university.'},
  {jp:'教室',kana:'きょうしつ',romaji:'kyōshitsu',en:'classroom',cat:'Places',sentence:'教室にいます。',sentenceKana:'きょうしつにいます。',sentenceEn:'I am in the classroom.'},
  {jp:'会社',kana:'かいしゃ',romaji:'kaisha',en:'company',cat:'Places',sentence:'会社で働きます。',sentenceKana:'かいしゃではたらきます。',sentenceEn:'I work at a company.'},
  {jp:'駅',kana:'えき',romaji:'eki',en:'station',cat:'Places',sentence:'駅に行きます。',sentenceKana:'えきにいきます。',sentenceEn:'I go to the station.'},
  {jp:'店',kana:'みせ',romaji:'mise',en:'shop, store',cat:'Places',sentence:'店で本を買います。',sentenceKana:'みせでほんをかいます。',sentenceEn:'I buy a book at the store.'},
  {jp:'デパート',kana:'デパート',romaji:'depāto',en:'department store',cat:'Places',sentence:'デパートで買い物をします。',sentenceKana:'でぱーとでかいものをします。',sentenceEn:'I shop at the department store.'},
  {jp:'スーパー',kana:'スーパー',romaji:'sūpā',en:'supermarket',cat:'Places',sentence:'スーパーで野菜を買います。',sentenceKana:'すーぱーでやさいをかいます。',sentenceEn:'I buy vegetables at the supermarket.'},
  {jp:'病院',kana:'びょういん',romaji:'byōin',en:'hospital',cat:'Places',sentence:'病院に行きます。',sentenceKana:'びょういんにいきます。',sentenceEn:'I go to the hospital.'},
  {jp:'銀行',kana:'ぎんこう',romaji:'ginkō',en:'bank',cat:'Places',sentence:'銀行でお金を下ろします。',sentenceKana:'ぎんこうでおかねをおろします。',sentenceEn:'I withdraw money at the bank.'},
  {jp:'図書館',kana:'としょかん',romaji:'toshokan',en:'library',cat:'Places',sentence:'図書館で本を読みます。',sentenceKana:'としょかんでほんをよみます。',sentenceEn:'I read books at the library.'},
  {jp:'郵便局',kana:'ゆうびんきょく',romaji:'yūbinkyoku',en:'post office',cat:'Places',sentence:'郵便局で手紙を出します。',sentenceKana:'ゆうびんきょくでてがみをだします。',sentenceEn:'I mail a letter at the post office.'},
  {jp:'喫茶店',kana:'きっさてん',romaji:'kissaten',en:'café',cat:'Places',sentence:'喫茶店でコーヒーを飲みます。',sentenceKana:'きっさてんでこーひーをのみます。',sentenceEn:'I drink coffee at the café.'},
  {jp:'レストラン',kana:'レストラン',romaji:'resutoran',en:'restaurant',cat:'Places',sentence:'レストランでご飯を食べます。',sentenceKana:'れすとらんでごはんをたべます。',sentenceEn:'I eat a meal at the restaurant.'},
  {jp:'ホテル',kana:'ホテル',romaji:'hoteru',en:'hotel',cat:'Places',sentence:'ホテルに泊まります。',sentenceKana:'ほてるにとまります。',sentenceEn:'I stay at a hotel.'},
  {jp:'公園',kana:'こうえん',romaji:'kōen',en:'park',cat:'Places',sentence:'公園で散歩します。',sentenceKana:'こうえんでさんぽします。',sentenceEn:'I take a walk in the park.'},
  {jp:'町',kana:'まち',romaji:'machi',en:'town',cat:'Places',sentence:'町は賑やかです。',sentenceKana:'まちはにぎやかです。',sentenceEn:'The town is lively.'},
  {jp:'道',kana:'みち',romaji:'michi',en:'road, street',cat:'Places',sentence:'道を歩きます。',sentenceKana:'みちをあるきます。',sentenceEn:'I walk on the road.'},
  {jp:'部屋',kana:'へや',romaji:'heya',en:'room',cat:'Places',sentence:'部屋を掃除します。',sentenceKana:'へやをそうじします。',sentenceEn:'I clean the room.'},
  {jp:'庭',kana:'にわ',romaji:'niwa',en:'garden',cat:'Places',sentence:'庭に花が咲いています。',sentenceKana:'にわにはながさいています。',sentenceEn:'Flowers are blooming in the garden.'},
  {jp:'トイレ',kana:'トイレ',romaji:'toire',en:'toilet',cat:'Places',sentence:'トイレはどこですか。',sentenceKana:'といれはどこですか。',sentenceEn:'Where is the toilet?'},
  {jp:'入口',kana:'いりぐち',romaji:'iriguchi',en:'entrance',cat:'Places',sentence:'入口はこちらです。',sentenceKana:'いりぐちはこちらです。',sentenceEn:'The entrance is this way.'},
  {jp:'出口',kana:'でぐち',romaji:'deguchi',en:'exit',cat:'Places',sentence:'出口はあそこです。',sentenceKana:'でぐちはあそこです。',sentenceEn:'The exit is over there.'},
  {jp:'国',kana:'くに',romaji:'kuni',en:'country',cat:'Places',sentence:'日本はいい国です。',sentenceKana:'にほんはいいくにです。',sentenceEn:'Japan is a good country.'},
  {jp:'ご飯',kana:'ごはん',romaji:'gohan',en:'rice, meal',cat:'Food',sentence:'ご飯を食べます。',sentenceKana:'ごはんをたべます。',sentenceEn:'I eat a meal.'},
  {jp:'朝ご飯',kana:'あさごはん',romaji:'asagohan',en:'breakfast',cat:'Food',sentence:'朝ご飯を食べます。',sentenceKana:'あさごはんをたべます。',sentenceEn:'I eat breakfast.'},
  {jp:'昼ご飯',kana:'ひるごはん',romaji:'hirugohan',en:'lunch',cat:'Food',sentence:'昼ご飯を食べます。',sentenceKana:'ひるごはんをたべます。',sentenceEn:'I eat lunch.'},
  {jp:'晩ご飯',kana:'ばんごはん',romaji:'bangohan',en:'dinner',cat:'Food',sentence:'晩ご飯を食べます。',sentenceKana:'ばんごはんをたべます。',sentenceEn:'I eat dinner.'},
  {jp:'パン',kana:'パン',romaji:'pan',en:'bread',cat:'Food',sentence:'パンを食べます。',sentenceKana:'ぱんをたべます。',sentenceEn:'I eat bread.'},
  {jp:'水',kana:'みず',romaji:'mizu',en:'water',cat:'Food',sentence:'水を飲みます。',sentenceKana:'みずをのみます。',sentenceEn:'I drink water.'},
  {jp:'お茶',kana:'おちゃ',romaji:'ocha',en:'green tea',cat:'Food',sentence:'お茶を飲みます。',sentenceKana:'おちゃをのみます。',sentenceEn:'I drink green tea.'},
  {jp:'紅茶',kana:'こうちゃ',romaji:'kōcha',en:'black tea',cat:'Food',sentence:'紅茶を飲みます。',sentenceKana:'こうちゃをのみます。',sentenceEn:'I drink black tea.'},
  {jp:'コーヒー',kana:'コーヒー',romaji:'kōhī',en:'coffee',cat:'Food',sentence:'コーヒーを飲みます。',sentenceKana:'こーひーをのみます。',sentenceEn:'I drink coffee.'},
  {jp:'牛乳',kana:'ぎゅうにゅう',romaji:'gyūnyū',en:'milk',cat:'Food',sentence:'牛乳を飲みます。',sentenceKana:'ぎゅうにゅうをのみます。',sentenceEn:'I drink milk.'},
  {jp:'ジュース',kana:'ジュース',romaji:'jūsu',en:'juice',cat:'Food',sentence:'ジュースを飲みます。',sentenceKana:'じゅーすをのみます。',sentenceEn:'I drink juice.'},
  {jp:'お酒',kana:'おさけ',romaji:'osake',en:'alcohol, sake',cat:'Food',sentence:'お酒を飲みません。',sentenceKana:'おさけをのみません。',sentenceEn:'I don\'t drink alcohol.'},
  {jp:'ビール',kana:'ビール',romaji:'bīru',en:'beer',cat:'Food',sentence:'ビールを飲みます。',sentenceKana:'びーるをのみます。',sentenceEn:'I drink beer.'},
  {jp:'卵',kana:'たまご',romaji:'tamago',en:'egg',cat:'Food',sentence:'卵を食べます。',sentenceKana:'たまごをたべます。',sentenceEn:'I eat eggs.'},
  {jp:'魚',kana:'さかな',romaji:'sakana',en:'fish',cat:'Food',sentence:'魚を食べます。',sentenceKana:'さかなをたべます。',sentenceEn:'I eat fish.'},
  {jp:'肉',kana:'にく',romaji:'niku',en:'meat',cat:'Food',sentence:'肉を食べます。',sentenceKana:'にくをたべます。',sentenceEn:'I eat meat.'},
  {jp:'野菜',kana:'やさい',romaji:'yasai',en:'vegetable',cat:'Food',sentence:'野菜を食べます。',sentenceKana:'やさいをたべます。',sentenceEn:'I eat vegetables.'},
  {jp:'果物',kana:'くだもの',romaji:'kudamono',en:'fruit',cat:'Food',sentence:'果物を食べます。',sentenceKana:'くだものをたべます。',sentenceEn:'I eat fruit.'},
  {jp:'りんご',kana:'りんご',romaji:'ringo',en:'apple',cat:'Food',sentence:'りんごを食べます。',sentenceKana:'りんごをたべます。',sentenceEn:'I eat an apple.'},
  {jp:'みかん',kana:'みかん',romaji:'mikan',en:'mandarin orange',cat:'Food',sentence:'みかんを食べます。',sentenceKana:'みかんをたべます。',sentenceEn:'I eat a mandarin orange.'},
  {jp:'お菓子',kana:'おかし',romaji:'okashi',en:'sweets, snacks',cat:'Food',sentence:'お菓子を食べます。',sentenceKana:'おかしをたべます。',sentenceEn:'I eat sweets.'},
  {jp:'砂糖',kana:'さとう',romaji:'satō',en:'sugar',cat:'Food',sentence:'砂糖を入れます。',sentenceKana:'さとうをいれます。',sentenceEn:'I put sugar in.'},
  {jp:'塩',kana:'しお',romaji:'shio',en:'salt',cat:'Food',sentence:'塩を入れます。',sentenceKana:'しおをいれます。',sentenceEn:'I put salt in.'},
  {jp:'食べ物',kana:'たべもの',romaji:'tabemono',en:'food',cat:'Food',sentence:'食べ物を買います。',sentenceKana:'たべものをかいます。',sentenceEn:'I buy food.'},
  {jp:'飲み物',kana:'のみもの',romaji:'nomimono',en:'drink',cat:'Food',sentence:'飲み物を飲みます。',sentenceKana:'のみものをのみます。',sentenceEn:'I drink a drink.'},
  {jp:'料理',kana:'りょうり',romaji:'ryōri',en:'cooking, dish',cat:'Food',sentence:'料理を作ります。',sentenceKana:'りょうりをつくります。',sentenceEn:'I cook.'},
  {jp:'箸',kana:'はし',romaji:'hashi',en:'chopsticks',cat:'Food',sentence:'箸で食べます。',sentenceKana:'はしでたべます。',sentenceEn:'I eat with chopsticks.'},
  {jp:'電車',kana:'でんしゃ',romaji:'densha',en:'train',cat:'Transport',sentence:'電車に乗ります。',sentenceKana:'でんしゃにのります。',sentenceEn:'I ride the train.'},
  {jp:'車',kana:'くるま',romaji:'kuruma',en:'car',cat:'Transport',sentence:'車で行きます。',sentenceKana:'くるまでいきます。',sentenceEn:'I go by car.'},
  {jp:'自転車',kana:'じてんしゃ',romaji:'jitensha',en:'bicycle',cat:'Transport',sentence:'自転車に乗ります。',sentenceKana:'じてんしゃにのります。',sentenceEn:'I ride a bicycle.'},
  {jp:'バス',kana:'バス',romaji:'basu',en:'bus',cat:'Transport',sentence:'バスに乗ります。',sentenceKana:'ばすにのります。',sentenceEn:'I ride the bus.'},
  {jp:'タクシー',kana:'タクシー',romaji:'takushī',en:'taxi',cat:'Transport',sentence:'タクシーで行きます。',sentenceKana:'たくしーでいきます。',sentenceEn:'I go by taxi.'},
  {jp:'飛行機',kana:'ひこうき',romaji:'hikōki',en:'airplane',cat:'Transport',sentence:'飛行機で行きます。',sentenceKana:'ひこうきでいきます。',sentenceEn:'I go by airplane.'},
  {jp:'地下鉄',kana:'ちかてつ',romaji:'chikatetsu',en:'subway',cat:'Transport',sentence:'地下鉄に乗ります。',sentenceKana:'ちかてつにのります。',sentenceEn:'I ride the subway.'},
  {jp:'船',kana:'ふね',romaji:'fune',en:'ship, boat',cat:'Transport',sentence:'船に乗ります。',sentenceKana:'ふねにのります。',sentenceEn:'I board a ship.'},
  {jp:'机',kana:'つくえ',romaji:'tsukue',en:'desk',cat:'Objects',sentence:'机の上に本があります。',sentenceKana:'つくえのうえにほんがあります。',sentenceEn:'There is a book on the desk.'},
  {jp:'椅子',kana:'いす',romaji:'isu',en:'chair',cat:'Objects',sentence:'椅子に座ります。',sentenceKana:'いすにすわります。',sentenceEn:'I sit on the chair.'},
  {jp:'ドア',kana:'ドア',romaji:'doa',en:'door',cat:'Objects',sentence:'ドアを開けます。',sentenceKana:'どあをあけます。',sentenceEn:'I open the door.'},
  {jp:'窓',kana:'まど',romaji:'mado',en:'window',cat:'Objects',sentence:'窓を閉めます。',sentenceKana:'まどをしめます。',sentenceEn:'I close the window.'},
  {jp:'電気',kana:'でんき',romaji:'denki',en:'electricity, light',cat:'Objects',sentence:'電気をつけます。',sentenceKana:'でんきをつけます。',sentenceEn:'I turn on the light.'},
  {jp:'テレビ',kana:'テレビ',romaji:'terebi',en:'television',cat:'Objects',sentence:'テレビを見ます。',sentenceKana:'てれびをみます。',sentenceEn:'I watch TV.'},
  {jp:'電話',kana:'でんわ',romaji:'denwa',en:'telephone',cat:'Objects',sentence:'電話をかけます。',sentenceKana:'でんわをかけます。',sentenceEn:'I make a phone call.'},
  {jp:'時計',kana:'とけい',romaji:'tokei',en:'clock, watch',cat:'Objects',sentence:'時計を見ます。',sentenceKana:'とけいをみます。',sentenceEn:'I look at the clock.'},
  {jp:'傘',kana:'かさ',romaji:'kasa',en:'umbrella',cat:'Objects',sentence:'傘をさします。',sentenceKana:'かさをさします。',sentenceEn:'I put up an umbrella.'},
  {jp:'鞄',kana:'かばん',romaji:'kaban',en:'bag',cat:'Objects',sentence:'鞄を持ちます。',sentenceKana:'かばんをもちます。',sentenceEn:'I carry a bag.'},
  {jp:'靴',kana:'くつ',romaji:'kutsu',en:'shoes',cat:'Objects',sentence:'靴を履きます。',sentenceKana:'くつをはきます。',sentenceEn:'I put on shoes.'},
  {jp:'服',kana:'ふく',romaji:'fuku',en:'clothes',cat:'Objects',sentence:'服を着ます。',sentenceKana:'ふくをきます。',sentenceEn:'I wear clothes.'},
  {jp:'帽子',kana:'ぼうし',romaji:'bōshi',en:'hat, cap',cat:'Objects',sentence:'帽子をかぶります。',sentenceKana:'ぼうしをかぶります。',sentenceEn:'I wear a hat.'},
  {jp:'眼鏡',kana:'めがね',romaji:'megane',en:'glasses',cat:'Objects',sentence:'眼鏡をかけます。',sentenceKana:'めがねをかけます。',sentenceEn:'I wear glasses.'},
  {jp:'鍵',kana:'かぎ',romaji:'kagi',en:'key',cat:'Objects',sentence:'鍵をかけます。',sentenceKana:'かぎをかけます。',sentenceEn:'I lock (with a key).'},
  {jp:'写真',kana:'しゃしん',romaji:'shashin',en:'photograph',cat:'Objects',sentence:'写真を撮ります。',sentenceKana:'しゃしんをとります。',sentenceEn:'I take a photograph.'},
  {jp:'新聞',kana:'しんぶん',romaji:'shinbun',en:'newspaper',cat:'Objects',sentence:'新聞を読みます。',sentenceKana:'しんぶんをよみます。',sentenceEn:'I read a newspaper.'},
  {jp:'雑誌',kana:'ざっし',romaji:'zasshi',en:'magazine',cat:'Objects',sentence:'雑誌を読みます。',sentenceKana:'ざっしをよみます。',sentenceEn:'I read a magazine.'},
  {jp:'本',kana:'ほん',romaji:'hon',en:'book',cat:'Objects',sentence:'本を読みます。',sentenceKana:'ほんをよみます。',sentenceEn:'I read a book.'},
  {jp:'辞書',kana:'じしょ',romaji:'jisho',en:'dictionary',cat:'Objects',sentence:'辞書を引きます。',sentenceKana:'じしょをひきます。',sentenceEn:'I look up in a dictionary.'},
  {jp:'ノート',kana:'ノート',romaji:'nōto',en:'notebook',cat:'Objects',sentence:'ノートに書きます。',sentenceKana:'のーとに書きます。',sentenceEn:'I write in a notebook.'},
  {jp:'鉛筆',kana:'えんぴつ',romaji:'enpitsu',en:'pencil',cat:'Objects',sentence:'鉛筆で書きます。',sentenceKana:'えんぴつでかきます。',sentenceEn:'I write with a pencil.'},
  {jp:'ペン',kana:'ペン',romaji:'pen',en:'pen',cat:'Objects',sentence:'ペンで書きます。',sentenceKana:'ぺんでかきます。',sentenceEn:'I write with a pen.'},
  {jp:'紙',kana:'かみ',romaji:'kami',en:'paper',cat:'Objects',sentence:'紙に書きます。',sentenceKana:'かみにかきます。',sentenceEn:'I write on paper.'},
  {jp:'手紙',kana:'てがみ',romaji:'tegami',en:'letter',cat:'Objects',sentence:'手紙を書きます。',sentenceKana:'てがみをかきます。',sentenceEn:'I write a letter.'},
  {jp:'お金',kana:'おかね',romaji:'okane',en:'money',cat:'Objects',sentence:'お金を払います。',sentenceKana:'おかねをはらいます。',sentenceEn:'I pay money.'},
  {jp:'財布',kana:'さいふ',romaji:'saifu',en:'wallet',cat:'Objects',sentence:'財布にお金を入れます。',sentenceKana:'さいふにおかねをいれます。',sentenceEn:'I put money in the wallet.'},
  {jp:'パソコン',kana:'パソコン',romaji:'pasokon',en:'computer',cat:'Objects',sentence:'パソコンを使います。',sentenceKana:'ぱそこんをつかいます。',sentenceEn:'I use a computer.'},
  {jp:'カメラ',kana:'カメラ',romaji:'kamera',en:'camera',cat:'Objects',sentence:'カメラで写真を撮ります。',sentenceKana:'かめらでしゃしんをとります。',sentenceEn:'I take photos with a camera.'},
  {jp:'空',kana:'そら',romaji:'sora',en:'sky',cat:'Nature',sentence:'空が青いです。',sentenceKana:'そらがあおいです。',sentenceEn:'The sky is blue.'},
  {jp:'海',kana:'うみ',romaji:'umi',en:'sea',cat:'Nature',sentence:'海に行きます。',sentenceKana:'うみにいきます。',sentenceEn:'I go to the sea.'},
  {jp:'山',kana:'やま',romaji:'yama',en:'mountain',cat:'Nature',sentence:'山に登ります。',sentenceKana:'やまにのぼります。',sentenceEn:'I climb a mountain.'},
  {jp:'川',kana:'かわ',romaji:'kawa',en:'river',cat:'Nature',sentence:'川で泳ぎます。',sentenceKana:'かわでおよぎます。',sentenceEn:'I swim in the river.'},
  {jp:'木',kana:'き',romaji:'ki',en:'tree',cat:'Nature',sentence:'木が大きいです。',sentenceKana:'きがおおきいです。',sentenceEn:'The tree is big.'},
  {jp:'花',kana:'はな',romaji:'hana',en:'flower',cat:'Nature',sentence:'花が咲いています。',sentenceKana:'はながさいています。',sentenceEn:'Flowers are blooming.'},
  {jp:'天気',kana:'てんき',romaji:'tenki',en:'weather',cat:'Nature',sentence:'天気がいいです。',sentenceKana:'てんきがいいです。',sentenceEn:'The weather is good.'},
  {jp:'雨',kana:'あめ',romaji:'ame',en:'rain',cat:'Nature',sentence:'雨が降っています。',sentenceKana:'あめがふっています。',sentenceEn:'It is raining.'},
  {jp:'雪',kana:'ゆき',romaji:'yuki',en:'snow',cat:'Nature',sentence:'雪が降っています。',sentenceKana:'ゆきがふっています。',sentenceEn:'It is snowing.'},
  {jp:'風',kana:'かぜ',romaji:'kaze',en:'wind',cat:'Nature',sentence:'風が強いです。',sentenceKana:'かぜがつよいです。',sentenceEn:'The wind is strong.'},
  {jp:'晴れ',kana:'はれ',romaji:'hare',en:'clear weather',cat:'Nature',sentence:'今日は晴れです。',sentenceKana:'きょうははれです。',sentenceEn:'Today is clear.'},
  {jp:'曇り',kana:'くもり',romaji:'kumori',en:'cloudy',cat:'Nature',sentence:'今日は曇りです。',sentenceKana:'きょうはくもりです。',sentenceEn:'Today is cloudy.'},
  {jp:'食べる',kana:'たべる',romaji:'taberu',en:'to eat',cat:'Verbs',sentence:'朝ご飯を食べます。',sentenceKana:'あさごはんをたべます。',sentenceEn:'I eat breakfast.'},
  {jp:'飲む',kana:'のむ',romaji:'nomu',en:'to drink',cat:'Verbs',sentence:'水を飲みます。',sentenceKana:'みずをのみます。',sentenceEn:'I drink water.'},
  {jp:'見る',kana:'みる',romaji:'miru',en:'to see, watch',cat:'Verbs',sentence:'テレビを見ます。',sentenceKana:'てれびをみます。',sentenceEn:'I watch TV.'},
  {jp:'聞く',kana:'きく',romaji:'kiku',en:'to listen, ask',cat:'Verbs',sentence:'音楽を聞きます。',sentenceKana:'おんがくをききます。',sentenceEn:'I listen to music.'},
  {jp:'読む',kana:'よむ',romaji:'yomu',en:'to read',cat:'Verbs',sentence:'本を読みます。',sentenceKana:'ほんをよみます。',sentenceEn:'I read a book.'},
  {jp:'書く',kana:'かく',romaji:'kaku',en:'to write',cat:'Verbs',sentence:'手紙を書きます。',sentenceKana:'てがみをかきます。',sentenceEn:'I write a letter.'},
  {jp:'話す',kana:'はなす',romaji:'hanasu',en:'to speak',cat:'Verbs',sentence:'日本語を話します。',sentenceKana:'にほんごをはなします。',sentenceEn:'I speak Japanese.'},
  {jp:'言う',kana:'いう',romaji:'iu',en:'to say',cat:'Verbs',sentence:'何と言いますか。',sentenceKana:'なんといいますか。',sentenceEn:'What do you say?'},
  {jp:'思う',kana:'おもう',romaji:'omou',en:'to think',cat:'Verbs',sentence:'そう思います。',sentenceKana:'そうおもいます。',sentenceEn:'I think so.'},
  {jp:'知る',kana:'しる',romaji:'shiru',en:'to know',cat:'Verbs',sentence:'彼を知っています。',sentenceKana:'かれをしっています。',sentenceEn:'I know him.'},
  {jp:'分かる',kana:'わかる',romaji:'wakaru',en:'to understand',cat:'Verbs',sentence:'日本語が分かります。',sentenceKana:'にほんごがわかります。',sentenceEn:'I understand Japanese.'},
  {jp:'行く',kana:'いく',romaji:'iku',en:'to go',cat:'Verbs',sentence:'学校に行きます。',sentenceKana:'がっこうにいきます。',sentenceEn:'I go to school.'},
  {jp:'来る',kana:'くる',romaji:'kuru',en:'to come',cat:'Verbs',sentence:'友だちが来ます。',sentenceKana:'ともだちがきます。',sentenceEn:'My friend comes.'},
  {jp:'帰る',kana:'かえる',romaji:'kaeru',en:'to return home',cat:'Verbs',sentence:'家に帰ります。',sentenceKana:'いえにかえります。',sentenceEn:'I go home.'},
  {jp:'する',kana:'する',romaji:'suru',en:'to do',cat:'Verbs',sentence:'勉強します。',sentenceKana:'べんきょうします。',sentenceEn:'I study.'},
  {jp:'買う',kana:'かう',romaji:'kau',en:'to buy',cat:'Verbs',sentence:'本を買います。',sentenceKana:'ほんをかいます。',sentenceEn:'I buy a book.'},
  {jp:'売る',kana:'うる',romaji:'uru',en:'to sell',cat:'Verbs',sentence:'店で果物を売ります。',sentenceKana:'みせでくだものをうります。',sentenceEn:'The store sells fruit.'},
  {jp:'会う',kana:'あう',romaji:'au',en:'to meet',cat:'Verbs',sentence:'友だちに会います。',sentenceKana:'ともだちにあいます。',sentenceEn:'I meet a friend.'},
  {jp:'待つ',kana:'まつ',romaji:'matsu',en:'to wait',cat:'Verbs',sentence:'バスを待ちます。',sentenceKana:'ばすをまちます。',sentenceEn:'I wait for the bus.'},
  {jp:'作る',kana:'つくる',romaji:'tsukuru',en:'to make',cat:'Verbs',sentence:'料理を作ります。',sentenceKana:'りょうりをつくります。',sentenceEn:'I make a dish.'},
  {jp:'使う',kana:'つかう',romaji:'tsukau',en:'to use',cat:'Verbs',sentence:'コンピューターを使います。',sentenceKana:'こんぴゅーたーをつかいます。',sentenceEn:'I use a computer.'},
  {jp:'教える',kana:'おしえる',romaji:'oshieru',en:'to teach',cat:'Verbs',sentence:'先生が英語を教えます。',sentenceKana:'せんせいがえいごをおしえます。',sentenceEn:'The teacher teaches English.'},
  {jp:'習う',kana:'ならう',romaji:'narau',en:'to learn',cat:'Verbs',sentence:'日本語を習います。',sentenceKana:'にほんごをならいます。',sentenceEn:'I learn Japanese.'},
  {jp:'勉強する',kana:'べんきょうする',romaji:'benkyō suru',en:'to study',cat:'Verbs',sentence:'毎日勉強します。',sentenceKana:'まいにちべんきょうします。',sentenceEn:'I study every day.'},
  {jp:'働く',kana:'はたらく',romaji:'hataraku',en:'to work',cat:'Verbs',sentence:'会社で働きます。',sentenceKana:'かいしゃではたらきます。',sentenceEn:'I work at a company.'},
  {jp:'休む',kana:'やすむ',romaji:'yasumu',en:'to rest',cat:'Verbs',sentence:'今日は休みます。',sentenceKana:'きょうはやすみます。',sentenceEn:'I rest today.'},
  {jp:'遊ぶ',kana:'あそぶ',romaji:'asobu',en:'to play',cat:'Verbs',sentence:'公園で遊びます。',sentenceKana:'こうえんであそびます。',sentenceEn:'I play in the park.'},
  {jp:'泳ぐ',kana:'およぐ',romaji:'oyogu',en:'to swim',cat:'Verbs',sentence:'プールで泳ぎます。',sentenceKana:'ぷーるでおよぎます。',sentenceEn:'I swim in the pool.'},
  {jp:'歩く',kana:'あるく',romaji:'aruku',en:'to walk',cat:'Verbs',sentence:'道を歩きます。',sentenceKana:'みちをあるきます。',sentenceEn:'I walk on the road.'},
  {jp:'走る',kana:'はしる',romaji:'hashiru',en:'to run',cat:'Verbs',sentence:'公園を走ります。',sentenceKana:'こうえんをはしります。',sentenceEn:'I run in the park.'},
  {jp:'立つ',kana:'たつ',romaji:'tatsu',en:'to stand',cat:'Verbs',sentence:'駅に立っています。',sentenceKana:'えきにたっています。',sentenceEn:'I am standing at the station.'},
  {jp:'座る',kana:'すわる',romaji:'suwaru',en:'to sit',cat:'Verbs',sentence:'椅子に座ります。',sentenceKana:'いすにすわります。',sentenceEn:'I sit on a chair.'},
  {jp:'寝る',kana:'ねる',romaji:'neru',en:'to sleep',cat:'Verbs',sentence:'夜10時に寝ます。',sentenceKana:'よるじゅうじにねます。',sentenceEn:'I sleep at 10 PM.'},
  {jp:'起きる',kana:'おきる',romaji:'okiru',en:'to wake up',cat:'Verbs',sentence:'朝6時に起きます。',sentenceKana:'あさろくじにおきます。',sentenceEn:'I wake up at 6 AM.'},
  {jp:'入る',kana:'はいる',romaji:'hairu',en:'to enter',cat:'Verbs',sentence:'教室に入ります。',sentenceKana:'きょうしつにはいります。',sentenceEn:'I enter the classroom.'},
  {jp:'出る',kana:'でる',romaji:'deru',en:'to exit',cat:'Verbs',sentence:'家を出ます。',sentenceKana:'いえをでます。',sentenceEn:'I leave home.'},
  {jp:'開ける',kana:'あける',romaji:'akeru',en:'to open',cat:'Verbs',sentence:'ドアを開けます。',sentenceKana:'どあをあけます。',sentenceEn:'I open the door.'},
  {jp:'閉める',kana:'しめる',romaji:'shimeru',en:'to close',cat:'Verbs',sentence:'窓を閉めます。',sentenceKana:'まどをしめます。',sentenceEn:'I close the window.'},
  {jp:'持つ',kana:'もつ',romaji:'motsu',en:'to hold, carry',cat:'Verbs',sentence:'鞄を持ちます。',sentenceKana:'かばんをもちます。',sentenceEn:'I carry a bag.'},
  {jp:'取る',kana:'とる',romaji:'toru',en:'to take',cat:'Verbs',sentence:'ペンを取ります。',sentenceKana:'ぺんをとります。',sentenceEn:'I take a pen.'},
  {jp:'貸す',kana:'かす',romaji:'kasu',en:'to lend',cat:'Verbs',sentence:'本を貸します。',sentenceKana:'ほんをかします。',sentenceEn:'I lend a book.'},
  {jp:'借りる',kana:'かりる',romaji:'kariru',en:'to borrow',cat:'Verbs',sentence:'図書館で本を借ります。',sentenceKana:'としょかんでほんをかります。',sentenceEn:'I borrow a book from the library.'},
  {jp:'送る',kana:'おくる',romaji:'okuru',en:'to send',cat:'Verbs',sentence:'手紙を送ります。',sentenceKana:'てがみをおくります。',sentenceEn:'I send a letter.'},
  {jp:'洗う',kana:'あらう',romaji:'arau',en:'to wash',cat:'Verbs',sentence:'手を洗います。',sentenceKana:'てをあらいます。',sentenceEn:'I wash my hands.'},
  {jp:'着る',kana:'きる',romaji:'kiru',en:'to wear',cat:'Verbs',sentence:'服を着ます。',sentenceKana:'ふくをきます。',sentenceEn:'I wear clothes.'},
  {jp:'住む',kana:'すむ',romaji:'sumu',en:'to live, reside',cat:'Verbs',sentence:'東京に住んでいます。',sentenceKana:'とうきょうにすんでいます。',sentenceEn:'I live in Tokyo.'},
  {jp:'乗る',kana:'のる',romaji:'noru',en:'to ride, board',cat:'Verbs',sentence:'電車に乗ります。',sentenceKana:'でんしゃにのります。',sentenceEn:'I ride the train.'},
  {jp:'降りる',kana:'おりる',romaji:'oriru',en:'to get off',cat:'Verbs',sentence:'駅で降ります。',sentenceKana:'えきでおります。',sentenceEn:'I get off at the station.'},
  {jp:'始まる',kana:'はじまる',romaji:'hajimaru',en:'to begin',cat:'Verbs',sentence:'授業が始まります。',sentenceKana:'じゅぎょうがはじまります。',sentenceEn:'The class begins.'},
  {jp:'終わる',kana:'おわる',romaji:'owaru',en:'to end, finish',cat:'Verbs',sentence:'授業が終わります。',sentenceKana:'じゅぎょうがおわります。',sentenceEn:'The class ends.'},
  {jp:'呼ぶ',kana:'よぶ',romaji:'yobu',en:'to call',cat:'Verbs',sentence:'友だちを呼びます。',sentenceKana:'ともだちをよびます。',sentenceEn:'I call a friend.'},
  {jp:'歌う',kana:'うたう',romaji:'utau',en:'to sing',cat:'Verbs',sentence:'歌を歌います。',sentenceKana:'うたをうたいます。',sentenceEn:'I sing a song.'},
  {jp:'撮る',kana:'とる',romaji:'toru',en:'to take (a photo)',cat:'Verbs',sentence:'写真を撮ります。',sentenceKana:'しゃしんをとります。',sentenceEn:'I take a photo.'},
  {jp:'消す',kana:'けす',romaji:'kesu',en:'to turn off, erase',cat:'Verbs',sentence:'電気を消します。',sentenceKana:'でんきをけします。',sentenceEn:'I turn off the light.'},
  {jp:'あげる',kana:'あげる',romaji:'ageru',en:'to give',cat:'Verbs',sentence:'友だちにプレゼントをあげます。',sentenceKana:'ともだちにぷれぜんとをあげます。',sentenceEn:'I give a present to a friend.'},
  {jp:'もらう',kana:'もらう',romaji:'morau',en:'to receive',cat:'Verbs',sentence:'友だちからプレゼントをもらいます。',sentenceKana:'ともだちからぷれぜんとをもらいます。',sentenceEn:'I receive a present from a friend.'},
  {jp:'大きい',kana:'おおきい',romaji:'ōkii',en:'big',cat:'Adjectives',sentence:'この家は大きいです。',sentenceKana:'このいえはおおきいです。',sentenceEn:'This house is big.'},
  {jp:'小さい',kana:'ちいさい',romaji:'chiisai',en:'small',cat:'Adjectives',sentence:'この猫は小さいです。',sentenceKana:'このねこはちいさいです。',sentenceEn:'This cat is small.'},
  {jp:'新しい',kana:'あたらしい',romaji:'atarashii',en:'new',cat:'Adjectives',sentence:'新しい車を買いました。',sentenceKana:'あたらしいくるまをかいました。',sentenceEn:'I bought a new car.'},
  {jp:'古い',kana:'ふるい',romaji:'furui',en:'old (thing)',cat:'Adjectives',sentence:'この本は古いです。',sentenceKana:'このほんはふるいです。',sentenceEn:'This book is old.'},
  {jp:'高い',kana:'たかい',romaji:'takai',en:'tall, expensive',cat:'Adjectives',sentence:'このビルは高いです。',sentenceKana:'このびるはたかいです。',sentenceEn:'This building is tall.'},
  {jp:'安い',kana:'やすい',romaji:'yasui',en:'cheap',cat:'Adjectives',sentence:'このペンは安いです。',sentenceKana:'このぺんはやすいです。',sentenceEn:'This pen is cheap.'},
  {jp:'いい',kana:'いい',romaji:'ii',en:'good',cat:'Adjectives',sentence:'天気がいいです。',sentenceKana:'てんきがいいです。',sentenceEn:'The weather is good.'},
  {jp:'悪い',kana:'わるい',romaji:'warui',en:'bad',cat:'Adjectives',sentence:'今日は天気が悪いです。',sentenceKana:'きょうはてんきがわるいです。',sentenceEn:'Today is bad weather.'},
  {jp:'暑い',kana:'あつい',romaji:'atsui',en:'hot (weather)',cat:'Adjectives',sentence:'今日は暑いです。',sentenceKana:'きょうはあついです。',sentenceEn:'It is hot today.'},
  {jp:'寒い',kana:'さむい',romaji:'samui',en:'cold (weather)',cat:'Adjectives',sentence:'今日は寒いです。',sentenceKana:'きょうはさむいです。',sentenceEn:'It is cold today.'},
  {jp:'熱い',kana:'あつい',romaji:'atsui',en:'hot (to touch)',cat:'Adjectives',sentence:'お茶が熱いです。',sentenceKana:'おちゃがあついです。',sentenceEn:'The tea is hot.'},
  {jp:'冷たい',kana:'つめたい',romaji:'tsumetai',en:'cold (to touch)',cat:'Adjectives',sentence:'水が冷たいです。',sentenceKana:'みずがつめたいです。',sentenceEn:'The water is cold.'},
  {jp:'おいしい',kana:'おいしい',romaji:'oishii',en:'delicious',cat:'Adjectives',sentence:'このケーキはおいしいです。',sentenceKana:'このけーきはおいしいです。',sentenceEn:'This cake is delicious.'},
  {jp:'難しい',kana:'むずかしい',romaji:'muzukashii',en:'difficult',cat:'Adjectives',sentence:'日本語は難しいです。',sentenceKana:'にほんごはむずかしいです。',sentenceEn:'Japanese is difficult.'},
  {jp:'易しい',kana:'やさしい',romaji:'yasashii',en:'easy, kind',cat:'Adjectives',sentence:'この問題は易しいです。',sentenceKana:'このもんだいはやさしいです。',sentenceEn:'This problem is easy.'},
  {jp:'楽しい',kana:'たのしい',romaji:'tanoshii',en:'fun, enjoyable',cat:'Adjectives',sentence:'今日は楽しいです。',sentenceKana:'きょうはたのしいです。',sentenceEn:'Today is fun.'},
  {jp:'面白い',kana:'おもしろい',romaji:'omoshiroi',en:'interesting',cat:'Adjectives',sentence:'この本は面白いです。',sentenceKana:'このほんはおもしろいです。',sentenceEn:'This book is interesting.'},
  {jp:'つまらない',kana:'つまらない',romaji:'tsumaranai',en:'boring',cat:'Adjectives',sentence:'この映画はつまらないです。',sentenceKana:'このえいがはつまらないです。',sentenceEn:'This movie is boring.'},
  {jp:'忙しい',kana:'いそがしい',romaji:'isogashii',en:'busy',cat:'Adjectives',sentence:'今日は忙しいです。',sentenceKana:'きょうはいそがしいです。',sentenceEn:'I am busy today.'},
  {jp:'長い',kana:'ながい',romaji:'nagai',en:'long',cat:'Adjectives',sentence:'この川は長いです。',sentenceKana:'このかわはながいです。',sentenceEn:'This river is long.'},
  {jp:'短い',kana:'みじかい',romaji:'mijikai',en:'short',cat:'Adjectives',sentence:'この鉛筆は短いです。',sentenceKana:'このえんぴつはみじかいです。',sentenceEn:'This pencil is short.'},
  {jp:'重い',kana:'おもい',romaji:'omoi',en:'heavy',cat:'Adjectives',sentence:'この荷物は重いです。',sentenceKana:'このにもつはおもいです。',sentenceEn:'This baggage is heavy.'},
  {jp:'軽い',kana:'かるい',romaji:'karui',en:'light (weight)',cat:'Adjectives',sentence:'この鞄は軽いです。',sentenceKana:'このかばんはかるいです。',sentenceEn:'This bag is light.'},
  {jp:'広い',kana:'ひろい',romaji:'hiroi',en:'spacious, wide',cat:'Adjectives',sentence:'この公園は広いです。',sentenceKana:'このこうえんはひろいです。',sentenceEn:'This park is spacious.'},
  {jp:'狭い',kana:'せまい',romaji:'semai',en:'narrow',cat:'Adjectives',sentence:'この部屋は狭いです。',sentenceKana:'このへやはせまいです。',sentenceEn:'This room is narrow.'},
  {jp:'近い',kana:'ちかい',romaji:'chikai',en:'near',cat:'Adjectives',sentence:'駅は近いです。',sentenceKana:'えきはちかいです。',sentenceEn:'The station is near.'},
  {jp:'遠い',kana:'とおい',romaji:'tōi',en:'far',cat:'Adjectives',sentence:'空港は遠いです。',sentenceKana:'くうこうはとおいです。',sentenceEn:'The airport is far.'},
  {jp:'速い',kana:'はやい',romaji:'hayai',en:'fast',cat:'Adjectives',sentence:'この車は速いです。',sentenceKana:'このくるまははやいです。',sentenceEn:'This car is fast.'},
  {jp:'遅い',kana:'おそい',romaji:'osoi',en:'slow, late',cat:'Adjectives',sentence:'電車が遅いです。',sentenceKana:'でんしゃがおそいです。',sentenceEn:'The train is late.'},
  {jp:'強い',kana:'つよい',romaji:'tsuyoi',en:'strong',cat:'Adjectives',sentence:'風が強いです。',sentenceKana:'かぜがつよいです。',sentenceEn:'The wind is strong.'},
  {jp:'弱い',kana:'よわい',romaji:'yowai',en:'weak',cat:'Adjectives',sentence:'彼は弱いです。',sentenceKana:'かれはよわいです。',sentenceEn:'He is weak.'},
  {jp:'明るい',kana:'あかるい',romaji:'akarui',en:'bright',cat:'Adjectives',sentence:'この部屋は明るいです。',sentenceKana:'このへやはあかるいです。',sentenceEn:'This room is bright.'},
  {jp:'暗い',kana:'くらい',romaji:'kurai',en:'dark',cat:'Adjectives',sentence:'夜は暗いです。',sentenceKana:'よるはくらいです。',sentenceEn:'It is dark at night.'},
  {jp:'多い',kana:'おおい',romaji:'ōi',en:'many',cat:'Adjectives',sentence:'人が多いです。',sentenceKana:'ひとがおおいです。',sentenceEn:'There are many people.'},
  {jp:'少ない',kana:'すくない',romaji:'sukunai',en:'few',cat:'Adjectives',sentence:'お金が少ないです。',sentenceKana:'おかねがすくないです。',sentenceEn:'I have little money.'},
  {jp:'若い',kana:'わかい',romaji:'wakai',en:'young',cat:'Adjectives',sentence:'彼は若いです。',sentenceKana:'かれはわかいです。',sentenceEn:'He is young.'},
  {jp:'汚い',kana:'きたない',romaji:'kitanai',en:'dirty',cat:'Adjectives',sentence:'この部屋は汚いです。',sentenceKana:'このへやはきたないです。',sentenceEn:'This room is dirty.'},
  {jp:'危ない',kana:'あぶない',romaji:'abunai',en:'dangerous',cat:'Adjectives',sentence:'この道は危ないです。',sentenceKana:'このみちはあぶないです。',sentenceEn:'This road is dangerous.'},
  {jp:'痛い',kana:'いたい',romaji:'itai',en:'painful',cat:'Adjectives',sentence:'頭が痛いです。',sentenceKana:'あたまがいたいです。',sentenceEn:'My head hurts.'},
  {jp:'欲しい',kana:'ほしい',romaji:'hoshii',en:'wanted, desired',cat:'Adjectives',sentence:'新しい車が欲しいです。',sentenceKana:'あたらしいくるまがほしいです。',sentenceEn:'I want a new car.'},
  {jp:'甘い',kana:'あまい',romaji:'amai',en:'sweet',cat:'Adjectives',sentence:'このケーキは甘いです。',sentenceKana:'このけーきはあまいです。',sentenceEn:'This cake is sweet.'},
  {jp:'辛い',kana:'からい',romaji:'karai',en:'spicy, hot',cat:'Adjectives',sentence:'このカレーは辛いです。',sentenceKana:'このかれーはからいです。',sentenceEn:'This curry is spicy.'},
  {jp:'白い',kana:'しろい',romaji:'shiroi',en:'white',cat:'Adjectives',sentence:'この紙は白いです。',sentenceKana:'このかみはしろいです。',sentenceEn:'This paper is white.'},
  {jp:'黒い',kana:'くろい',romaji:'kuroi',en:'black',cat:'Adjectives',sentence:'この猫は黒いです。',sentenceKana:'このねこはくろいです。',sentenceEn:'This cat is black.'},
  {jp:'赤い',kana:'あかい',romaji:'akai',en:'red',cat:'Adjectives',sentence:'このりんごは赤いです。',sentenceKana:'このりんごはあかいです。',sentenceEn:'This apple is red.'},
  {jp:'青い',kana:'あおい',romaji:'aoi',en:'blue',cat:'Adjectives',sentence:'この空は青いです。',sentenceKana:'このそらはあおいです。',sentenceEn:'This sky is blue.'},
  {jp:'元気',kana:'げんき',romaji:'genki',en:'healthy, energetic',cat:'Na-adjectives',sentence:'彼は元気です。',sentenceKana:'かれはげんきです。',sentenceEn:'He is healthy.'},
  {jp:'きれい',kana:'きれい',romaji:'kirei',en:'pretty, clean',cat:'Na-adjectives',sentence:'この花はきれいです。',sentenceKana:'このはなはきれいです。',sentenceEn:'This flower is pretty.'},
  {jp:'好き',kana:'すき',romaji:'suki',en:'liked, favorite',cat:'Na-adjectives',sentence:'私は音楽が好きです。',sentenceKana:'わたしはおんがくがすきです。',sentenceEn:'I like music.'},
  {jp:'嫌い',kana:'きらい',romaji:'kirai',en:'disliked',cat:'Na-adjectives',sentence:'私は納豆が嫌いです。',sentenceKana:'わたしはなっとうがきらいです。',sentenceEn:'I dislike natto.'},
  {jp:'有名',kana:'ゆうめい',romaji:'yūmei',en:'famous',cat:'Na-adjectives',sentence:'富士山は有名です。',sentenceKana:'ふじさんはゆうめいです。',sentenceEn:'Mt. Fuji is famous.'},
  {jp:'静か',kana:'しずか',romaji:'shizuka',en:'quiet',cat:'Na-adjectives',sentence:'この図書館は静かです。',sentenceKana:'このとしょかんはしずかです。',sentenceEn:'This library is quiet.'},
  {jp:'にぎやか',kana:'にぎやか',romaji:'nigiyaka',en:'lively',cat:'Na-adjectives',sentence:'この町はにぎやかです。',sentenceKana:'このまちはにぎやかです。',sentenceEn:'This town is lively.'},
  {jp:'暇',kana:'ひま',romaji:'hima',en:'free (time)',cat:'Na-adjectives',sentence:'私は今暇です。',sentenceKana:'わたしはいまひまです。',sentenceEn:'I am free now.'},
  {jp:'大変',kana:'たいへん',romaji:'taihen',en:'tough, awful',cat:'Na-adjectives',sentence:'この仕事は大変です。',sentenceKana:'このしごとはたいへんです。',sentenceEn:'This job is tough.'},
  {jp:'便利',kana:'べんり',romaji:'benri',en:'convenient',cat:'Na-adjectives',sentence:'この駅は便利です。',sentenceKana:'このえきはべんりです。',sentenceEn:'This station is convenient.'},
  {jp:'上手',kana:'じょうず',romaji:'jōzu',en:'skilled, good at',cat:'Na-adjectives',sentence:'彼は料理が上手です。',sentenceKana:'かれはりょうりがじょうずです。',sentenceEn:'He is good at cooking.'},
  {jp:'下手',kana:'へた',romaji:'heta',en:'unskilled, bad at',cat:'Na-adjectives',sentence:'私は絵が下手です。',sentenceKana:'わたしはえがへたです。',sentenceEn:'I am bad at drawing.'},
  {jp:'大切',kana:'たいせつ',romaji:'taisetsu',en:'important',cat:'Na-adjectives',sentence:'家族は大切です。',sentenceKana:'かぞくはたいせつです。',sentenceEn:'Family is important.'},
  {jp:'親切',kana:'しんせつ',romaji:'shinsetsu',en:'kind',cat:'Na-adjectives',sentence:'彼は親切です。',sentenceKana:'かれはしんせつです。',sentenceEn:'He is kind.'},
  {jp:'同じ',kana:'おなじ',romaji:'onaji',en:'same',cat:'Na-adjectives',sentence:'これは同じです。',sentenceKana:'これはおなじです。',sentenceEn:'This is the same.'},
  {jp:'簡単',kana:'かんたん',romaji:'kantan',en:'simple, easy',cat:'Na-adjectives',sentence:'この問題は簡単です。',sentenceKana:'このもんだいはかんたんです。',sentenceEn:'This problem is easy.'},
  {jp:'大丈夫',kana:'だいじょうぶ',romaji:'daijōbu',en:'all right, OK',cat:'Na-adjectives',sentence:'私は大丈夫です。',sentenceKana:'わたしはだいじょうぶです。',sentenceEn:'I am OK.'},
  {jp:'とても',kana:'とても',romaji:'totemo',en:'very',cat:'Adverbs',sentence:'今日はとても暑いです。',sentenceKana:'きょうはとてもあついです。',sentenceEn:'It is very hot today.'},
  {jp:'ちょっと',kana:'ちょっと',romaji:'chotto',en:'a little, slightly',cat:'Adverbs',sentence:'ちょっと待ってください。',sentenceKana:'ちょっとまってください。',sentenceEn:'Please wait a moment.'},
  {jp:'少し',kana:'すこし',romaji:'sukoshi',en:'a little, a few',cat:'Adverbs',sentence:'少しお金があります。',sentenceKana:'すこしおかねがあります。',sentenceEn:'I have a little money.'},
  {jp:'たくさん',kana:'たくさん',romaji:'takusan',en:'a lot, many',cat:'Adverbs',sentence:'人がたくさんいます。',sentenceKana:'ひとがたくさんいます。',sentenceEn:'There are many people.'},
  {jp:'よく',kana:'よく',romaji:'yoku',en:'often, well',cat:'Adverbs',sentence:'よくこの店に来ます。',sentenceKana:'よくこのみせにきます。',sentenceEn:'I often come to this store.'},
  {jp:'いつも',kana:'いつも',romaji:'itsumo',en:'always',cat:'Adverbs',sentence:'いつも７時に起きます。',sentenceKana:'いつもしちじにおきます。',sentenceEn:'I always wake up at 7.'},
  {jp:'時々',kana:'ときどき',romaji:'tokidoki',en:'sometimes',cat:'Adverbs',sentence:'時々映画を見ます。',sentenceKana:'ときどきえいがをみます。',sentenceEn:'I sometimes watch movies.'},
  {jp:'あまり',kana:'あまり',romaji:'amari',en:'(not) very',cat:'Adverbs',sentence:'あまり食べません。',sentenceKana:'あまりたべません。',sentenceEn:'I don\'t eat very much.'},
  {jp:'全然',kana:'ぜんぜん',romaji:'zenzen',en:'(not) at all',cat:'Adverbs',sentence:'全然分かりません。',sentenceKana:'ぜんぜんわかりません。',sentenceEn:'I don\'t understand at all.'},
  {jp:'もう',kana:'もう',romaji:'mō',en:'already',cat:'Adverbs',sentence:'もう寝ます。',sentenceKana:'もうねます。',sentenceEn:'I will sleep already.'},
  {jp:'まだ',kana:'まだ',romaji:'mada',en:'still, not yet',cat:'Adverbs',sentence:'まだ食べていません。',sentenceKana:'まだたべていません。',sentenceEn:'I haven\'t eaten yet.'},
  {jp:'すぐ',kana:'すぐ',romaji:'sugu',en:'soon, right away',cat:'Adverbs',sentence:'すぐ行きます。',sentenceKana:'すぐいきます。',sentenceEn:'I will go right away.'},
  {jp:'ゆっくり',kana:'ゆっくり',romaji:'yukkuri',en:'slowly',cat:'Adverbs',sentence:'ゆっくり話してください。',sentenceKana:'ゆっくりはなしてください。',sentenceEn:'Please speak slowly.'},
  {jp:'一番',kana:'いちばん',romaji:'ichiban',en:'most, number one',cat:'Adverbs',sentence:'これが一番好きです。',sentenceKana:'これがいちばんすきです。',sentenceEn:'I like this the most.'},
  {jp:'もっと',kana:'もっと',romaji:'motto',en:'more',cat:'Adverbs',sentence:'もっと勉強します。',sentenceKana:'もっとべんきょうします。',sentenceEn:'I will study more.'},
  {jp:'一緒に',kana:'いっしょに',romaji:'issho ni',en:'together',cat:'Adverbs',sentence:'友だちと一緒に勉強します。',sentenceKana:'ともだちといっしょにべんきょうします。',sentenceEn:'I study together with a friend.'},
  {jp:'本当に',kana:'ほんとうに',romaji:'hontō ni',en:'really, truly',cat:'Adverbs',sentence:'本当に嬉しいです。',sentenceKana:'ほんとうにうれしいです。',sentenceEn:'I am really happy.'},
  {jp:'全部',kana:'ぜんぶ',romaji:'zenbu',en:'all, everything',cat:'Adverbs',sentence:'全部食べました。',sentenceKana:'ぜんぶたべました。',sentenceEn:'I ate everything.'},
  {jp:'何',kana:'なに',romaji:'nani / nan',en:'what',cat:'Questions',sentence:'これは何ですか。',sentenceKana:'これはなんですか。',sentenceEn:'What is this?'},
  {jp:'誰',kana:'だれ',romaji:'dare',en:'who',cat:'Questions',sentence:'あの人は誰ですか。',sentenceKana:'あのひとはだれですか。',sentenceEn:'Who is that person?'},
  {jp:'どこ',kana:'どこ',romaji:'doko',en:'where',cat:'Questions',sentence:'トイレはどこですか。',sentenceKana:'といれはどこですか。',sentenceEn:'Where is the toilet?'},
  {jp:'いつ',kana:'いつ',romaji:'itsu',en:'when',cat:'Questions',sentence:'パーティーはいつですか。',sentenceKana:'ぱーてぃーはいつですか。',sentenceEn:'When is the party?'},
  {jp:'どう',kana:'どう',romaji:'dō',en:'how',cat:'Questions',sentence:'日本語はどうですか。',sentenceKana:'にほんごはどうですか。',sentenceEn:'How is Japanese?'},
  {jp:'どうして',kana:'どうして',romaji:'dōshite',en:'why',cat:'Questions',sentence:'どうして遅れましたか。',sentenceKana:'どうしておくれましたか。',sentenceEn:'Why were you late?'},
  {jp:'いくら',kana:'いくら',romaji:'ikura',en:'how much',cat:'Questions',sentence:'この本はいくらですか。',sentenceKana:'このほんはいくらですか。',sentenceEn:'How much is this book?'},
  {jp:'いくつ',kana:'いくつ',romaji:'ikutsu',en:'how many, how old',cat:'Questions',sentence:'リンゴはいくつありますか。',sentenceKana:'りんごはいくつありますか。',sentenceEn:'How many apples are there?'},
  {jp:'どれ',kana:'どれ',romaji:'dore',en:'which one',cat:'Questions',sentence:'どれがあなたの本ですか。',sentenceKana:'どれがあなたのほんですか。',sentenceEn:'Which one is your book?'},
  {jp:'どの',kana:'どの',romaji:'dono',en:'which (+ noun)',cat:'Questions',sentence:'どの本が好きですか。',sentenceKana:'どのほんがすきですか。',sentenceEn:'Which book do you like?'},
  {jp:'どんな',kana:'どんな',romaji:'donna',en:'what kind of',cat:'Questions',sentence:'どんな食べ物が好きですか。',sentenceKana:'どんなたべものがすきですか。',sentenceEn:'What kind of food do you like?'},
  {jp:'何時',kana:'なんじ',romaji:'nanji',en:'what time',cat:'Questions',sentence:'今何時ですか。',sentenceKana:'いまなんじですか。',sentenceEn:'What time is it now?'},
  {jp:'これ',kana:'これ',romaji:'kore',en:'this one',cat:'Common',sentence:'これはペンです。',sentenceKana:'これはぺんです。',sentenceEn:'This is a pen.'},
  {jp:'それ',kana:'それ',romaji:'sore',en:'that one',cat:'Common',sentence:'それは本です。',sentenceKana:'それはほんです。',sentenceEn:'That is a book.'},
  {jp:'あれ',kana:'あれ',romaji:'are',en:'that one (far)',cat:'Common',sentence:'あれは何ですか。',sentenceKana:'あれはなんですか。',sentenceEn:'What is that over there?'},
  {jp:'ここ',kana:'ここ',romaji:'koko',en:'here',cat:'Common',sentence:'ここに座ってください。',sentenceKana:'ここにすわってください。',sentenceEn:'Please sit here.'},
  {jp:'そこ',kana:'そこ',romaji:'soko',en:'there',cat:'Common',sentence:'そこにあります。',sentenceKana:'そこにあります。',sentenceEn:'It is there.'},
  {jp:'あそこ',kana:'あそこ',romaji:'asoko',en:'over there',cat:'Common',sentence:'あそこに駅があります。',sentenceKana:'あそこにえきがあります。',sentenceEn:'There is a station over there.'},
  {jp:'上',kana:'うえ',romaji:'ue',en:'up, above, on',cat:'Common',sentence:'机の上に本があります。',sentenceKana:'つくえのうえにほんがあります。',sentenceEn:'There is a book on the desk.'},
  {jp:'下',kana:'した',romaji:'shita',en:'down, below, under',cat:'Common',sentence:'机の下に猫がいます。',sentenceKana:'つくえのしたにねこがいます。',sentenceEn:'There is a cat under the desk.'},
  {jp:'中',kana:'なか',romaji:'naka',en:'inside, middle',cat:'Common',sentence:'箱の中に何がありますか。',sentenceKana:'はこのなかにありますか。',sentenceEn:'What is inside the box?'},
  {jp:'外',kana:'そと',romaji:'soto',en:'outside',cat:'Common',sentence:'外は寒いです。',sentenceKana:'そとはさむいです。',sentenceEn:'It is cold outside.'},
  {jp:'前',kana:'まえ',romaji:'mae',en:'front, before',cat:'Common',sentence:'学校の前にいます。',sentenceKana:'がっこうのまえにいます。',sentenceEn:'I am in front of the school.'},
  {jp:'後ろ',kana:'うしろ',romaji:'ushiro',en:'behind, back',cat:'Common',sentence:'後ろに人がいます。',sentenceKana:'うしろにひとがいます。',sentenceEn:'There is a person behind.'},
  {jp:'右',kana:'みぎ',romaji:'migi',en:'right',cat:'Common',sentence:'右に曲がります。',sentenceKana:'みぎにまがります。',sentenceEn:'I turn right.'},
  {jp:'左',kana:'ひだり',romaji:'hidari',en:'left',cat:'Common',sentence:'左に曲がります。',sentenceKana:'ひだりにまがります。',sentenceEn:'I turn left.'},
  {jp:'隣',kana:'となり',romaji:'tonari',en:'next to, neighbor',cat:'Common',sentence:'私の隣に友だちがいます。',sentenceKana:'わたしのとなりにともだちがいます。',sentenceEn:'My friend is next to me.'},
  {jp:'近く',kana:'ちかく',romaji:'chikaku',en:'nearby',cat:'Common',sentence:'近くにスーパーがあります。',sentenceKana:'ちかくにすーぱーがあります。',sentenceEn:'There is a supermarket nearby.'},
  {jp:'日本',kana:'にほん',romaji:'nihon',en:'Japan',cat:'Common',sentence:'日本に行きたいです。',sentenceKana:'にほんにいきたいです。',sentenceEn:'I want to go to Japan.'},
  {jp:'日本語',kana:'にほんご',romaji:'nihongo',en:'Japanese language',cat:'Common',sentence:'日本語を勉強しています。',sentenceKana:'にほんごをべんきょうしています。',sentenceEn:'I am studying Japanese.'},
  {jp:'英語',kana:'えいご',romaji:'eigo',en:'English language',cat:'Common',sentence:'英語が話せます。',sentenceKana:'えいごがはなせます。',sentenceEn:'I can speak English.'},
  {jp:'言葉',kana:'ことば',romaji:'kotoba',en:'word, language',cat:'Common',sentence:'言葉の意味を調べます。',sentenceKana:'ことばのいみをしらべます。',sentenceEn:'I look up the meaning of words.'},
  {jp:'質問',kana:'しつもん',romaji:'shitsumon',en:'question',cat:'Common',sentence:'先生に質問をします。',sentenceKana:'せんせいにしつもんをします。',sentenceEn:'I ask the teacher a question.'},
  {jp:'宿題',kana:'しゅくだい',romaji:'shukudai',en:'homework',cat:'Common',sentence:'宿題をします。',sentenceKana:'しゅくだいをします。',sentenceEn:'I do homework.'},
  {jp:'テスト',kana:'テスト',romaji:'tesuto',en:'test',cat:'Common',sentence:'テストがあります。',sentenceKana:'てすとがあります。',sentenceEn:'There is a test.'},
  {jp:'仕事',kana:'しごと',romaji:'shigoto',en:'work, job',cat:'Common',sentence:'仕事が終わりました。',sentenceKana:'しごとがおわりました。',sentenceEn:'I finished work.'},
  {jp:'意味',kana:'いみ',romaji:'imi',en:'meaning',cat:'Common',sentence:'この言葉の意味は何ですか。',sentenceKana:'このことばのいみはなんですか。',sentenceEn:'What is the meaning of this word?'},
  {jp:'歌',kana:'うた',romaji:'uta',en:'song',cat:'Common',sentence:'歌を歌います。',sentenceKana:'うたをうたいます。',sentenceEn:'I sing a song.'},
  {jp:'音楽',kana:'おんがく',romaji:'ongaku',en:'music',cat:'Common',sentence:'音楽を聞きます。',sentenceKana:'おんがくをききます。',sentenceEn:'I listen to music.'},
  {jp:'映画',kana:'えいが',romaji:'eiga',en:'movie',cat:'Common',sentence:'映画を見ます。',sentenceKana:'えいがをみます。',sentenceEn:'I watch a movie.'},
  {jp:'スポーツ',kana:'スポーツ',romaji:'supōtsu',en:'sport',cat:'Common',sentence:'スポーツが好きです。',sentenceKana:'すぽーつがすきです。',sentenceEn:'I like sports.'},
  {jp:'旅行',kana:'りょこう',romaji:'ryokō',en:'travel, trip',cat:'Common',sentence:'旅行に行きます。',sentenceKana:'りょこうにいきます。',sentenceEn:'I go on a trip.'},
  {jp:'買い物',kana:'かいもの',romaji:'kaimono',en:'shopping',cat:'Common',sentence:'買い物をします。',sentenceKana:'かいものをします。',sentenceEn:'I go shopping.'},
  {jp:'散歩',kana:'さんぽ',romaji:'sanpo',en:'a walk, stroll',cat:'Common',sentence:'散歩をします。',sentenceKana:'さんぽをします。',sentenceEn:'I take a walk.'},
  {jp:'一つ',kana:'ひとつ',romaji:'hitotsu',en:'one (thing)',cat:'Counters',sentence:'リンゴが一つあります。',sentenceKana:'りんごがひとつあります。',sentenceEn:'There is one apple.'},
  {jp:'二つ',kana:'ふたつ',romaji:'futatsu',en:'two (things)',cat:'Counters',sentence:'リンゴが二つあります。',sentenceKana:'りんごがふたつあります。',sentenceEn:'There are two apples.'},
  {jp:'三つ',kana:'みっつ',romaji:'mittsu',en:'three (things)',cat:'Counters',sentence:'リンゴが三つあります。',sentenceKana:'りんごがみっつあります。',sentenceEn:'There are three apples.'},
  {jp:'四つ',kana:'よっつ',romaji:'yottsu',en:'four (things)',cat:'Counters',sentence:'リンゴが四つあります。',sentenceKana:'りんごがよっつあります。',sentenceEn:'There are four apples.'},
  {jp:'五つ',kana:'いつつ',romaji:'itsutsu',en:'five (things)',cat:'Counters',sentence:'リンゴが五つあります。',sentenceKana:'りんごがいつつあります。',sentenceEn:'There are five apples.'},
  {jp:'六つ',kana:'むっつ',romaji:'muttsu',en:'six (things)',cat:'Counters',sentence:'リンゴが六つあります。',sentenceKana:'りんごがむっつあります。',sentenceEn:'There are six apples.'},
  {jp:'七つ',kana:'ななつ',romaji:'nanatsu',en:'seven (things)',cat:'Counters',sentence:'リンゴが七つあります。',sentenceKana:'りんごがななつあります。',sentenceEn:'There are seven apples.'},
  {jp:'八つ',kana:'やっつ',romaji:'yattsu',en:'eight (things)',cat:'Counters',sentence:'リンゴが八つあります。',sentenceKana:'りんごがやっつあります。',sentenceEn:'There are eight apples.'},
  {jp:'九つ',kana:'ここのつ',romaji:'kokonotsu',en:'nine (things)',cat:'Counters',sentence:'リンゴが九つあります。',sentenceKana:'りんごがここのつあります。',sentenceEn:'There are nine apples.'},
  {jp:'とお',kana:'とお',romaji:'tō',en:'ten (things)',cat:'Counters',sentence:'りんごがとおあります。',sentenceKana:'りんごがとおあります。',sentenceEn:'There are ten apples.'},
  {jp:'一人',kana:'ひとり',romaji:'hitori',en:'one person, alone',cat:'Counters',sentence:'一人で行きます。',sentenceKana:'ひとりでいきます。',sentenceEn:'I go alone.'},
  {jp:'二人',kana:'ふたり',romaji:'futari',en:'two people',cat:'Counters',sentence:'二人で行きます。',sentenceKana:'ふたりでいきます。',sentenceEn:'Two of us go.'},
  {jp:'春',kana:'はる',romaji:'haru',en:'spring',cat:'Time',sentence:'春が好きです。',sentenceKana:'はるがすきです。',sentenceEn:'I like spring.'},
  {jp:'夏',kana:'なつ',romaji:'natsu',en:'summer',cat:'Time',sentence:'夏は暑いです。',sentenceKana:'なつはあついです。',sentenceEn:'Summer is hot.'},
  {jp:'秋',kana:'あき',romaji:'aki',en:'autumn',cat:'Time',sentence:'秋は涼しいです。',sentenceKana:'あきはすずしいです。',sentenceEn:'Autumn is cool.'},
  {jp:'冬',kana:'ふゆ',romaji:'fuyu',en:'winter',cat:'Time',sentence:'冬は寒いです。',sentenceKana:'ふゆはさむいです。',sentenceEn:'Winter is cold.'},
  {jp:'毎週',kana:'まいしゅう',romaji:'maishū',en:'every week',cat:'Time',sentence:'毎週映画を見ます。',sentenceKana:'まいしゅうえいがをみます。',sentenceEn:'I watch a movie every week.'},
  {jp:'毎月',kana:'まいつき',romaji:'maitsuki',en:'every month',cat:'Time',sentence:'毎月図書館に行きます。',sentenceKana:'まいつきとしょかんにいきます。',sentenceEn:'I go to the library every month.'},
  {jp:'毎年',kana:'まいとし',romaji:'maitoshi',en:'every year',cat:'Time',sentence:'毎年旅行に行きます。',sentenceKana:'まいとしりょこうにいきます。',sentenceEn:'I go on a trip every year.'},
  {jp:'一昨日',kana:'おととい',romaji:'ototoi',en:'day before yesterday',cat:'Time',sentence:'一昨日は雨でした。',sentenceKana:'おとといはあめでした。',sentenceEn:'It rained the day before yesterday.'},
  {jp:'明後日',kana:'あさって',romaji:'asatte',en:'day after tomorrow',cat:'Time',sentence:'明後日はテストです。',sentenceKana:'あさってはてすとです。',sentenceEn:'The day after tomorrow is the test.'},
  {jp:'誕生日',kana:'たんじょうび',romaji:'tanjōbi',en:'birthday',cat:'Time',sentence:'誕生日にプレゼントをもらいました。',sentenceKana:'たんじょうびにぷれぜんとをもらいました。',sentenceEn:'I received a present on my birthday.'},
  {jp:'休み',kana:'やすみ',romaji:'yasumi',en:'rest, holiday',cat:'Time',sentence:'明日は休みです。',sentenceKana:'あしたはやすみです。',sentenceEn:'Tomorrow is a holiday.'},
  {jp:'時',kana:'とき',romaji:'toki',en:'time, when',cat:'Time',sentence:'その時、私は家にいました。',sentenceKana:'そのとき、わたしはいえにいました。',sentenceEn:'At that time, I was at home.'},
  {jp:'今度',kana:'こんど',romaji:'kondo',en:'next time, this time',cat:'Time',sentence:'今度は京都に行きます。',sentenceKana:'こんどはきょうとにいきます。',sentenceEn:'Next time I will go to Kyoto.'},
  {jp:'死ぬ',kana:'しぬ',romaji:'shinu',en:'to die',cat:'Verbs',sentence:'彼は去年死にました。',sentenceKana:'かれはきょねんしにました。',sentenceEn:'He died last year.'},
  {jp:'飛ぶ',kana:'とぶ',romaji:'tobu',en:'to fly, jump',cat:'Verbs',sentence:'鳥が飛びます。',sentenceKana:'とりがとびます。',sentenceEn:'Birds fly.'},
  {jp:'押す',kana:'おす',romaji:'osu',en:'to push, press',cat:'Verbs',sentence:'ボタンを押します。',sentenceKana:'ぼたんをおします。',sentenceEn:'I push the button.'},
  {jp:'引く',kana:'ひく',romaji:'hiku',en:'to pull',cat:'Verbs',sentence:'ドアを引きます。',sentenceKana:'どあをひきます。',sentenceEn:'I pull the door.'},
  {jp:'切る',kana:'きる',romaji:'kiru',en:'to cut',cat:'Verbs',sentence:'紙を切ります。',sentenceKana:'かみをきります。',sentenceEn:'I cut paper.'},
  {jp:'入れる',kana:'いれる',romaji:'ireru',en:'to put in',cat:'Verbs',sentence:'箱に本を入れます。',sentenceKana:'はこにほんをいれます。',sentenceEn:'I put a book in the box.'},
  {jp:'出す',kana:'だす',romaji:'dasu',en:'to take out, send',cat:'Verbs',sentence:'手紙を出します。',sentenceKana:'てがみをだします。',sentenceEn:'I send a letter.'},
  {jp:'始める',kana:'はじめる',romaji:'hajimeru',en:'to start (something)',cat:'Verbs',sentence:'授業を始めます。',sentenceKana:'じゅぎょうをはじめます。',sentenceEn:'I start the class.'},
  {jp:'着く',kana:'つく',romaji:'tsuku',en:'to arrive',cat:'Verbs',sentence:'駅に着きました。',sentenceKana:'えきにつきました。',sentenceEn:'I arrived at the station.'},
  {jp:'曲がる',kana:'まがる',romaji:'magaru',en:'to turn, bend',cat:'Verbs',sentence:'右に曲がります。',sentenceKana:'みぎにまがります。',sentenceEn:'I turn right.'},
  {jp:'渡る',kana:'わたる',romaji:'wataru',en:'to cross',cat:'Verbs',sentence:'道を渡ります。',sentenceKana:'みちをわたります。',sentenceEn:'I cross the road.'},
  {jp:'渡す',kana:'わたす',romaji:'watasu',en:'to hand over',cat:'Verbs',sentence:'彼に本を渡します。',sentenceKana:'かれにほんをわたします。',sentenceEn:'I hand the book to him.'},
  {jp:'登る',kana:'のぼる',romaji:'noboru',en:'to climb',cat:'Verbs',sentence:'山に登ります。',sentenceKana:'やまにのぼります。',sentenceEn:'I climb the mountain.'},
  {jp:'並ぶ',kana:'ならぶ',romaji:'narabu',en:'to line up',cat:'Verbs',sentence:'列に並びます。',sentenceKana:'れつにならびます。',sentenceEn:'I line up in a queue.'},
  {jp:'並べる',kana:'ならべる',romaji:'naraberu',en:'to arrange',cat:'Verbs',sentence:'本を並べます。',sentenceKana:'ほんをならべます。',sentenceEn:'I arrange the books.'},
  {jp:'困る',kana:'こまる',romaji:'komaru',en:'to be troubled',cat:'Verbs',sentence:'困っています。',sentenceKana:'こまっています。',sentenceEn:'I am troubled.'},
  {jp:'疲れる',kana:'つかれる',romaji:'tsukareru',en:'to get tired',cat:'Verbs',sentence:'仕事で疲れました。',sentenceKana:'しごとでつかれました。',sentenceEn:'I got tired from work.'},
  {jp:'覚える',kana:'おぼえる',romaji:'oboeru',en:'to memorize',cat:'Verbs',sentence:'単語を覚えます。',sentenceKana:'たんごをおぼえます。',sentenceEn:'I memorize vocabulary.'},
  {jp:'忘れる',kana:'わすれる',romaji:'wasureru',en:'to forget',cat:'Verbs',sentence:'忘れました。',sentenceKana:'わすれました。',sentenceEn:'I forgot.'},
  {jp:'なくす',kana:'なくす',romaji:'nakusu',en:'to lose',cat:'Verbs',sentence:'鍵をなくしました。',sentenceKana:'かぎをなくしました。',sentenceEn:'I lost my key.'},
  {jp:'見せる',kana:'みせる',romaji:'miseru',en:'to show',cat:'Verbs',sentence:'写真を見せます。',sentenceKana:'しゃしんをみせます。',sentenceEn:'I show a photo.'},
  {jp:'答える',kana:'こたえる',romaji:'kotaeru',en:'to answer',cat:'Verbs',sentence:'質問に答えます。',sentenceKana:'しつもんにこたえます。',sentenceEn:'I answer the question.'},
  {jp:'出かける',kana:'でかける',romaji:'dekakeru',en:'to go out',cat:'Verbs',sentence:'出かけます。',sentenceKana:'でかけます。',sentenceEn:'I go out.'},
  {jp:'急ぐ',kana:'いそぐ',romaji:'isogu',en:'to hurry',cat:'Verbs',sentence:'急ぎます。',sentenceKana:'いそぎます。',sentenceEn:'I hurry.'},
  {jp:'止まる',kana:'とまる',romaji:'tomaru',en:'to stop (intr.)',cat:'Verbs',sentence:'車が止まります。',sentenceKana:'くるまがとまります。',sentenceEn:'The car stops.'},
  {jp:'止める',kana:'とめる',romaji:'tomeru',en:'to stop (tr.)',cat:'Verbs',sentence:'車を止めます。',sentenceKana:'くるまをとめます。',sentenceEn:'I stop the car.'},
  {jp:'開く',kana:'あく',romaji:'aku',en:'to open (intr.)',cat:'Verbs',sentence:'ドアが開きます。',sentenceKana:'どあがあきます。',sentenceEn:'The door opens.'},
  {jp:'閉まる',kana:'しまる',romaji:'shimaru',en:'to close (intr.)',cat:'Verbs',sentence:'窓が閉まります。',sentenceKana:'まどがしまります。',sentenceEn:'The window closes.'},
  {jp:'要る',kana:'いる',romaji:'iru',en:'to need',cat:'Verbs',sentence:'お金が要ります。',sentenceKana:'おかねがいます。',sentenceEn:'I need money.'},
  {jp:'ある',kana:'ある',romaji:'aru',en:'to be, exist (things)',cat:'Verbs',sentence:'机があります。',sentenceKana:'つくえがあります。',sentenceEn:'There is a desk.'},
  {jp:'いる',kana:'いる',romaji:'iru',en:'to be, exist (living)',cat:'Verbs',sentence:'猫がいます。',sentenceKana:'ねこがいます。',sentenceEn:'There is a cat.'},
  {jp:'吸う',kana:'すう',romaji:'suu',en:'to inhale, smoke',cat:'Verbs',sentence:'空気を吸います。',sentenceKana:'くうきをすいます。',sentenceEn:'I breathe in air.'},
  {jp:'磨く',kana:'みがく',romaji:'migaku',en:'to brush, polish',cat:'Verbs',sentence:'歯を磨きます。',sentenceKana:'はをみがきます。',sentenceEn:'I brush my teeth.'},
  {jp:'浴びる',kana:'あびる',romaji:'abiru',en:'to take (a shower)',cat:'Verbs',sentence:'シャワーを浴びます。',sentenceKana:'しゃわーをあびます。',sentenceEn:'I take a shower.'},
  {jp:'生まれる',kana:'うまれる',romaji:'umareru',en:'to be born',cat:'Verbs',sentence:'彼は日本で生まれました。',sentenceKana:'かれはにほんでうまれました。',sentenceEn:'He was born in Japan.'},
  {jp:'手伝う',kana:'てつだう',romaji:'tetsudau',en:'to help',cat:'Verbs',sentence:'友だちを手伝います。',sentenceKana:'ともだちをてつだいます。',sentenceEn:'I help a friend.'},
  {jp:'かかる',kana:'かかる',romaji:'kakaru',en:'to take (time/money)',cat:'Verbs',sentence:'時間がかかります。',sentenceKana:'じかんがかかります。',sentenceEn:'It takes time.'},
  {jp:'結婚する',kana:'けっこんする',romaji:'kekkon suru',en:'to get married',cat:'Verbs',sentence:'彼は来年結婚します。',sentenceKana:'かれはらいねんけっこんします。',sentenceEn:'He will get married next year.'},
  {jp:'練習する',kana:'れんしゅうする',romaji:'renshū suru',en:'to practice',cat:'Verbs',sentence:'ピアノを練習します。',sentenceKana:'ぴあのをれんしゅうします。',sentenceEn:'I practice the piano.'},
  {jp:'掃除する',kana:'そうじする',romaji:'sōji suru',en:'to clean',cat:'Verbs',sentence:'部屋を掃除します。',sentenceKana:'へやをそうじします。',sentenceEn:'I clean the room.'},
  {jp:'洗濯する',kana:'せんたくする',romaji:'sentaku suru',en:'to do laundry',cat:'Verbs',sentence:'洗濯をします。',sentenceKana:'せんたくをします。',sentenceEn:'I do laundry.'},
  {jp:'低い',kana:'ひくい',romaji:'hikui',en:'low',cat:'Adjectives',sentence:'この机は低いです。',sentenceKana:'このつくえはひくいです。',sentenceEn:'This desk is low.'},
  {jp:'太い',kana:'ふとい',romaji:'futoi',en:'thick, fat',cat:'Adjectives',sentence:'この木は太いです。',sentenceKana:'このきはふといです。',sentenceEn:'This tree is thick.'},
  {jp:'細い',kana:'ほそい',romaji:'hosoi',en:'thin, slender',cat:'Adjectives',sentence:'この鉛筆は細いです。',sentenceKana:'このえんぴつはほそいです。',sentenceEn:'This pencil is thin.'},
  {jp:'丸い',kana:'まるい',romaji:'marui',en:'round',cat:'Adjectives',sentence:'このボールは丸いです。',sentenceKana:'このぼーるはまるいです。',sentenceEn:'This ball is round.'},
  {jp:'うるさい',kana:'うるさい',romaji:'urusai',en:'noisy, annoying',cat:'Adjectives',sentence:'この町はうるさいです。',sentenceKana:'このまちはうるさいです。',sentenceEn:'This town is noisy.'},
  {jp:'眠い',kana:'ねむい',romaji:'nemui',en:'sleepy',cat:'Adjectives',sentence:'私は眠いです。',sentenceKana:'わたしはねむいです。',sentenceEn:'I am sleepy.'},
  {jp:'かわいい',kana:'かわいい',romaji:'kawaii',en:'cute',cat:'Adjectives',sentence:'この猫はかわいいです。',sentenceKana:'このねこはかわいいです。',sentenceEn:'This cat is cute.'},
  {jp:'暖かい',kana:'あたたかい',romaji:'atatakai',en:'warm',cat:'Adjectives',sentence:'今日は暖かいです。',sentenceKana:'きょうはあたたかいです。',sentenceEn:'It is warm today.'},
  {jp:'涼しい',kana:'すずしい',romaji:'suzushii',en:'cool',cat:'Adjectives',sentence:'今日は涼しいです。',sentenceKana:'きょうはすずしいです。',sentenceEn:'It is cool today.'},
  {jp:'まずい',kana:'まずい',romaji:'mazui',en:'bad-tasting',cat:'Adjectives',sentence:'この料理はまずいです。',sentenceKana:'このりょうりはまずいです。',sentenceEn:'This dish tastes bad.'},
  {jp:'苦い',kana:'にがい',romaji:'nigai',en:'bitter',cat:'Adjectives',sentence:'この薬は苦いです。',sentenceKana:'このくすりはにがいです。',sentenceEn:'This medicine is bitter.'},
  {jp:'黄色い',kana:'きいろい',romaji:'kiiroi',en:'yellow',cat:'Adjectives',sentence:'この花は黄色いです。',sentenceKana:'このはなはきいろいです。',sentenceEn:'This flower is yellow.'},
  {jp:'茶色い',kana:'ちゃいろい',romaji:'chairoi',en:'brown',cat:'Adjectives',sentence:'この犬は茶色いです。',sentenceKana:'このいぬはちゃいろいです。',sentenceEn:'This dog is brown.'},
  {jp:'いろいろ',kana:'いろいろ',romaji:'iroiro',en:'various',cat:'Na-adjectives',sentence:'いろいろな本を読みます。',sentenceKana:'いろいろなほんをよみます。',sentenceEn:'I read various books.'},
  {jp:'残念',kana:'ざんねん',romaji:'zannen',en:'unfortunate, a pity',cat:'Na-adjectives',sentence:'それは残念です。',sentenceKana:'それはざんねんです。',sentenceEn:'That is unfortunate.'},
  {jp:'結構',kana:'けっこう',romaji:'kekkō',en:'fine, quite',cat:'Na-adjectives',sentence:'結構いいです。',sentenceKana:'けっこういいです。',sentenceEn:'It is quite good.'},
  {jp:'だんだん',kana:'だんだん',romaji:'dandan',en:'gradually',cat:'Adverbs',sentence:'だんだん寒くなります。',sentenceKana:'だんだんさむくなります。',sentenceEn:'It is getting gradually colder.'},
  {jp:'まっすぐ',kana:'まっすぐ',romaji:'massugu',en:'straight',cat:'Adverbs',sentence:'まっすぐ行ってください。',sentenceKana:'まっすぐいってください。',sentenceEn:'Please go straight.'},
  {jp:'ちょうど',kana:'ちょうど',romaji:'chōdo',en:'exactly, just',cat:'Adverbs',sentence:'ちょうどいいです。',sentenceKana:'ちょうどいいです。',sentenceEn:'It is just right.'},
  {jp:'たぶん',kana:'たぶん',romaji:'tabun',en:'probably',cat:'Adverbs',sentence:'たぶん明日は晴れます。',sentenceKana:'たぶんあしたははれます。',sentenceEn:'It will probably be sunny tomorrow.'},
  {jp:'だいたい',kana:'だいたい',romaji:'daitai',en:'roughly, about',cat:'Adverbs',sentence:'だいたい７時に起きます。',sentenceKana:'だいたいしちじにおきます。',sentenceEn:'I wake up at about 7.'},
  {jp:'もう一度',kana:'もういちど',romaji:'mō ichido',en:'once more',cat:'Adverbs',sentence:'もう一度言ってください。',sentenceKana:'もういちどいってください。',sentenceEn:'Please say it once more.'},
  {jp:'なぜ',kana:'なぜ',romaji:'naze',en:'why',cat:'Adverbs',sentence:'なぜ来ませんでしたか。',sentenceKana:'なぜきませんでしたか。',sentenceEn:'Why didn\'t you come?'},
  {jp:'どうも',kana:'どうも',romaji:'dōmo',en:'thanks; somehow',cat:'Adverbs',sentence:'どうもありがとう。',sentenceKana:'どうもありがとう。',sentenceEn:'Thank you very much.'},
  {jp:'寿司',kana:'すし',romaji:'sushi',en:'sushi',cat:'Food',sentence:'寿司を食べます。',sentenceKana:'すしをたべます。',sentenceEn:'I eat sushi.'},
  {jp:'ラーメン',kana:'ラーメン',romaji:'rāmen',en:'ramen',cat:'Food',sentence:'ラーメンを食べます。',sentenceKana:'らーめんをたべます。',sentenceEn:'I eat ramen.'},
  {jp:'うどん',kana:'うどん',romaji:'udon',en:'udon noodles',cat:'Food',sentence:'うどんを食べます。',sentenceKana:'うどんをたべます。',sentenceEn:'I eat udon.'},
  {jp:'カレー',kana:'カレー',romaji:'karē',en:'curry',cat:'Food',sentence:'カレーを食べます。',sentenceKana:'かれーをたべます。',sentenceEn:'I eat curry.'},
  {jp:'サラダ',kana:'サラダ',romaji:'sarada',en:'salad',cat:'Food',sentence:'サラダを食べます。',sentenceKana:'さらだをたべます。',sentenceEn:'I eat salad.'},
  {jp:'ケーキ',kana:'ケーキ',romaji:'kēki',en:'cake',cat:'Food',sentence:'ケーキを食べます。',sentenceKana:'けーきをたべます。',sentenceEn:'I eat cake.'},
  {jp:'スープ',kana:'スープ',romaji:'sūpu',en:'soup',cat:'Food',sentence:'スープを飲みます。',sentenceKana:'すーぷをのみます。',sentenceEn:'I drink soup.'},
  {jp:'お弁当',kana:'おべんとう',romaji:'obentō',en:'boxed lunch',cat:'Food',sentence:'お弁当を食べます。',sentenceKana:'おべんとうをたべます。',sentenceEn:'I eat a boxed lunch.'},
  {jp:'チョコレート',kana:'チョコレート',romaji:'chokorēto',en:'chocolate',cat:'Food',sentence:'チョコレートを食べます。',sentenceKana:'ちょこれーとをたべます。',sentenceEn:'I eat chocolate.'},
  {jp:'お湯',kana:'おゆ',romaji:'oyu',en:'hot water',cat:'Food',sentence:'お湯を入れます。',sentenceKana:'おゆをいれます。',sentenceEn:'I pour hot water.'},
  {jp:'ワイン',kana:'ワイン',romaji:'wain',en:'wine',cat:'Food',sentence:'ワインを飲みます。',sentenceKana:'わいんをのみます。',sentenceEn:'I drink wine.'},
  {jp:'ベッド',kana:'ベッド',romaji:'beddo',en:'bed',cat:'Objects',sentence:'ベッドで寝ます。',sentenceKana:'べっどでねます。',sentenceEn:'I sleep in bed.'},
  {jp:'テーブル',kana:'テーブル',romaji:'tēburu',en:'table',cat:'Objects',sentence:'テーブルの上に本があります。',sentenceKana:'てーぶるのうえにほんがあります。',sentenceEn:'There is a book on the table.'},
  {jp:'冷蔵庫',kana:'れいぞうこ',romaji:'reizōko',en:'refrigerator',cat:'Objects',sentence:'冷蔵庫に牛乳があります。',sentenceKana:'れいぞうこにぎゅうにゅうがあります。',sentenceEn:'There is milk in the refrigerator.'},
  {jp:'台所',kana:'だいどころ',romaji:'daidokoro',en:'kitchen',cat:'Objects',sentence:'台所で料理をします。',sentenceKana:'だいどころでりょうりをします。',sentenceEn:'I cook in the kitchen.'},
  {jp:'お風呂',kana:'おふろ',romaji:'ofuro',en:'bath',cat:'Objects',sentence:'お風呂に入ります。',sentenceKana:'おふろにはいります。',sentenceEn:'I take a bath.'},
  {jp:'コップ',kana:'コップ',romaji:'koppu',en:'cup, glass',cat:'Objects',sentence:'コップに水を入れます。',sentenceKana:'こっぷにみずをいれます。',sentenceEn:'I put water in a cup.'},
  {jp:'お皿',kana:'おさら',romaji:'osara',en:'plate, dish',cat:'Objects',sentence:'お皿にご飯を盛ります。',sentenceKana:'おさらにはんをよそいます。',sentenceEn:'I put rice on the plate.'},
  {jp:'コート',kana:'コート',romaji:'kōto',en:'coat',cat:'Objects',sentence:'コートを着ます。',sentenceKana:'こーとをきます。',sentenceEn:'I put on a coat.'},
  {jp:'シャツ',kana:'シャツ',romaji:'shatsu',en:'shirt',cat:'Objects',sentence:'シャツを着ます。',sentenceKana:'しゃつをきます。',sentenceEn:'I wear a shirt.'},
  {jp:'ズボン',kana:'ズボン',romaji:'zubon',en:'trousers',cat:'Objects',sentence:'ズボンを履きます。',sentenceKana:'ずぼんをはきます。',sentenceEn:'I put on trousers.'},
  {jp:'切手',kana:'きって',romaji:'kitte',en:'postage stamp',cat:'Objects',sentence:'切手を貼ります。',sentenceKana:'きってをはります。',sentenceEn:'I put a stamp on.'},
  {jp:'はがき',kana:'はがき',romaji:'hagaki',en:'postcard',cat:'Objects',sentence:'はがきを送ります。',sentenceKana:'はがきをおくります。',sentenceEn:'I send a postcard.'},
  {jp:'地図',kana:'ちず',romaji:'chizu',en:'map',cat:'Objects',sentence:'地図を見ます。',sentenceKana:'ちずをみます。',sentenceEn:'I look at a map.'},
  {jp:'荷物',kana:'にもつ',romaji:'nimotsu',en:'luggage, baggage',cat:'Objects',sentence:'荷物を持ちます。',sentenceKana:'にもつをもちます。',sentenceEn:'I carry luggage.'},
  {jp:'プレゼント',kana:'プレゼント',romaji:'purezento',en:'present, gift',cat:'Objects',sentence:'プレゼントをあげます。',sentenceKana:'ぷれぜんとをあげます。',sentenceEn:'I give a present.'},
  {jp:'ネクタイ',kana:'ネクタイ',romaji:'nekutai',en:'necktie',cat:'Objects',sentence:'ネクタイを締めます。',sentenceKana:'ねくたいをしめます。',sentenceEn:'I put on a tie.'},
  {jp:'スプーン',kana:'スプーン',romaji:'supūn',en:'spoon',cat:'Objects',sentence:'スプーンで食べます。',sentenceKana:'すぷーんでたべます。',sentenceEn:'I eat with a spoon.'},
  {jp:'フォーク',kana:'フォーク',romaji:'fōku',en:'fork',cat:'Objects',sentence:'フォークで食べます。',sentenceKana:'ふぉーくでたべます。',sentenceEn:'I eat with a fork.'},
  {jp:'ナイフ',kana:'ナイフ',romaji:'naifu',en:'knife',cat:'Objects',sentence:'ナイフで切ります。',sentenceKana:'ないふできります。',sentenceEn:'I cut with a knife.'},
  {jp:'ラジオ',kana:'ラジオ',romaji:'rajio',en:'radio',cat:'Objects',sentence:'ラジオを聞きます。',sentenceKana:'らじおをききます。',sentenceEn:'I listen to the radio.'},
  {jp:'アパート',kana:'アパート',romaji:'apāto',en:'apartment',cat:'Places',sentence:'アパートに住んでいます。',sentenceKana:'あぱーとにすんでいます。',sentenceEn:'I live in an apartment.'},
  {jp:'建物',kana:'たてもの',romaji:'tatemono',en:'building',cat:'Places',sentence:'この建物は高いです。',sentenceKana:'このたてものはたかいです。',sentenceEn:'This building is tall.'},
  {jp:'ビル',kana:'ビル',romaji:'biru',en:'building (multi-storey)',cat:'Places',sentence:'あのビルは新しです。',sentenceKana:'あのびるはあたらしいです。',sentenceEn:'That building is new.'},
  {jp:'映画館',kana:'えいがかん',romaji:'eigakan',en:'cinema',cat:'Places',sentence:'映画館で映画を見ます。',sentenceKana:'えいがかんでえいがをみます。',sentenceEn:'I watch a movie at the cinema.'},
  {jp:'空港',kana:'くうこう',romaji:'kūkō',en:'airport',cat:'Places',sentence:'空港に行きます。',sentenceKana:'くうこうにいきます。',sentenceEn:'I go to the airport.'},
  {jp:'プール',kana:'プール',romaji:'pūru',en:'swimming pool',cat:'Places',sentence:'プールで泳ぎます。',sentenceKana:'ぷーるでおよぎます。',sentenceEn:'I swim in the pool.'},
  {jp:'本屋',kana:'ほんや',romaji:'honya',en:'bookshop',cat:'Places',sentence:'本屋で本を買います。',sentenceKana:'ほんやでほんをかいます。',sentenceEn:'I buy a book at the bookshop.'},
  {jp:'パン屋',kana:'パンや',romaji:'panya',en:'bakery',cat:'Places',sentence:'パン屋でパンを買います。',sentenceKana:'ぱんやでぱんをかいます。',sentenceEn:'I buy bread at the bakery.'},
  {jp:'角',kana:'かど',romaji:'kado',en:'corner',cat:'Places',sentence:'角を曲がります。',sentenceKana:'かどをまがります。',sentenceEn:'I turn at the corner.'},
  {jp:'横',kana:'よこ',romaji:'yoko',en:'side, beside',cat:'Places',sentence:'机の横に椅子があります。',sentenceKana:'つくえのよこにいすがあります。',sentenceEn:'There is a chair beside the desk.'},
  {jp:'所',kana:'ところ',romaji:'tokoro',en:'place',cat:'Places',sentence:'あそこがいい所です。',sentenceKana:'あそこがいいところです。',sentenceEn:'That is a good place.'},
  {jp:'大人',kana:'おとな',romaji:'otona',en:'adult',cat:'People',sentence:'私は大人です。',sentenceKana:'わたしはおとなです。',sentenceEn:'I am an adult.'},
  {jp:'男の子',kana:'おとこのこ',romaji:'otoko no ko',en:'boy',cat:'People',sentence:'あの男の子は元気です。',sentenceKana:'あのおとこのこはげんきです。',sentenceEn:'That boy is energetic.'},
  {jp:'女の子',kana:'おんなのこ',romaji:'onna no ko',en:'girl',cat:'People',sentence:'あの女の子はかわいいです。',sentenceKana:'あのおんなのこはかわいいです。',sentenceEn:'That girl is cute.'},
  {jp:'おじさん',kana:'おじさん',romaji:'ojisan',en:'uncle, middle-aged man',cat:'People',sentence:'あのおじさんは先生です。',sentenceKana:'あのおじさんはせんせいです。',sentenceEn:'That man is a teacher.'},
  {jp:'おばさん',kana:'おばさん',romaji:'obasan',en:'aunt, middle-aged woman',cat:'People',sentence:'あのおばさんは看護師です。',sentenceKana:'あのおばさんはかんごしです。',sentenceEn:'That woman is a nurse.'},
  {jp:'留学生',kana:'りゅうがくせい',romaji:'ryūgakusei',en:'international student',cat:'People',sentence:'私は留学生です。',sentenceKana:'わたしはりゅうがくせいです。',sentenceEn:'I am an international student.'},
  {jp:'外国人',kana:'がいこくじん',romaji:'gaikokujin',en:'foreigner',cat:'People',sentence:'彼は外国人です。',sentenceKana:'かれはがいこくじんです。',sentenceEn:'He is a foreigner.'},
  {jp:'お客さん',kana:'おきゃくさん',romaji:'okyakusan',en:'guest, customer',cat:'People',sentence:'お客さんが来ました。',sentenceKana:'おきゃくさんがきました。',sentenceEn:'A guest came.'},
  {jp:'犬',kana:'いぬ',romaji:'inu',en:'dog',cat:'Animals',sentence:'犬が好きです。',sentenceKana:'いぬがすきです。',sentenceEn:'I like dogs.'},
  {jp:'猫',kana:'ねこ',romaji:'neko',en:'cat',cat:'Animals',sentence:'猫がいます。',sentenceKana:'ねこがいます。',sentenceEn:'There is a cat.'},
  {jp:'鳥',kana:'とり',romaji:'tori',en:'bird',cat:'Animals',sentence:'鳥が飛びます。',sentenceKana:'とりがとびます。',sentenceEn:'Birds fly.'},
  {jp:'動物',kana:'どうぶつ',romaji:'dōbutsu',en:'animal',cat:'Animals',sentence:'動物が好きです。',sentenceKana:'どうぶつがすきです。',sentenceEn:'I like animals.'},
  {jp:'月',kana:'つき',romaji:'tsuki',en:'moon',cat:'Nature',sentence:'月がきれいです。',sentenceKana:'つきがきれいです。',sentenceEn:'The moon is beautiful.'},
  {jp:'星',kana:'ほし',romaji:'hoshi',en:'star',cat:'Nature',sentence:'星が光っています。',sentenceKana:'ほしがひかっています。',sentenceEn:'Stars are shining.'},
  {jp:'池',kana:'いけ',romaji:'ike',en:'pond',cat:'Nature',sentence:'池に魚がいます。',sentenceKana:'いけにさかながあります。',sentenceEn:'There are fish in the pond.'},
  {jp:'漢字',kana:'かんじ',romaji:'kanji',en:'kanji',cat:'Common',sentence:'漢字を勉強します。',sentenceKana:'かんじをべんきょうします。',sentenceEn:'I study kanji.'},
  {jp:'平仮名',kana:'ひらがな',romaji:'hiragana',en:'hiragana',cat:'Common',sentence:'平仮名を書きます。',sentenceKana:'ひらがなをかきます。',sentenceEn:'I write hiragana.'},
  {jp:'片仮名',kana:'カタカナ',romaji:'katakana',en:'katakana',cat:'Common',sentence:'片仮名を覚えます。',sentenceKana:'かたかなをおぼえます。',sentenceEn:'I memorize katakana.'},
  {jp:'字',kana:'じ',romaji:'ji',en:'letter, character',cat:'Common',sentence:'字がきれいです。',sentenceKana:'じがきれいです。',sentenceEn:'The letters are neat.'},
  {jp:'文',kana:'ぶん',romaji:'bun',en:'sentence',cat:'Common',sentence:'この文を読みます。',sentenceKana:'このぶんをよみます。',sentenceEn:'I read this sentence.'},
  {jp:'番号',kana:'ばんごう',romaji:'bangō',en:'number',cat:'Common',sentence:'番号を書きます。',sentenceKana:'ばんごうをかきます。',sentenceEn:'I write the number.'},
  {jp:'電話番号',kana:'でんわばんごう',romaji:'denwa bangō',en:'phone number',cat:'Common',sentence:'電話番号を教えてください。',sentenceKana:'でんわばんごうをおしえてください。',sentenceEn:'Please tell me your phone number.'},
  {jp:'問題',kana:'もんだい',romaji:'mondai',en:'problem, question',cat:'Common',sentence:'問題を解きます。',sentenceKana:'もんだいをときます。',sentenceEn:'I solve the problem.'},
  {jp:'答え',kana:'こたえ',romaji:'kotae',en:'answer',cat:'Common',sentence:'答えを書きます。',sentenceKana:'こたえをかきます。',sentenceEn:'I write the answer.'},
  {jp:'試験',kana:'しけん',romaji:'shiken',en:'examination',cat:'Common',sentence:'試験を受けます。',sentenceKana:'しけんをうけます。',sentenceEn:'I take an examination.'},
  {jp:'授業',kana:'じゅぎょう',romaji:'jugyō',en:'class, lesson',cat:'Common',sentence:'授業に出ます。',sentenceKana:'じゅぎょうにでます。',sentenceEn:'I attend class.'},
  {jp:'練習',kana:'れんしゅう',romaji:'renshū',en:'practice',cat:'Common',sentence:'練習をします。',sentenceKana:'れんしゅうをします。',sentenceEn:'I practice.'},
  {jp:'趣味',kana:'しゅみ',romaji:'shumi',en:'hobby',cat:'Common',sentence:'趣味は何ですか。',sentenceKana:'しゅみはなんですか。',sentenceEn:'What is your hobby?'},
  {jp:'病気',kana:'びょうき',romaji:'byōki',en:'illness',cat:'Common',sentence:'彼は病気です。',sentenceKana:'かれはびょうきです。',sentenceEn:'He is ill.'},
  {jp:'薬',kana:'くすり',romaji:'kusuri',en:'medicine',cat:'Common',sentence:'薬を飲みます。',sentenceKana:'くすりをのみます。',sentenceEn:'I take medicine.'},
  {jp:'色',kana:'いろ',romaji:'iro',en:'colour',cat:'Common',sentence:'色がきれいです。',sentenceKana:'いろがきれいです。',sentenceEn:'The colour is nice.'},
  {jp:'声',kana:'こえ',romaji:'koe',en:'voice',cat:'Common',sentence:'声が大きいです。',sentenceKana:'こえがおおきいです。',sentenceEn:'The voice is loud.'},
  {jp:'音',kana:'おと',romaji:'oto',en:'sound',cat:'Common',sentence:'音が聞こえます。',sentenceKana:'おとがきこえます。',sentenceEn:'I can hear a sound.'},
  {jp:'切符',kana:'きっぷ',romaji:'kippu',en:'ticket',cat:'Common',sentence:'切符を買います。',sentenceKana:'きっぷをかいます。',sentenceEn:'I buy a ticket.'},
  {jp:'自分',kana:'じぶん',romaji:'jibun',en:'oneself',cat:'Common',sentence:'自分でします。',sentenceKana:'じぶんでします。',sentenceEn:'I do it myself.'},
  {jp:'みんな',kana:'みんな',romaji:'minna',en:'everyone',cat:'Common',sentence:'みんな来ました。',sentenceKana:'みんなきました。',sentenceEn:'Everyone came.'},
  {jp:'パーティー',kana:'パーティー',romaji:'pātī',en:'party',cat:'Common',sentence:'パーティーに行きます。',sentenceKana:'ぱーてぃーにいきます。',sentenceEn:'I go to the party.'},
  {jp:'ニュース',kana:'ニュース',romaji:'nyūsu',en:'news',cat:'Common',sentence:'ニュースを見ます。',sentenceKana:'にゅーすをみます。',sentenceEn:'I watch the news.'},
  {jp:'何曜日',kana:'なんようび',romaji:'nan\'yōbi',en:'what day of the week',cat:'Questions',sentence:'今日は何曜日ですか。',sentenceKana:'きょうはなんようびですか。',sentenceEn:'What day of the week is it today?'},
  {jp:'何月',kana:'なんがつ',romaji:'nangatsu',en:'what month',cat:'Questions',sentence:'今日は何月ですか。',sentenceKana:'きょうはなんがつですか。',sentenceEn:'What month is it today?'},
  {jp:'何日',kana:'なんにち',romaji:'nannichi',en:'what day, how many days',cat:'Questions',sentence:'今日は何日ですか。',sentenceKana:'きょうはなんにちですか。',sentenceEn:'What day of the month is it today?'},
  {jp:'一月',kana:'いちがつ',romaji:'ichigatsu',en:'January',cat:'Time',sentence:'一月は寒いです。',sentenceKana:'いちがつはさむいです。',sentenceEn:'January is cold.'},
  {jp:'二月',kana:'にがつ',romaji:'nigatsu',en:'February',cat:'Time',sentence:'二月は寒いです。',sentenceKana:'にがつはさむいです。',sentenceEn:'February is cold.'},
  {jp:'三月',kana:'さんがつ',romaji:'sangatsu',en:'March',cat:'Time',sentence:'三月は暖かいです。',sentenceKana:'さんがつはあたたかいです。',sentenceEn:'March is warm.'},
  {jp:'四月',kana:'しがつ',romaji:'shigatsu',en:'April',cat:'Time',sentence:'四月は桜が咲きます。',sentenceKana:'しがつはさくらがさきます。',sentenceEn:'Cherry blossoms bloom in April.'},
  {jp:'五月',kana:'ごがつ',romaji:'gogatsu',en:'May',cat:'Time',sentence:'五月は気持ちいいです。',sentenceKana:'ごがつはきもちいいです。',sentenceEn:'May is pleasant.'},
  {jp:'六月',kana:'ろくがつ',romaji:'rokugatsu',en:'June',cat:'Time',sentence:'六月は雨が多いです。',sentenceKana:'ろくがつはあめがおおいです。',sentenceEn:'June has a lot of rain.'},
  {jp:'七月',kana:'しちがつ',romaji:'shichigatsu',en:'July',cat:'Time',sentence:'七月は暑いです。',sentenceKana:'しちがつはあついです。',sentenceEn:'July is hot.'},
  {jp:'八月',kana:'はちがつ',romaji:'hachigatsu',en:'August',cat:'Time',sentence:'八月も暑いです。',sentenceKana:'はちがつもあついです。',sentenceEn:'August is also hot.'},
  {jp:'九月',kana:'くがつ',romaji:'kugatsu',en:'September',cat:'Time',sentence:'九月は涼しいです。',sentenceKana:'くがつはすずしいです。',sentenceEn:'September is cool.'},
  {jp:'十月',kana:'じゅうがつ',romaji:'jūgatsu',en:'October',cat:'Time',sentence:'十月は秋です。',sentenceKana:'じゅうがつはあきです。',sentenceEn:'October is autumn.'},
  {jp:'十一月',kana:'じゅういちがつ',romaji:'jūichigatsu',en:'November',cat:'Time',sentence:'十一月は寒くなります。',sentenceKana:'じゅういちがつはさむくなります。',sentenceEn:'November gets colder.'},
  {jp:'十二月',kana:'じゅうにがつ',romaji:'jūnigatsu',en:'December',cat:'Time',sentence:'十二月は寒いです。',sentenceKana:'じゅうにがつはさむいです。',sentenceEn:'December is cold.'},
  {jp:'一日',kana:'ついたち',romaji:'tsuitachi',en:'1st (of the month)',cat:'Time',sentence:'今日は一日です。',sentenceKana:'きょうはついたちです。',sentenceEn:'Today is the 1st.'},
  {jp:'二日',kana:'ふつか',romaji:'futsuka',en:'2nd; two days',cat:'Time',sentence:'今日は二日です。',sentenceKana:'きょうはふつかです。',sentenceEn:'Today is the 2nd.'},
  {jp:'三日',kana:'みっか',romaji:'mikka',en:'3rd; three days',cat:'Time',sentence:'今日は三日です。',sentenceKana:'きょうはみっかです。',sentenceEn:'Today is the 3rd.'},
  {jp:'四日',kana:'よっか',romaji:'yokka',en:'4th; four days',cat:'Time',sentence:'今日は四日です。',sentenceKana:'きょうはよっかです。',sentenceEn:'Today is the 4th.'},
  {jp:'五日',kana:'いつか',romaji:'itsuka',en:'5th; five days',cat:'Time',sentence:'今日は五日です。',sentenceKana:'きょうはいつかです。',sentenceEn:'Today is the 5th.'},
  {jp:'六日',kana:'むいか',romaji:'muika',en:'6th; six days',cat:'Time',sentence:'今日は六日です。',sentenceKana:'きょうはむいかです。',sentenceEn:'Today is the 6th.'},
  {jp:'七日',kana:'なのか',romaji:'nanoka',en:'7th; seven days',cat:'Time',sentence:'今日は七日です。',sentenceKana:'きょうはなのかです。',sentenceEn:'Today is the 7th.'},
  {jp:'八日',kana:'ようか',romaji:'yōka',en:'8th; eight days',cat:'Time',sentence:'今日は八日です。',sentenceKana:'きょうはようかです。',sentenceEn:'Today is the 8th.'},
  {jp:'九日',kana:'ここのか',romaji:'kokonoka',en:'9th; nine days',cat:'Time',sentence:'今日は九日です。',sentenceKana:'きょうはここのかです。',sentenceEn:'Today is the 9th.'},
  {jp:'十日',kana:'とおか',romaji:'tōka',en:'10th; ten days',cat:'Time',sentence:'今日は十日です。',sentenceKana:'きょうはとおかです。',sentenceEn:'Today is the 10th.'},
  {jp:'二十日',kana:'はつか',romaji:'hatsuka',en:'20th; twenty days',cat:'Time',sentence:'今日は二十日です。',sentenceKana:'きょうははつかです。',sentenceEn:'Today is the 20th.'},
  {jp:'東',kana:'ひがし',romaji:'higashi',en:'east',cat:'Directions',sentence:'東の方に行きます。',sentenceKana:'ひがしのほうにいきます。',sentenceEn:'I go east.'},
  {jp:'西',kana:'にし',romaji:'nishi',en:'west',cat:'Directions',sentence:'西の方に行きます。',sentenceKana:'にしのほうにいきます。',sentenceEn:'I go west.'},
  {jp:'南',kana:'みなみ',romaji:'minami',en:'south',cat:'Directions',sentence:'南の方に行きます。',sentenceKana:'みなみのほうにいきます。',sentenceEn:'I go south.'},
  {jp:'北',kana:'きた',romaji:'kita',en:'north',cat:'Directions',sentence:'北の方に行きます。',sentenceKana:'きたのほうにいきます。',sentenceEn:'I go north.'},
  {jp:'赤',kana:'あか',romaji:'aka',en:'red',cat:'Colours',sentence:'このりんごは赤です。',sentenceKana:'このりんごはあかです。',sentenceEn:'This apple is red.'},
  {jp:'青',kana:'あお',romaji:'ao',en:'blue',cat:'Colours',sentence:'この空は青です。',sentenceKana:'このそらはあおです。',sentenceEn:'This sky is blue.'},
  {jp:'白',kana:'しろ',romaji:'shiro',en:'white',cat:'Colours',sentence:'この紙は白です。',sentenceKana:'このかみはしろです。',sentenceEn:'This paper is white.'},
  {jp:'黒',kana:'くろ',romaji:'kuro',en:'black',cat:'Colours',sentence:'この猫は黒です。',sentenceKana:'このねこはくろです。',sentenceEn:'This cat is black.'},
  {jp:'緑',kana:'みどり',romaji:'midori',en:'green',cat:'Colours',sentence:'この葉っぱは緑です。',sentenceKana:'このはっぱはみどりです。',sentenceEn:'This leaf is green.'},
  {jp:'黄色',kana:'きいろ',romaji:'kiiro',en:'yellow',cat:'Colours',sentence:'この花は黄色です。',sentenceKana:'このはなはきいろです。',sentenceEn:'This flower is yellow.'},
  {jp:'茶色',kana:'ちゃいろ',romaji:'chairo',en:'brown',cat:'Colours',sentence:'この犬は茶色です。',sentenceKana:'このいぬはちゃいろです。',sentenceEn:'This dog is brown.'},
  {jp:'ピンク',kana:'ピンク',romaji:'pinku',en:'pink',cat:'Colours',sentence:'この花はピンクです。',sentenceKana:'このはなはぴんくです。',sentenceEn:'This flower is pink.'},
  {jp:'笑う',kana:'わらう',romaji:'warau',en:'to laugh, smile',cat:'Verbs',sentence:'彼は笑います。',sentenceKana:'かれはわらいます。',sentenceEn:'He laughs.'},
  {jp:'脱ぐ',kana:'ぬぐ',romaji:'nugu',en:'to take off (clothes)',cat:'Verbs',sentence:'靴を脱ぎます。',sentenceKana:'くつをぬぎます。',sentenceEn:'I take off my shoes.'},
  {jp:'履く',kana:'はく',romaji:'haku',en:'to wear (shoes, trousers)',cat:'Verbs',sentence:'靴を履きます。',sentenceKana:'くつをはきます。',sentenceEn:'I put on shoes.'},
  {jp:'かぶる',kana:'かぶる',romaji:'kaburu',en:'to wear (on the head)',cat:'Verbs',sentence:'帽子をかぶります。',sentenceKana:'ぼうしをかぶります。',sentenceEn:'I put on a hat.'},
  {jp:'かける',kana:'かける',romaji:'kakeru',en:'to hang; to make (a call)',cat:'Verbs',sentence:'眼鏡をかけます。',sentenceKana:'めがねをかけます。',sentenceEn:'I put on glasses.'},
  {jp:'運ぶ',kana:'はこぶ',romaji:'hakobu',en:'to carry',cat:'Verbs',sentence:'荷物を運びます。',sentenceKana:'にもつをはこびます。',sentenceEn:'I carry luggage.'},
  {jp:'やめる',kana:'やめる',romaji:'yameru',en:'to quit, stop',cat:'Verbs',sentence:'仕事をやめます。',sentenceKana:'しごとをやめます。',sentenceEn:'I quit my job.'},
  {jp:'払う',kana:'はらう',romaji:'harau',en:'to pay',cat:'Verbs',sentence:'お金を払います。',sentenceKana:'おかねをはらいます。',sentenceEn:'I pay money.'},
  {jp:'返す',kana:'かえす',romaji:'kaesu',en:'to return (something)',cat:'Verbs',sentence:'本を返します。',sentenceKana:'ほんをかえします。',sentenceEn:'I return a book.'},
  {jp:'電話する',kana:'でんわする',romaji:'denwa suru',en:'to phone, call',cat:'Verbs',sentence:'友だちに電話します。',sentenceKana:'ともだちにでんわします。',sentenceEn:'I call a friend.'},
  {jp:'質問する',kana:'しつもんする',romaji:'shitsumon suru',en:'to ask a question',cat:'Verbs',sentence:'先生に質問します。',sentenceKana:'せんせいにしつもんします。',sentenceEn:'I ask the teacher a question.'},
  {jp:'初めて',kana:'はじめて',romaji:'hajimete',en:'for the first time',cat:'Adverbs',sentence:'初めて日本に来ました。',sentenceKana:'はじめてにほんにきました。',sentenceEn:'I came to Japan for the first time.'},
  {jp:'後で',kana:'あとで',romaji:'ato de',en:'later',cat:'Adverbs',sentence:'後で会いましょう。',sentenceKana:'あとであいましょう。',sentenceEn:'Let\'s meet later.'},
  {jp:'バナナ',kana:'バナナ',romaji:'banana',en:'banana',cat:'Food',sentence:'バナナを食べます。',sentenceKana:'ばななをたべます。',sentenceEn:'I eat a banana.'},
  {jp:'オレンジ',kana:'オレンジ',romaji:'orenji',en:'orange',cat:'Food',sentence:'オレンジを食べます。',sentenceKana:'おれんじをたべます。',sentenceEn:'I eat an orange.'},
  {jp:'トマト',kana:'トマト',romaji:'tomato',en:'tomato',cat:'Food',sentence:'トマトを食べます。',sentenceKana:'とまとをたべます。',sentenceEn:'I eat a tomato.'},
  {jp:'いちご',kana:'いちご',romaji:'ichigo',en:'strawberry',cat:'Food',sentence:'いちごを食べます。',sentenceKana:'いちごをたべます。',sentenceEn:'I eat a strawberry.'},
  {jp:'食事',kana:'しょくじ',romaji:'shokuji',en:'meal',cat:'Food',sentence:'食事をします。',sentenceKana:'しょくじをします。',sentenceEn:'I have a meal.'},
  {jp:'タオル',kana:'タオル',romaji:'taoru',en:'towel',cat:'Objects',sentence:'タオルを使います。',sentenceKana:'たおるをつかいます。',sentenceEn:'I use a towel.'},
  {jp:'消しゴム',kana:'けしゴム',romaji:'keshigomu',en:'eraser',cat:'Objects',sentence:'消しゴムで消します。',sentenceKana:'けしごむでけします。',sentenceEn:'I erase with an eraser.'},
  {jp:'漫画',kana:'まんが',romaji:'manga',en:'comic, manga',cat:'Objects',sentence:'漫画を読みます。',sentenceKana:'まんがをよみます。',sentenceEn:'I read manga.'},
  {jp:'絵',kana:'え',romaji:'e',en:'picture, drawing',cat:'Objects',sentence:'絵を描きます。',sentenceKana:'えをかきます。',sentenceEn:'I draw a picture.'},
  {jp:'箱',kana:'はこ',romaji:'hako',en:'box',cat:'Objects',sentence:'箱の中に何がありますか。',sentenceKana:'はこのなかにありますか。',sentenceEn:'What is inside the box?'},
  {jp:'お手洗い',kana:'おてあらい',romaji:'otearai',en:'restroom',cat:'Places',sentence:'お手洗いはどこですか。',sentenceKana:'おてあらいはどこですか。',sentenceEn:'Where is the restroom?'},
  {jp:'寺',kana:'てら',romaji:'tera',en:'temple',cat:'Places',sentence:'寺に行きます。',sentenceKana:'てらにいきます。',sentenceEn:'I go to the temple.'},
  {jp:'赤ちゃん',kana:'あかちゃん',romaji:'akachan',en:'baby',cat:'People',sentence:'赤ちゃんが泣いています。',sentenceKana:'あかちゃんがないています。',sentenceEn:'The baby is crying.'},
  {jp:'お兄さん',kana:'おにいさん',romaji:'onīsan',en:'older brother (someone\'s)',cat:'People',sentence:'お兄さんは大学生です。',sentenceKana:'おにいさんはだいがくせいです。',sentenceEn:'My older brother is a university student.'},
  {jp:'お姉さん',kana:'おねえさん',romaji:'onēsan',en:'older sister (someone\'s)',cat:'People',sentence:'お姉さんは看護師です。',sentenceKana:'おねえさんはかんごしです。',sentenceEn:'My older sister is a nurse.'},
  {jp:'おじいさん',kana:'おじいさん',romaji:'ojīsan',en:'grandfather, old man',cat:'People',sentence:'おじいさんは元気です。',sentenceKana:'おじいさんはげんきです。',sentenceEn:'Grandfather is healthy.'},
  {jp:'おばあさん',kana:'おばあさん',romaji:'obāsan',en:'grandmother, old woman',cat:'People',sentence:'おばあさんは優しいです。',sentenceKana:'おばあさんはやさしいです。',sentenceEn:'Grandmother is kind.'},
  {jp:'皆さん',kana:'みなさん',romaji:'minasan',en:'everyone (polite)',cat:'People',sentence:'皆さん、こんにちは。',sentenceKana:'みなさん、こんにちは。',sentenceEn:'Hello everyone.'},
  {jp:'方',kana:'かた',romaji:'kata',en:'person (polite)',cat:'People',sentence:'あの方は先生です。',sentenceKana:'あのほうはせんせいです。',sentenceEn:'That person is a teacher.'},
  {jp:'指',kana:'ゆび',romaji:'yubi',en:'finger',cat:'Body',sentence:'指が痛いです。',sentenceKana:'ゆびがいたいです。',sentenceEn:'My finger hurts.'},
  {jp:'テニス',kana:'テニス',romaji:'tenisu',en:'tennis',cat:'Leisure',sentence:'テニスをします。',sentenceKana:'てにすをします。',sentenceEn:'I play tennis.'},
  {jp:'サッカー',kana:'サッカー',romaji:'sakkā',en:'soccer',cat:'Leisure',sentence:'サッカーをします。',sentenceKana:'さっかーをします。',sentenceEn:'I play soccer.'},
  {jp:'野球',kana:'やきゅう',romaji:'yakyū',en:'baseball',cat:'Leisure',sentence:'野球をします。',sentenceKana:'やきゅうをします。',sentenceEn:'I play baseball.'},
  {jp:'ピアノ',kana:'ピアノ',romaji:'piano',en:'piano',cat:'Leisure',sentence:'ピアノを弾きます。',sentenceKana:'ぴあのをひきます。',sentenceEn:'I play the piano.'},
  {jp:'雲',kana:'くも',romaji:'kumo',en:'cloud',cat:'Nature',sentence:'雲が白いです。',sentenceKana:'くもがしろいです。',sentenceEn:'The clouds are white.'},
  {jp:'すごい',kana:'すごい',romaji:'sugoi',en:'amazing, great',cat:'Adjectives',sentence:'この映画はすごいです。',sentenceKana:'このえいがはすごいです。',sentenceEn:'This movie is amazing.'},
  {jp:'世界',kana:'せかい',romaji:'sekai',en:'world',cat:'Common',sentence:'世界は広いです。',sentenceKana:'せかいはひろいです。',sentenceEn:'The world is wide.'},
  {jp:'場所',kana:'ばしょ',romaji:'basho',en:'place, location',cat:'Common',sentence:'いい場所です。',sentenceKana:'いいばしょです。',sentenceEn:'It\'s a good place.'},
  {jp:'約束',kana:'やくそく',romaji:'yakusoku',en:'promise, appointment',cat:'Common',sentence:'約束を守ります。',sentenceKana:'やくそくをまもります。',sentenceEn:'I keep the promise.'},
  {jp:'親',kana:'おや',romaji:'oya',en:'parent',cat:'Common',sentence:'親に電話します。',sentenceKana:'おやにでんわします。',sentenceEn:'I call my parents.'},
  {jp:'味',kana:'あじ',romaji:'aji',en:'taste, flavour',cat:'Common',sentence:'味がいいです。',sentenceKana:'あじがいいです。',sentenceEn:'The taste is good.'},
  {jp:'間',kana:'あいだ',romaji:'aida',en:'interval, between',cat:'Common',sentence:'間に合います。',sentenceKana:'あいだにあります。',sentenceEn:'I\'m on time.'},
  {jp:'勉強',kana:'べんきょう',romaji:'benkyō',en:'study',cat:'Common',sentence:'勉強をします。',sentenceKana:'べんきょうをします。',sentenceEn:'I study.'},
  {jp:'たばこ',kana:'たばこ',romaji:'tabako',en:'cigarette, tobacco',cat:'Common',sentence:'たばこを吸いません。',sentenceKana:'たばこをすいません。',sentenceEn:'I don\'t smoke.'}
];

export { N5_VOCAB };