
[
  {"id":1,"point":"は (wa)"},
  {"id":2,"point":"です / だ"},
  {"id":3,"point":"が (ga)"},
  {"id":4,"point":"を (o)"},
  {"id":5,"point":"に (ni)"},
  {"id":6,"point":"で (de)"},
  {"id":7,"point":"へ (e)"},
  {"id":8,"point":"と (to)"},
  {"id":9,"point":"も (mo)"},
  {"id":10,"point":"の (no)"},
  {"id":11,"point":"か (ka)"},
  {"id":12,"point":"～ます / ～ません"},
  {"id":13,"point":"～ました / ～ませんでした"},
  {"id":14,"point":"～ませんか"},
  {"id":15,"point":"～ましょう"},
  {"id":16,"point":"い-adjectives"},
  {"id":17,"point":"な-adjectives"},
  {"id":18,"point":"これ / それ / あれ"},
  {"id":19,"point":"この / その / あの + noun"},
  {"id":20,"point":"～たい"},
  {"id":21,"point":"～てください"},
  {"id":22,"point":"～ています"},
  {"id":23,"point":"ある / いる"},
  {"id":24,"point":"から / まで"},
  {"id":25,"point":"～が、～"},
  {"id":26,"point":"～じゃありません"},
  {"id":27,"point":"～でした"},
  {"id":28,"point":"い-adjective past (～かった)"},
  {"id":29,"point":"～て (te-form)"},
  {"id":30,"point":"～から (because)"},
  {"id":31,"point":"～ないでください"},
  {"id":32,"point":"～ましょうか"},
  {"id":33,"point":"～がほしい"},
  {"id":34,"point":"～が上手 / 下手"},
  {"id":35,"point":"もう / まだ"},
  {"id":36,"point":"～や～"},
  {"id":37,"point":"～ね / ～よ"},
  {"id":38,"point":"～くなる / ～になる"},
  {"id":39,"point":"一番"},
  {"id":40,"point":"～より"},
  {"id":41,"point":"～前に / ～後で"},
  {"id":42,"point":"～のほうが"},
  {"id":43,"point":"～でしょう"},
  {"id":44,"point":"そして / それから"},
  {"id":45,"point":"でも"},
  {"id":46,"point":"～ことができる"},
  {"id":47,"point":"何か・誰か・どこか"}
]
